;*********************************************************************************************************
; 
; Autogenerated by DizAssembler:
;   https://github.com/codenjoyme/8080-emulator/blob/master/src/main/java/spec/assembler/DizAssembler.java
; From: 'src/main/resources/lik/roms/02_mon-1m.bin' in range [C800:CFFF]
;       and partially 'src/main/resources/lik/roms/03_mon-1m_basicLik.bin' in range: [D000:D23F]
; In test: DizAssemblerTest.testDecompileTest_lik_romMonitor()
; 
;*********************************************************************************************************

         CPU  8080
         .ORG 0C800h
ljyzh    EQU 00000h
ljyzj    EQU 00100h
lnoto    EQU 00CC6h
lnhhj    EQU 01323h
lnqez    EQU 01826h
lnitx    EQU 02477h
ljpog    EQU 027CDh
lounp    EQU 07E26h
lohyk    EQU 07FFFh
lcmxb    EQU 08B40h
lgcux    EQU 08B46h
lcakd    EQU 08B49h
lcjml    EQU 08B4Ch
lcmyh    EQU 08F40h
lgfwx    EQU 08F42h
lfttv    EQU 08F43h
lcjxn    EQU 08F44h
lbxul    EQU 08F45h
lfqtb    EQU 08F47h
lcalj    EQU 08F49h
lftjz    EQU 08F4Bh
lcjnr    EQU 08F4Ch
lbxkp    EQU 08F4Dh
lgcmh    EQU 08F4Eh
lcmvv    EQU 08F50h
lcast    EQU 08F51h
lcmvf    EQU 08F70h
lfqgd    EQU 08F7Fh
lcava    EQU 08F81h
lgfws    EQU 08F82h
lfttq    EQU 08F83h
lfqsw    EQU 08F87h
lgctm    EQU 08F96h
lcmlu    EQU 08F98h
lcais    EQU 08F99h
lcauo    EQU 08FE1h
lftte    EQU 08FE3h
lgftu    EQU 08FF2h
lcjko    EQU 08FFCh
lbxhm    EQU 08FFDh
lgcje    EQU 08FFEh
lfqgc    EQU 08FFFh
lgeaj    EQU 0903Eh
lcunh    EQU 0BC00h
lgozx    EQU 0C037h
ldlfj    EQU 0C170h
lgozr    EQU 0C337h
lgozv    EQU 0C377h
ldlfq    EQU 0C3D0h
lcysc    EQU 0C3F9h
lhehl    EQU 0C422h
lgpdp    EQU 0C427h
lhaui    EQU 0C4BEh
ldmvl    EQU 0D240h
lgunu    EQU 0EFFFh
ldsxd    EQU 0F000h
ldgub    EQU 0F001h
lhlvt    EQU 0F002h
lgzsr    EQU 0F003h
ldgqd    EQU 0FF01h
ldldh:   LXI SP,lohyk
         LXI H,0C800h
         SHLD lcauo
         LXI H,ldmvb
         CALL lgont
         LXI H,lcmvv
         CALL lgozr
         CPI 00Dh
         JZ lhbar
         MVI B,020h
ldhqf:   MVI M,000h
         INX H
         DCR B
         JNZ ldhqf
         LXI H,lcmvv
         MVI B,000h
ldksv:   CPI 008h
         JZ lcvpo
         CPI 018h
         JZ lgrmm
         CPI 05Fh
         JZ lcyps
         CPI 07Fh
         JZ lcyps
         CPI 00Dh
         JZ ldkto
         CPI 020h
         JC ldlcv
         CPI 02Ah
         JNC lcvpt
         ADI 010h
lcvpt:   CPI 03Ch
         JNZ ldiaf
         SUI 010h
ldiaf:   MOV M,A
         CALL lcvmr
         INX H
         INR B
         MOV A,B
         CPI 020h
         JZ lcvpa
ldlcv:   CALL lgozr
         JMP ldksv
lhbar:   LXI H,lcmvv
         CALL lgont
         JMP ldlcv
lgont:   MVI B,000h
lcyxh:   MOV A,M
         ORA A
         RZ
         MOV C,A
         CALL lcvoa
         INX H
         INR B
         JMP lcyxh
lcvmr:   PUSH PSW
         MVI C,07Fh
         CALL lcvoa
         MVI C,008h
         CALL lcvoa
         POP PSW
         MOV C,A
         JMP lcvoa
lcvpo:   MOV C,A
         MOV A,B
         ORA A
         JZ ldlcv
         DCR B
         DCX H
         CALL lcvoa
         JMP ldlcv
lgrmm:   MOV C,A
         MOV A,M
         ORA A
         JZ ldlcv
         INX H
         INR B
         CALL lcvoa
         JMP ldlcv
lcyps:   MOV A,B
         ORA A
         JZ ldlcv
         MOV A,M
         ORA A
         JNZ ldlcv
         DCR B
         DCX H
         MOV M,A
         MVI C,008h
         CALL lcvoa
         MVI C,07Fh
         CALL lcvoa
         MVI C,008h
         CALL lcvoa
         JMP ldlcv
ldkto:   LXI H,lgtqq
         LDA lcmvv
         MOV C,A
lgooi:   MOV A,M
         INX H
         ORA A
         JZ lcvpa
         CMP C
         JZ lhaoy
         INX H
         INX H
         JMP lgooi
lhaoy:   MOV E,M
         INX H
         MOV D,M
         PUSH D
         LXI H,lcmvv
         MOV A,M
         CPI 04Fh
         PUSH PSW
         CZ ldkqp
         POP PSW
         CPI 049h
         PUSH PSW
         CZ ldkqp
         POP PSW
         CPI 047h
         CZ ldkqp
         LXI B,ljyzh
         CALL lcvnf
         PUSH D
         ORA A
         JZ lgovr
         CALL lcvnf
         PUSH D
         ORA A
         JZ ldkrb
         CALL lcvnf
         PUSH D
         ORA A
         JNZ lcvpa
         JMP lcynz
lgovr:   PUSH B
ldkrb:   PUSH B
lcynz:   POP B
         POP D
         POP H
         RET
lcvnf:   LXI D,ljyzh
ldlct:   INX H
         MOV A,M
         CPI 02Ch
         JZ lgrol
         ORA A
         JNZ ldlct
lgrol:   PUSH H
         CALL ldhsx
         MOV E,A
         CALL ldhsx
         CALL lgoyh
         ORA E
         MOV E,A
         CALL ldhsx
         MOV D,A
         CALL ldhsx
         CALL lgoyh
         ORA D
         MOV D,A
ldict:   POP H
         MOV A,M
         RET
lgoyh:   RLC
         RLC
         RLC
         RLC
         RET
ldhsx:   DCX H
         PUSH D
         LXI D,lcmvv
         CALL lgpdp
         POP D
         JZ ldhzr
         MOV A,M
         CPI 02Ch
         JZ ldhzr
         ORA A
         JZ ldhzr
         SUI 030h
         CPI 00Ah
         RC
         SUI 007h
         CPI 00Ah
         JC lcvpa
         CPI 010h
         RC
         JMP lcvpa
ldhzr:   POP H
         JMP ldict
ldkqp:   LXI H,lcmvf
         MVI C,010h
lcvmt:   MVI M,000h
         INX H
         DCR C
         JNZ lcvmt
         LXI H,lcast
         LXI D,lcmvf
         MVI C,010h
         MOV A,M
         CPI 03Dh
         JNZ lcvpa
         INX H
lgrwk:   MOV A,M
         ORA A
         RZ
         CPI 020h
         JC lcvpa
         CPI 02Ch
         RZ
         CPI 07Fh
         JNC lcvpa
         STAX D
         INX H
         INX D
         DCR C
         JNZ lgrwk
         JMP lcvpa
lcvpa:   LXI H,lgqdn
         CALL lgont
         JMP ldldh
         PUSH H
         LXI H,0C800h
         XTHL
         PCHL
ldhpq:   MOV M,C
         CALL lgpdp
         JZ ldldh
         INX H
         JMP ldhpq
         CALL lcvpu
         JMP ldldh
lcvpu:   MOV A,H
         CMP B
         JC lcvza
         JNZ lhdpu
         MOV A,L
         CMP C
         JC lcvza
lhdpu:   MOV A,M
         STAX B
         CALL lgpdp
         RZ
         INX H
         INX B
         JMP lhdpu
lcvza:   CALL lgrvy
ldkta:   LDAX D
         STAX B
         CALL lgpdp
         RZ
         DCX D
         DCX B
         JMP ldkta
lgrvy:   PUSH H
         PUSH B
         ORA A
         MOV A,E
         SUB L
         MOV C,A
         MOV A,D
         SBB H
         JC lcvzd
         MOV B,A
         POP H
         DAD B
         PUSH H
         POP B
         POP H
         RET
lcvzd:   POP B
         POP H
         RET
         MOV M,E
         JMP ldldh
ldhsj:   MOV A,M
         CMP C
         CZ lgrmf
         CALL lgpdp
         JZ ldldh
         INX H
         JMP ldhsj
lgrmf:   PUSH B
         PUSH H
         CALL lcvxq
         MVI B,003h
lheaz:   CALL lgomi
         MOV A,M
         CALL lhbci
         DCR B
         INX H
         JNZ lheaz
         POP H
         POP B
         RET
lcywv:   LDAX B
         CMP M
         CNZ lczab
         CALL lgpdp
         JZ ldldh
         INX H
         INX B
         JMP lcywv
lczab:   PUSH B
         CALL lgozk
         CALL lgoob
         XTHL
         CALL lgoob
         XTHL
         POP B
         RET
lgoob:   CALL lgomi
         CALL ldhua
         CALL lgomi
         MOV A,M
         CALL lhbci
         JMP lgomi
lgolp:   MVI C,01Fh
         CALL lcvoa
         MOV B,L
         CALL ldlcf
         CALL ldlcf
         CALL lgozk
         SHLD lgcmh
         MVI D,010h
lgrvp:   CALL ldlac
         DCR D
         JNZ lgrvp
         PUSH H
         LXI H,lcxot
         CALL lgont
         POP H
lhebo:   CALL lgozr
         CPI 00Dh
         JZ lgolp
         LXI D,ljyzh
         CPI 008h
         JZ ldlci
         CPI 018h
         JNZ ldldh
         PUSH H
         LXI H,lounp
         MVI A,0FFh
         JMP lcvym
ldlci:   XRA A
         PUSH H
         LXI H,lnqez
lcvym:   SHLD lcalj
         LXI H,lnqez
         SHLD lbxul
         LXI H,lounp
         SHLD lfqtb
         STA lftjz
lgouq:   LHLD lcalj
         SHLD lcjko
         LDA lftjz
         MOV H,A
         CALL lgozr
         CPI 00Dh
         JZ lhbak
         CPI 008h
         JZ ldkst
         CPI 018h
         JZ ldlda
         CPI 019h
         JZ lhaot
         CPI 01Ah
         JZ lgryd
         MOV C,A
         LDA lftjz
         CPI 0FFh
         JZ ldicl
         MOV A,C
         CPI 020h
         JC lharf
         CPI 02Ah
         JNC lhaxw
         ADI 010h
         JMP ldhsl
lhaxw:   CPI 030h
         JC lharf
         CPI 03Ah
         JC ldhsl
         CPI 041h
         JC lharf
         CPI 047h
         JNC lharf
         SUI 007h
ldhsl:   SUI 030h
         MOV C,A
         LDA lftjz
         ORA A
         MOV A,C
         MVI B,0F0h
         JNZ ldlcl
         MVI B,00Fh
         RLC
         RLC
         RLC
         RLC
         MOV C,A
ldlcl:   LHLD lgcmh
         DAD D
         MOV A,M
         ANA B
         ORA C
         MOV M,A
         MOV A,M
         LHLD lbxul
         SHLD lcjko
         PUSH PSW
         CALL lcyyi
         POP PSW
         LHLD lfqtb
         SHLD lcjko
         CALL lhapl
         LDA lftjz
         MOV H,A
         JMP ldlda
ldicl:   CPI 020h
         JC lharf
         MVI B,000h
         JMP ldlcl
lharf:   MVI A,0FFh
         STA lgftu
         CALL ldlfj
         MVI A,040h
         STA lgftu
         JMP lgouq
lhaot:   MVI B,0F8h
         JMP lcvws
lgryd:   MVI B,008h
         JMP lcvws
ldkst:   MVI B,0FFh
         LDA lftjz
         CPI 0FFh
         JZ lcvws
         ORA A
         MVI A,001h
         JZ lhdox
         XRA A
         MOV B,A
lhdox:   STA lftjz
         JMP lcvws
ldlda:   MVI B,001h
         LDA lftjz
         CPI 0FFh
         JZ lcvws
         ORA A
         MVI A,000h
         JNZ lhdox
         MOV B,A
         INR A
         JMP lhdox
lcvws:   MOV A,E
         ADD B
         CPI 080h
         JC lgrxy
         MOV A,H
         STA lftjz
         JMP lharf
lgrxy:   MOV E,A
         PUSH D
         ANI 007h
         MOV B,A
         ADD B
         ADD B
         MOV B,A
         ADI 07Eh
         MOV D,A
         MOV A,B
         RLC
         RLC
         ADI 018h
         MOV H,A
         MOV A,E
         ANI 078h
         RRC
         RRC
         RRC
         MOV B,A
         ADD B
         ADD B
         ADD B
         ADD B
         ADD B
         ADD B
         ADD B
         ADD B
         ADD B
         ADI 026h
         MOV E,A
         MOV L,A
         SHLD lbxul
         XCHG
         SHLD lfqtb
         POP D
         LDA lftjz
         CPI 0FFh
         JZ ldlco
         LHLD lbxul
         MOV B,A
         ADD B
         ADD B
         ADD H
         MOV H,A
ldlco:   SHLD lcalj
         JMP lgouq
lhbak:   LXI H,lnoto
         SHLD lcjko
         POP H
         JMP lhebo
ldlac:   CALL ldhua
         MVI C,03Ah
         CALL lcvoa
         MVI B,008h
         MVI A,07Eh
         STA lbxkp
         MVI A,018h
         STA lcjnr
ldidt:   LDA lcjnr
         STA lbxhm
         ADI 00Ch
         STA lcjnr
         MOV A,M
         CALL lhbci
         LDA lbxkp
         STA lbxhm
         ADI 003h
         STA lbxkp
         MOV A,M
         CALL lgrpp
         INX H
         DCR B
         JNZ ldidt
         CALL lgozk
         RET
lgrpp:   CPI 020h
         JC lcyon
         CPI 07Fh
         JNC lcyon
         MOV C,A
         JMP lcvoa
lcyon:   MVI C,02Eh
         JMP lcvoa
lhapl:   CPI 020h
         JC lgrqj
         CPI 07Fh
         JNC lgrqj
         JMP lcvmr
lgrqj:   MVI A,02Eh
         JMP lcvmr
ldlcf:   MVI D,008h
         MVI A,07Eh
         STA lbxkp
         MVI A,018h
         STA lcjnr
ldhrp:   MOV A,B
         INR B
         CALL lcwaa
         MOV C,A
         LDA lcjnr
         STA lbxhm
         ADI 00Ch
         STA lcjnr
         CALL lcvoa
         LDA lbxkp
         STA lbxhm
         ADI 003h
         STA lbxkp
         CALL lcvoa
         DCR D
         JNZ ldhrp
         CALL lgozk
         RET
lhbci:   PUSH D
         PUSH B
         CALL lhazw
         MOV C,D
         CALL ldlbs
         MOV C,E
         CALL ldlbs
         POP B
         POP D
         RET
lhazw:   MOV E,A
         RRC
         RRC
         RRC
         RRC
         CALL lcwaa
         MOV D,A
         MOV A,E
         CALL lcwaa
         MOV E,A
         RET
lcwaa:   ANI 00Fh
         CPI 00Ah
         JC lharw
         ADI 007h
lharw:   ADI 030h
         RET
lcyyi:   PUSH D
         CALL lhazw
         MOV A,D
         CALL lcvmr
         MOV A,E
         CALL lcvmr
         POP D
         RET
lgomi:   PUSH B
         MVI C,020h
         CALL lcvoa
         POP B
         RET
lgozk:   MVI C,00Ah
         JMP lcvoa
ldhua:   MOV A,H
         CALL lhbci
         MOV A,L
         JMP lhbci
ldibk:   MVI C,0FFh
lhbaa:   XRA A
         CALL ldlfq
         DCR C
         JNZ lhbaa
         MVI A,0E6h
         CALL ldlfq
         MOV A,L
         CALL ldlfq
         MOV A,H
         CALL ldlfq
         MOV A,E
         CALL ldlfq
         MOV A,D
         CALL ldlfq
lgrxc:   MOV A,M
         CALL ldlfq
         CALL lgpdp
         RZ
         INX H
         JMP lgrxc
lgomm:   PUSH H
         LXI H,lcunh
         SHLD lfqgd
         MOV A,C
         ORA A
         JZ lhasp
         STA lgcje
lhasp:   POP H
         PUSH H
         CALL lgrql
         SHLD lcava
         LXI H,lcmvf
         PUSH D
         LXI D,lgfws
         CALL ldibk
         POP D
         POP H
         JMP ldibk
         LDA lcmxb
         CPI 031h
         CZ lcakd
         CALL lgomm
         JMP ldldh
         CALL ldibk
         JMP ldldh
lcyop:   LHLD lgcje
         JMP lcvop
         CALL lgrql
         JMP ldldh
         CALL lcyop
         JMP ldldh
lgrql:   LXI B,ljyzh
lhast:   MOV A,M
         ADD C
         MOV C,A
         MOV A,B
         ADC M
         MOV B,A
         CALL lgpdp
         INX H
         JNZ lhast
         PUSH B
         POP H
lcvop:   JMP lcvxq
ldled:   PUSH H
         PUSH D
lhect:   LXI H,lfttq
         LXI D,lcais
         CALL lhehl
         LHLD lgctm
         LXI D,lcunh
         CALL lgpdp
         JNZ lhect
         CALL lhaso
         LXI H,lcmvf
         LXI D,lfqsw
ldleo:   LDAX D
         ORA A
         JZ lgoww
         CMP M
         INX H
         INX D
         JZ ldleo
         JMP lhect
lhaso:   LXI H,lfqsw
         CALL lgozk
         JMP lgont
lgoww:   LXI H,lhfhj
         CALL lgont
         POP D
         POP H
         CALL ldhrq
         JZ lcysc
         PUSH H
         INX H
         INX H
         INX H
         INX H
         SHLD lftte
         INX D
         INX D
         INX D
         INX D
         POP H
         JMP lhehl
lcvxq:   CALL lgozk
         JMP ldhua
         CALL lhecs
         JMP ldldh
         CALL lhecs
         PUSH H
         LXI H,0C800h
         XTHL
         PCHL
         CALL ldhrq
         JZ lhbac
         CALL lhehl
         JMP ldldh
lhbac:   CALL lcysc
         JMP ldldh
ldhrq:   XRA A
         ORA H
         ORA L
         ORA D
         ORA E
         RET
lhecs:   LDA lcmxb
         CPI 031h
         CZ lcjml
         MOV A,C
         ORA A
         JZ lheag
         STA lfqgc
lheag:   CALL ldled
         LHLD lftte
         PUSH H
         CALL lcvxq
         XCHG
         CALL lcvxq
         PUSH H
         LHLD lcmlu
         CALL lcvxq
         XTHL
         XCHG
         CALL lgrql
         XCHG
         XTHL
         XCHG
         CALL lgpdp
         POP D
         JNZ lcvpa
         POP H
         RET
         MVI C,000h
         CALL lcvpx
         MVI C,0FFh
         CALL lcvpx
         JMP ldldh
         MVI C,0FFh
         CALL lcvpx
         JMP ldldh
lcvpx:   MVI A,0FFh
         CALL lgozv
         MOV L,A
         MVI A,008h
         CALL lgozv
         MOV H,A
         MVI A,008h
         CALL lgozv
         MOV E,A
         MVI A,008h
         CALL lgozv
         MOV D,A
lcwan:   MVI A,008h
         CALL lgozv
         SUB M
         ANA C
         JNZ lcvpa
         CALL lgpdp
         RZ
         INX H
         JMP lcwan
         LXI H,ldmvl
         LXI D,lgunu
         LXI B,ljyzh
         CALL lcvpu
         RST 0
         MVI A,090h
         STA lgzsr
lcyqv:   MOV A,H
         STA lhlvt
         MOV A,L
         STA ldgub
         LDA ldsxd
         STAX B
         CALL lgpdp
         JZ ldldh
         INX H
         INX B
         JMP lcyqv
         LDA lcmxb
         CPI 031h
         JNZ lcvpa
         MOV A,L
         ORA A
         JZ lcmxb
         JMP lgcux
ldlbs:   LDA ldgqd
         CPI 07Ch
         JC ldldh
         CPI 080h
         CC lgozr
lcvoa:   MOV A,C
         CPI 00Ah
         JNZ lgozx
         LDA lcjko
         CPI 0EEh
         JC lgozx
         MVI C,00Dh
         PUSH D
         PUSH H
         MVI L,000h
         MVI E,00Ah
lgrwq:   MVI H,090h
         MOV D,H
lhayy:   LDAX D
         MOV M,A
         INR H
         INR D
         MOV A,D
         CPI 0C0h
         JNZ lhayy
         INR L
         INR E
         JNZ lgrwq
         POP H
         POP D
         JMP lgozx
lhdtc:   SHLD lcmyh
         XRA A
         STA lcjnr
         MOV C,M
         MOV A,C
         CALL lhazf
         PUSH H
         LHLD lcmyh
         CALL lcvxq
         CALL lgomi
         MOV C,B
lczaq:   CALL lgomi
         MOV A,M
         CALL lhbci
         DCR C
         INX H
         JNZ lczaq
         MVI A,030h
         STA lbxhm
         LHLD lcmyh
         MOV C,B
lhazc:   MOV A,M
         PUSH B
         CALL lgrpp
         POP B
         INX H
         DCR C
         JNZ lhazc
         MVI A,03Fh
         STA lbxhm
         LXI H,lhfug
lcyrj:   DCR D
         JZ lhazr
lcvqp:   MOV A,M
         INX H
         RAL
         JNC lcvqp
         JMP lcyrj
lhazr:   CALL ldktz
         CALL lgomi
         POP H
         INR E
lhapv:   DCR E
         JZ lgrpj
lhech:   MOV A,M
         INX H
         RAL
         JC lhapv
         JMP lhech
lgrpj:   CALL ldktz
         MOV A,B
         LHLD lcmyh
         INX H
         DCR A
         JZ lcypb
         PUSH PSW
         LDA lcjnr
         ORA A
         MVI C,020h
         JZ lgrzz
         MVI C,02Ch
lgrzz:   CALL lcvoa
         POP PSW
         DCR A
         JZ lcvyd
         MOV E,M
         INX H
         MOV D,M
         XCHG
         CALL ldhua
         JMP lcypb
lcvyd:   MOV A,M
         CALL lhbci
lcypb:   LHLD lcmyh
         MVI D,000h
         MOV E,B
         DAD D
         JMP lhdtc
lgrzj:   INR D
         INR D
         INR D
         INR D
         RET
ldktz:   MOV A,M
         ANI 07Fh
         MOV C,A
         CALL lcvoa
         MOV A,M
         INX H
         RAL
         JNC ldktz
         RET
lhazf:   MVI B,001h
         LXI D,ljyzj
         LXI H,lhfjz
         ORA A
         RZ
         INR D
         CPI 076h
         RZ
         INR D
         CPI 040h
         JC lgovy
         CPI 080h
         JNC lhctp
         LXI H,lgqqp
         PUSH H
         ANI 038h
         RRC
         RRC
         RRC
         ADD L
         MOV L,A
         MOV A,M
         ANI 07Fh
         STA lgfwx
         MVI A,02Ch
         STA lfttv
         MOV A,C
         ANI 007h
         POP H
         ADD L
         MOV L,A
         MOV A,M
         ORI 080h
         STA lcjxn
         LXI H,lgfwx
         MVI E,000h
         RET
lgovy:   INR D
         ANI 00Fh
         RZ
         CPI 008h
         RZ
         INR B
         INR B
         MOV A,C
         INR D
         CPI 022h
         RZ
         INR D
         CPI 032h
         RZ
         INR D
         CPI 02Ah
         RZ
         INR D
         CPI 03Ah
         RZ
         DCR B
         DCR B
         INR D
         CPI 007h
         RZ
         INR D
         CPI 017h
         RZ
         INR D
         CPI 027h
         RZ
         INR D
         CPI 037h
         RZ
         INR D
         CPI 00Fh
         RZ
         INR D
         CPI 01Fh
         RZ
         INR D
         CPI 02Fh
         RZ
         INR D
         CPI 03Fh
         RZ
         LXI H,lgqgt
         ANI 030h
         RRC
         RRC
         RRC
         RRC
         MOV E,A
         MOV A,C
         ANI 00Fh
         INR D
         CPI 002h
         RZ
         INR D
         CPI 00Ah
         RZ
         INR D
         CPI 004h
         RZ
         LXI H,lhchj
         CPI 00Ch
         RZ
         INR D
         CPI 00Dh
         RZ
         LXI H,lgqgt
         CPI 005h
         RZ
         INR B
         INR D
         CPI 006h
         CZ ldjir
         RZ
         LXI H,lhchj
         CPI 00Eh
         CZ ldjir
         RZ
         LXI H,lgtox
         INR B
         INR D
         CPI 001h
         CZ ldjir
         RZ
         INR D
         DCR B
         DCR B
         CPI 003h
         RZ
         INR D
         CPI 009h
         RZ
         INR D
         CPI 00Bh
         RZ
lhctp:   MOV A,C
         CPI 0C0h
         JNC ldmvd
         LXI H,lgqqp
         ANI 007h
         MOV E,A
         MOV A,C
         ANI 038h
         RRC
         RRC
         RRC
         ADI 01Ah
         MOV D,A
         RET
ldjir:   STA lcjnr
         RET
ldmvd:   MVI D,022h
         MVI B,003h
         LXI H,lhfjz
         CPI 0C3h
         RZ
         INR D
         CPI 0CDh
         RZ
         INR D
         DCR B
         CPI 0D3h
         RZ
         INR D
         CPI 0DBh
         RZ
         ANI 00Fh
         DCR B
         INR D
         CPI 00Dh
         RZ
         INR D
         MOV A,C
         ANI 030h
         RRC
         RRC
         RRC
         RRC
         MOV E,A
         ADD D
         MOV D,A
         MOV A,C
         ANI 00Fh
         INR B
         CPI 006h
         RZ
         CALL lgrzj
         CPI 00Eh
         RZ
         CALL lgrzj
         DCR B
         CPI 003h
         RZ
         CALL lgrzj
         CPI 009h
         RZ
         CALL lgrzj
         CPI 00Bh
         RZ
         MVI D,03Bh
         LXI H,ldmjn
         CPI 001h
         RZ
         INR D
         CPI 005h
         RZ
         LXI H,lhftv
         INR D
         CPI 007h
         RZ
         LXI H,lhctb
         CPI 00Fh
         RZ
         INR D
         LXI H,lhcjf
         ORA A
         RZ
         MVI B,003h
         INR D
         CPI 002h
         RZ
         INR D
         CPI 004h
         RZ
         INR D
         MVI B,001h
         LXI H,ldafv
         CPI 008h
         RZ
         INR D
         MVI B,003h
         CPI 00Ah
         RZ
         INR D
         RET

lgtqq:   DB 04Ah, 0B6h, 0C9h, 046h, 0BCh, 0C9h, 054h, 0C7h, 0C9h, 044h
         DB 05Fh, 0CAh, 04Fh, 025h, 0CDh, 04Dh, 008h, 0CAh, 053h, 00Ch
         DB 0CAh, 043h, 031h, 0CAh, 04Bh, 03Fh, 0CDh, 058h, 045h, 0CDh
         DB 049h, 0BBh, 0CDh, 047h, 0C1h, 0CDh, 04Ch, 0CAh, 0CDh, 056h
         DB 018h, 0CEh, 057h, 025h, 0CEh, 052h, 064h, 0CEh, 042h, 057h
         DB 0CEh, 041h, 0CAh, 0CEh, 050h, 080h, 0CEh, 051h, 033h, 0CDh
         DB 000h
ldmvb:   DB 00Ah, 02Ah, 020h, 06Dh, 06Fh, 06Eh, 069h, 074h, 06Fh, 072h
         DB 02Dh, 031h, 06Dh, 020h, 02Ah, 00Ah, 03Dh, 03Dh, 03Dh, 03Eh
         DB 000h
lcxot:   DB 03Dh, 03Dh, 03Dh, 03Eh, 000h
lhfhj:   DB 020h, 03Ch, 03Dh, 03Dh, 000h
lgqdn:   DB 020h, 06Fh, 07Bh, 069h, 062h, 06Bh, 061h, 000h
lgqqp:   DB 0C2h, 0C3h, 0C4h, 0C5h, 0C8h, 0CCh, 0CDh, 0C1h
lgqgt:   DB 0C2h, 0C4h, 0C8h, 0CDh
lgtox:   DB 0C2h, 0C4h, 0C8h, 053h, 0D0h
ldmjn:   DB 0C2h, 0C4h, 0C8h, 050h, 053h, 0D7h
lhchj:   DB 0C3h, 0C5h, 0CCh, 0C1h
lhftv:   DB 0B0h, 0B2h, 0B4h, 0B6h
lhctb:   DB 0B1h, 0B3h, 0B5h, 0B7h
lhfjz:   DB 088h, 088h, 088h, 088h
lhcjf:   DB 008h, 04Eh, 0DAh, 008h, 04Eh, 0C3h, 008h, 050h, 0CFh, 008h
         DB 0D0h
ldafv:   DB 008h, 0DAh, 008h, 0C3h, 008h, 050h, 0C5h, 008h, 0CDh
lhfug:   DB 04Eh, 04Fh, 0D0h, 048h, 04Ch, 0D4h, 04Dh, 04Fh, 0D6h, 03Fh
         DB 03Fh, 0BFh, 053h, 048h, 04Ch, 0C4h, 053h, 054h, 0C1h, 04Ch
         DB 048h, 04Ch, 0C4h, 04Ch, 044h, 0C1h, 052h, 04Ch, 0C3h, 052h
         DB 041h, 0CCh, 044h, 041h, 0C1h, 053h, 054h, 0C3h, 052h, 052h
         DB 0C3h, 052h, 041h, 0D2h, 043h, 04Dh, 0C1h, 043h, 04Dh, 0C3h
         DB 053h, 054h, 041h, 0D8h, 04Ch, 044h, 041h, 0D8h, 049h, 04Eh
         DB 0D2h, 044h, 043h, 0D2h, 04Dh, 056h, 0C9h, 04Ch, 058h, 0C9h
         DB 049h, 04Eh, 0D8h, 044h, 041h, 0C4h, 044h, 043h, 0D8h, 041h
         DB 044h, 0C4h, 041h, 044h, 0C3h, 053h, 055h, 0C2h, 053h, 042h
         DB 0C2h, 041h, 04Eh, 0C1h, 058h, 052h, 0C1h, 04Fh, 052h, 0C1h
         DB 043h, 04Dh, 0D0h, 04Ah, 04Dh, 0D0h, 043h, 041h, 04Ch, 0CCh
         DB 04Fh, 055h, 0D4h, 049h, 0CEh, 03Fh, 03Fh, 0BFh, 041h, 044h
         DB 0C9h, 053h, 055h, 0C9h, 041h, 04Eh, 0C9h, 04Fh, 052h, 0C9h
         DB 041h, 043h, 0C9h, 053h, 042h, 0C9h, 058h, 052h, 0C9h, 043h
         DB 050h, 0C9h, 0A0h, 0A0h, 058h, 054h, 048h, 0CCh, 044h, 0C9h
         DB 052h, 045h, 0D4h, 03Fh, 03Fh, 0BFh, 050h, 043h, 048h, 0CCh
         DB 053h, 050h, 048h, 0CCh, 03Fh, 03Fh, 0BFh, 0A0h, 058h, 043h
         DB 048h, 0C7h, 045h, 0C9h, 050h, 04Fh, 0D0h, 050h, 055h, 053h
         DB 0C8h, 052h, 053h, 0D4h, 0D2h, 0CAh, 0C3h, 0D2h, 0CAh, 0C3h
END