;*********************************************************************************************************
; 
; Autogenerated by DizAssembler:
;   https://github.com/codenjoyme/8080-emulator/blob/master/src/main/java/spec/assembler/DizAssembler.java
; From: src/main/resources/lik/apps/zoo/zoo.rks
; In test: DizAssemblerTest.testDizAssembly()
; 
;*********************************************************************************************************

         CPU  8080
         .ORG 00000h
lnisl    EQU 02377h
lnitx    EQU 02477h
lnitz    EQU 02577h
ljsiu    EQU 02AC9h
lnvzg    EQU 030FEh
lnjwe    EQU 030FFh
ljtwe    EQU 03AC9h
lnjsg    EQU 03FFFh
lomqm    EQU 040FEh
loodw    EQU 050FEh
louqc    EQU 077B6h
lcasc    EQU 08FF1h
lgfjy    EQU 08FFAh
lcjko    EQU 08FFCh
lbxhm    EQU 08FFDh
lcopl    EQU 09000h
lghef    EQU 0900Ah
ldlif    EQU 0C000h
lgozx    EQU 0C037h
ldlfj    EQU 0C170h
lcwaz    EQU 0C235h
ldkyf    EQU 0C248h
ldiev    EQU 0C254h
lhduj    EQU 0C25Ah
lgozr    EQU 0C337h
ldpgb    EQU 0FE1Ch
lddcz    EQU 0FE1Dh
ldstf    EQU 0FF00h
ldgqd    EQU 0FF01h
lhlrv    EQU 0FF02h
ldsqd    EQU 0FF30h
ldsqg    EQU 0FFF0h
ldsgk    EQU 0FFF8h
lgwbe    EQU 0FFFFh
         JMP ljzai

lnfuv:   DB 0C3h, 032h, 000h
lnoxd:   JMP ljjlt
         DB 0C3h
lnrob:   DB 06Ch, 000h
ljvor:   JMP ljmwe
lnckf:   JMP lnowm
lnrvl:   JMP ljvlo
ljjsz:   JMP ljypo
ljymz:   JMP lnrlf
         DB 0C3h, 08Ch, 001h
lnokv:   JMP ljmjy
ljmvp:   JMP lnctm
ljvxx:   JMP lnfhy
lnctl:   JMP lnrvq
lnrnl:   JMP ljypc
ljjkz:   JMP lnojw

ljywf:   DB 083h, 001h
lnruv:   PUSH H
         PUSH B
ljvvl:   LDAX B
         MOV M,A
         INR H
         INR B
         LDAX B
         MOV M,A
         INX H
         INX B
         LDAX B
         MOV M,A
         DCR H
         DCR B
         LDAX B
         MOV M,A
         INX H
         INX B
         MOV A,C
         ANI 00Fh
         JNZ ljvvl
         POP B
         POP H
         RET
ljjlt:   PUSH H
         PUSH B
lnckj:   LDAX B
         ORA M
         MOV M,A
         INR H
         INR B
         LDAX B
         ORA M
         MOV M,A
         INX H
         INX B
         LDAX B
         ORA M
         MOV M,A
         DCR H
         DCR B
         LDAX B
         ORA M
         MOV M,A
         INX H
         INX B
         MOV A,C
         ANI 00Fh
         JNZ lnckj
         POP B
         POP H
         RET
         DB 0EBh, 021h, 000h, 014h, 006h, 0C0h, 07Eh, 00Fh, 00Fh, 00Fh
         DB 00Fh, 023h, 0B6h, 012h, 023h, 013h, 005h, 0C2h, 072h, 000h
         DB 0C9h
ljmwe:   LXI D,lkanx
         LXI B,ldlif
lncua:   MOV A,M
         ADD A
         ADD A
         ADD A
         ADD A
         STAX D
         CPI 050h
         JNZ lnfsi
         INR C
lnfsi:   INX D
         MOV A,M
         ANI 0F0h
         STAX D
         CPI 050h
         JNZ lnoku
         INR C
lnoku:   INX D
         INX H
         DCR B
         JNZ lncua
         MOV A,C
         RET
lnowm:   LXI H,lcopl
         LXI D,lkanx
         LXI B,00180h
lncjo:   PUSH B
         CALL ljypo
         POP B
         INX D
         DCX B
         MOV A,B
         ORA C
         JNZ lncjo
         RET
ljvlo:   MOV H,D
         MOV L,E
         DAD H
         DAD H
         DAD H
         DAD H
         MOV A,H
         ADD A
         ADI 010h
         MOV H,A
         RET
ljypo:   LDAX D
         MOV C,A
         MVI B,00Ch
         CALL ljvlo
         JMP lnruv
lnrvo:   PUSH H
         CALL ljypo
         LXI B,ldsgk
         DAD B
         POP PSW
         LXI B,ljyuv
         ADD B
         MOV B,A
         CALL ljjlt
         XCHG
         LXI D,lgwbe
         DAD D
         RET
ljmlw:   PUSH H
         CALL ljypo
         POP PSW
         LXI B,ljyvh
         ADD B
         MOV B,A
         CALL ljjlt
         XCHG
         RET
ljymm:   PUSH H
         CALL ljypo
         LXI B,ldstf
         DAD B
         POP PSW
         LXI B,ljyur
         ADD B
         MOV B,A
         CALL ljjlt
         XCHG
         LXI D,ldsqg
         DAD D
         RET
lnckh:   PUSH H
         CALL ljypo
         LXI B,00100h
         DAD B
         POP PSW
         LXI B,ljyvl
         ADD B
         MOV B,A
         CALL ljjlt
         XCHG
         LXI D,00010h
         DAD D
         RET
lnowp:   PUSH H
         CALL ljypo
         LXI B,00008h
         DAD B
         POP PSW
         LXI B,ljyvg
         ADD B
         MOV B,A
         CALL ljjlt
         XCHG
         LXI D,00001h
         DAD D
         RET
ljjip:   PUSH H
         CALL ljypo
         POP PSW
         LXI B,ljyuu
         ADD B
         MOV B,A
         CALL ljjlt
         XCHG
         RET
ljvox:   PUSH H
         CALL ljypo
         LXI B,ldstf
         DAD B
         POP PSW
         LXI B,ljyuq
         ADD B
         MOV B,A
         CALL ljjlt
         XCHG
         LXI D,ldsqg
         DAD D
         RET
lnful:   PUSH H
         CALL ljypo
         LXI B,00100h
         DAD B
         POP PSW
         LXI B,ljyvk
         ADD B
         MOV B,A
         CALL ljjlt
         XCHG
         LXI D,00010h
         DAD D
         RET
lnrlf:   PUSH H
         CALL ljypo
         POP D
         CALL ljypo
         LXI B,lkamq
         MOV A,C
         ADI 010h
         MOV C,A
         JMP ljjlt
ljvos:   MOV A,L
         ANI 00Fh
         DAD H
         DAD H
         DAD H
         DAD H
         MOV L,A
         MOV A,H
         ANI 01Fh
         MOV H,A
         RET
ljmjy:   CALL ljvos
         XCHG
         CALL ljvos
         MOV A,H
         SUB D
         MOV B,A
         MOV A,L
         SUB E
         MOV C,A
         RET
lnctm:   PUSH D
         MOV D,M
         INX H
         MVI E,001h
ljvoc:   CMP M
         INX H
         JZ ljymk
         INR E
         DCR D
         JNZ ljvoc
         MVI E,000h
ljymk:   MOV A,E
         POP D
         RET
lnfhy:   LXI B,00000h
         ORA A
         RZ
         PUSH D
         DCR A
         RAR
         RAR
         CMA
ljjvq:   MOV D,A
         SBB A
         MOV C,A
         CMA
         MOV B,A
         MOV A,D
         ANA B
         MOV B,A
         MOV A,D
         ANA C
         MOV C,A
         POP D
         RET
lnrvq:   LDAX D
         CPI 040h
         MVI L,0FFh
         JZ lnrva
         JM ljywk
         INR E
         LDAX D
         DCR E
         CPI 040h
         JC ljywk
         MOV A,H
         SUI 004h
         JM lnowp
         MVI H,002h
         JMP lnowp
ljywk:   MVI L,000h
lnrva:   MOV A,H
         SUI 004h
         JM ljjis
         MVI H,002h
         JMP lnojx
ljjis:   MOV A,B
         ORA A
         JZ ljvnt
         PUSH H
         JP ljmjp
lnowv:   LXI H,ldsqg
         DAD D
         MOV A,M
         POP H
         CPI 030h
         JC ljvnt
         MOV A,L
         ORA A
         JP ljymm
         JMP ljvox
ljmjp:   LXI H,00010h
         DAD D
         MOV A,M
         POP H
         CPI 030h
         JC ljvnt
         MOV A,L
         ORA A
         JP lnckh
         JMP lnful
ljvnt:   MVI B,000h
         MOV A,C
         ORA A
         JM lnowz
         JNZ lncjl
lnott:   MOV A,L
         ORA A
         JP ljmlw
         JMP ljjip
lnojx:   MOV A,C
         ORA A
         JZ lnrkv
         JP lncjl
lnowz:   LDAX D
         CPI 030h
         JC lnrkv
         JNZ lnrll
         DCR E
         LDAX D
         INR E
         CPI 030h
         JC lnrkv
         JMP lnrvo
lnrll:   CPI 040h
         JNZ lnrkv
         MOV A,H
         ORA A
         JNZ lnrkv
         DCR E
         LDAX D
         INR E
         CPI 030h
         JNZ lnrkv
         JMP lnrvo
lncjl:   INR E
         LDAX D
         DCR E
         CPI 030h
         JC lnrkv
         JMP lnowp
lnrkv:   MVI C,000h
         MOV A,B
         ORA A
         JZ lnott
         PUSH H
         JM lnowv
         JMP ljmjp
ljypc:   CALL ljypo
         LXI B,lkami
         CALL ljjlt
         DCR H
         DCR H
         LXI B,lkals
         CALL ljjlt
         LXI B,lkajg
         LXI D,00010h
         DAD D
         LXI D,lnowe
         JMP lnruv

lnowe:   DB 0CDh, 0C8h, 000h, 001h, 090h, 012h, 0CDh, 04Dh, 000h, 021h
         DB 0F0h, 0FFh, 019h, 0EBh, 0CDh, 0C8h, 000h, 01Ch, 03Eh, 070h
         DB 012h, 0C3h, 0C8h, 000h
lnojw:   CALL ljypo
         LXI B,lkamm
         CALL ljjlt
         INR H
         INR H
         LXI B,lkalw
         CALL ljjlt
         LXI B,lkajk
         LXI D,00010h
         DAD D
         LXI D,ljvma
         JMP lnruv

ljvma:   DB 0CDh, 0C8h, 000h, 001h, 0D0h, 012h, 0CDh, 04Dh, 000h, 021h
         DB 010h, 000h, 0C3h, 0B2h, 002h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 051h, 08Ah, 014h, 04Bh
         DB 095h, 043h, 015h, 030h, 002h, 054h, 015h, 04Bh, 018h, 045h
         DB 015h, 031h, 048h, 056h, 015h, 04Bh, 004h, 023h, 015h, 032h
         DB 007h, 034h, 015h, 04Ch, 011h, 025h, 015h, 052h, 014h, 036h
         DB 015h, 04Ch, 059h, 023h, 015h, 045h, 059h, 08Ah, 014h, 04Dh
         DB 089h, 054h, 015h, 030h, 096h, 045h, 015h, 04Dh, 001h, 036h
         DB 015h, 020h, 001h, 08Bh, 014h, 04Eh, 003h, 08Ch, 014h, 020h
ljyzf:   DB 000h
ljmwd:   DB 000h
lnrxv:   DB 040h, 016h
ljvyl:   DB 000h
ljjvj:   DB 000h
lnoxb:   DB 019h
lnctz:   DB 019h
ljypj:   DB 003h
ljmmh:   DB 003h
lnrnz:   DB 00Ch
lnfkx:   DB 004h, 000h
ljjln:   DB 000h, 000h
lnckd:   DB 010h
ljywt:   DB 01Eh, 014h
lnrvj:   DB 01Eh, 014h
ljvvz:   DB 01Eh, 014h
lnoup:   DB 000h, 00Eh, 002h
ljmjv:   DB 000h
lnrln:   DB 000h
lnfil:   DB 010h, 014h
ljjjb:   DB 014h, 014h
lnchr:   DB 015h, 014h
ljmvn:   DB 080h, 010h
lnfud:   DB 000h
ljvxv:   DB 00Ah, 000h
lnowl:   DB 010h, 014h
ljyot:   DB 014h, 014h
lnrnj:   DB 015h, 014h
ljvnz:   DB 080h, 010h
lnomp:   DB 000h
lncjn:   DB 00Ah, 000h, 0C3h, 0B9h, 01Dh
ljvvj:   JMP lkajb
lncqx:   JMP lnpxa
lnrkx:   JMP lnpxb
ljjil:   JMP lnovi
ljyza:   JMP ljjks
lnfuo:   JMP ljyqa
lnoww:   JMP lnrmi
ljmmc:   JMP ljjwi
ljvok:   JMP lnrxe
lncjy:   JMP lncsy
lnrve:   JMP ljmnb
ljjss:   JMP ljjtt
ljyms:   JMP ljjna
         DB 0C3h, 004h, 006h
lnoko:   JMP ljmlj
         DB 0C3h, 040h, 006h, 0C3h, 05Fh, 006h
lncte:   JMP ljvqd
         DB 0C3h, 01Dh, 006h
ljjks:   LHLD lnrvj
         XCHG
         MOV L,A
         LDAX D
         CPI 030h
         JNC ljvli
         MVI A,0FFh
         ORA A
         RET
ljvli:   MOV A,L
         CPI 005h
         JNC lnokc
lnrxu:   STA ljmjv
         CALL ljvxx
         LDAX D
         CPI 050h
         CZ ljjue
         MVI H,000h
         CALL lnctl
         SHLD ljvvz
         MOV A,C
         STA lnoup
         LXI H,003E5h
         SHLD lnfuc
         XRA A
         RET
lnrxe:   JMP ljjus
ljjus:   LHLD ljywf
         SHLD lncjm
         LHLD lnoup
         SHLD lnfuw
         LHLD lnrvj
         XCHG
         LHLD ljvvz
         SHLD lnrvj
         JMP ljymz
lnokc:   MOV B,A
         LHLD ljyzf
         MOV A,L
         ADI 004h
         ANI 0BFh
         CMP H
         JZ lnoor
         MOV A,B
         SUI 005h
         JNZ lnflp
         LXI H,ldsqg
         DAD D
         MOV A,M
         CPI 060h
         JC lnoor
         INR L
         MOV A,M
         CPI 020h
         JNZ lnoor
         CALL ljvxl
         CALL lnrnl
         JMP lnrzh
lnflp:   LXI H,00010h
         DAD D
         MOV A,M
         CPI 060h
         JC lnoor
         INR L
         MOV A,M
         CPI 020h
         JNZ lnoor
         CALL ljvxl
         CALL ljjkz
lnrzh:   XCHG
         SHLD lnfuc
         LXI H,00000h
         SHLD ljmjv
         XRA A
         RET
lnoor:   LDA lnrln
         JMP lnrxu
ljvxl:   PUSH H
         PUSH D
         MVI M,070h
         XCHG
         LDA ljyzf
         MOV L,A
         MVI H,003h
         LDA lnfkx
         ADI 020h
         DAA
         MOV M,A
         INR L
         MOV M,E
         INR L
         MOV M,D
         INR L
         INR L
         MOV A,L
         ANI 0BFh
         STA ljyzf
         POP D
         POP H
         RET
ljjtt:   LHLD ljyzf
         MOV A,L
         CMP H
         RZ
         MOV L,H
         MVI H,003h
         LDA lnfkx
         CMP M
         RNZ
         INR L
         MOV E,M
         INR L
         MOV D,M
         INR L
         INR L
         MOV A,L
         ANI 0BFh
         STA ljmwd
         MVI A,020h
         STAX D
         JMP ljjsz
ljjue:   LDA lnckd
         DCR A
         STA lnckd
         MVI A,060h
         STAX D
         PUSH B
         LXI B,lnrob
         CALL ljjkb
         POP B
         RET
ljyqa:   LHLD lnrvj
         XCHG
         LHLD ljjjb
         PUSH H
         CALL lnokv
         MOV H,B
         MOV L,C
         SHLD ljvxv
         POP D
         MOV A,B
         ORA C
         RZ
         LDAX D
         CPI 030h
         JC ljyog
         CPI 050h
         CZ ljvnb
         MVI H,002h
         CALL lnctl
         SHLD lnchr
         MOV A,C
         STA ljmvn
         MVI A,0FFh
         ORA A
         RET
lncsy:   LHLD ljywf
         SHLD ljmwy
         LHLD ljmvn
         SHLD lnfuw
         LHLD ljjjb
         LDA lnfud
         ORA A
         CNZ ljyxr
         STA lnfud
         XCHG
         LHLD lnchr
         SHLD ljjjb
         JMP ljymz
lnrmi:   LHLD lnrvj
         XCHG
         LHLD ljyot
         PUSH H
         CALL lnokv
         MOV H,B
         MOV L,C
         SHLD lncjn
         POP D
         MOV A,B
         ORA C
         RZ
         LDAX D
         CPI 030h
         JC ljvze
         CPI 050h
         CZ lnrpi
         MVI H,004h
         CALL lnctl
         SHLD lnrnj
         MOV A,C
         STA ljvnz
         MVI A,0FFh
         ORA A
         RET
ljmnb:   LHLD ljywf
         SHLD lnftb
         LHLD ljvnz
         SHLD lnfuw
         LHLD ljyot
         LDA lnomp
         ORA A
         CNZ ljyxr
         STA lnomp
         XCHG
         LHLD lnrnj
         SHLD ljyot
         JMP ljymz
ljvqd:   CPI 007h
         RNC
         STA ljmjv
         CPI 005h
         RNC
         STA lnrln
         RET
ljmlj:   ANI 001h
         ADD A
         DCR A
         PUSH H
         PUSH D
         PUSH B
         LXI H,lnrnz
         ADD M
         ANI 03Fh
         MOV M,A
         ADD A
         ADD A
         STA ljyqi
         POP B
         POP D
         POP H
         RET
ljyxr:   DCR A
         RNZ
         MOV A,M
         CPI 060h
         MVI A,001h
         RNZ
         MVI M,050h
         XRA A
         RET
ljvnb:   LDA lnfud
         ORA A
         RNZ
         MVI A,020h
         STA lnfud
         MVI A,060h
         STAX D
         RET
lnrpi:   LDA lnomp
         ORA A
         RNZ
         MVI A,020h
         STA lnomp
         MVI A,060h
         STAX D
         RET
ljyog:   LHLD lnfil
         SHLD lnchr
         SHLD ljjjb
         JMP ljjmg
ljvze:   LHLD lnowl
         SHLD lnrnj
         SHLD ljyot
ljjmg:   PUSH B
         LXI B,lnfuv
         CALL ljjkb
         POP B
         RET
lnovi:   LXI B,ljyvh
         LXI D,lndyv
         DCR A
         RZ
         PUSH PSW
         CALL lnrvl
         POP D
lnfwg:   CALL lnoxd
         INR H
         INR H
         DCR D
         JNZ lnfwg
         RET
ljjna:   LXI H,ljmer
         CALL ljvzl
         LXI H,ljmuq
         CALL lnrkx
         LHLD ljjln
         CALL ljvvj
         LXI H,lncsm
         CALL lnrkx
         LDA ljjvj
         CALL ljzaj
         LXI H,lnrye
         CALL lnrkx
         LDA lnctz
         CALL ljzaj
         LXI H,ljyxc
         CALL lnrkx
         LDA lnrnz
         CALL ljzaj
         RET
ljvzl:   MOV A,L
         DCR A
         RM
         INR A
         CPI 01Ah
         RNC
         ADD A
         ADD A
         ADD L
         ADD A
         ADI 003h
         MOV L,A
         MOV A,H
         ANI 03Fh
         MOV H,A
         ADD A
         ADD H
         MOV H,A
         SHLD lcjko
         RET
ljjkb:   PUSH H
         PUSH D
         LHLD ljjln
         MOV A,C
         ADD L
         DAA
         MOV L,A
         MOV A,B
         ADC H
         DAA
         MOV H,A
         SHLD ljjln
         XCHG
         LXI H,ljmfz
         CALL ljvzl
         XCHG
         CALL ljvvj
         POP D
         POP H
         RET
         DB 00Eh, 01Fh, 0C3h, 071h, 003h
ljzaj:   MOV L,A
         MVI H,000h
         CALL lnciv
         MOV A,E
         CALL lncqx
         RET
lnfmb:   CALL ljvxd
         CALL ljvxd
         CALL ljvxd
ljvxd:   MOV B,D
         MOV C,E
lnovt:   MOV A,E
         ADD C
         DAA
         MOV E,A
         MOV A,D
         ADC B
         DAA
         MOV D,A
         RET
lnciv:   LXI D,00000h
         MOV A,H
         CALL lncun
         MOV A,L
lncun:   CALL lnron
lnron:   PUSH PSW
         CALL lnfmb
         POP PSW
         RRC
         RRC
         RRC
         RRC
         PUSH PSW
         ANI 00Fh
         CPI 00Ah
         JC ljjjp
         ADI 006h
ljjjp:   MOV C,A
         MVI B,000h
         CALL lnovt
         POP PSW
         RET
ljjwi:   PUSH D
         LXI D,lnjwe
ljmng:   DCX D
         MOV A,D
         ORA E
         JNZ ljmng
         POP D
         RET

ljmuq:   DB 073h, 07Eh, 065h, 074h, 03Ah, 000h
lncsm:   DB 020h, 020h, 020h, 020h, 020h, 07Ch, 074h, 061h, 076h, 03Ah
         DB 000h
lnrye:   DB 020h, 020h, 020h, 020h, 020h, 070h, 06Fh, 070h, 079h, 074h
         DB 06Bh, 069h, 03Ah, 000h
ljyxc:   DB 020h, 020h, 020h, 020h, 020h, 075h, 072h, 06Fh, 077h, 065h
         DB 06Eh, 078h, 03Ah, 000h, 000h, 000h
ljzai:   LXI SP,lnjsg
         JMP ljvtv
lnoye:   JMP lgozr
ljmnk:   JMP ldlfj
ljvps:   JMP ljkvn
         DB 0C3h, 000h, 0C8h
lnrwm:   DB 009h, 008h, 018h, 060h, 080h, 071h, 073h, 02Dh, 03Bh, 06Bh
         DB 000h, 000h, 000h, 000h
ljyzs:   LXI H,00000h
         SHLD lnfkx
         SHLD ljjln
         LDA ljvyl
         STA ljjvj
         LDA lnoxb
         STA lnctz
         RET
lnovc:   LDA ljypj
         STA ljmmh
         LXI H,ldsqd
         SHLD lcasc
         CALL ljmnk
         LXI H,00000h
         SHLD ljyzf
         XRA A
         STA lnfud
         STA lnomp
         RET
lnftj:   LXI H,lkany
         NOP
         LHLD lnrxv
         LDA ljjvj
         LXI D,000C0h
ljyzr:   DCR A
         JM ljypv
         DAD D
         JMP ljyzr
ljypv:   RET
ljmmt:   CALL lnckf
         LDA ljmmh
         CALL ljjil
         LHLD ljywt
         SHLD lnrvj
         LHLD lnfil
         SHLD ljjjb
         LHLD lnowl
         SHLD ljyot
         RET
ljjwp:   CALL ljjmo
         LDA ljmjv
         CALL ljyza
         JNZ ljmni
         CALL lnfuo
         JZ ljmni
         CALL lnoww
         JZ ljmni
         CALL ljjmo
         LHLD lnrvj
         XCHG
         CALL ljvok
         CALL lncjy
         CALL lnrve
         CALL ljjss
         LHLD lnfkx
         MOV A,L
         ADI 001h
         DAA
         MOV L,A
         MOV A,H
         ACI 000h
         DAA
         MOV H,A
         SHLD lnfkx
         LDA lnckd
         ORA A
         JNZ ljjwp
         XRA A
         RET
ljmni:   MVI A,0FFh
         ORA A
         RET
ljjmo:   CALL ljmmc
         CALL ljvps
         CPI 0FFh
         RZ
lnovq:   LXI H,lnrwm
         CALL ljmvp
         CPI 009h
         JZ ljzai
         CPI 007h
         JC lncte
         SUI 007h
         CALL lnoko
         CALL ljyms
         CALL lnoye
         CPI 03Dh
         JNZ ljyni
         MVI A,02Dh
ljyni:   CPI 02Bh
         JNZ lncic
         MVI A,03Bh
lncic:   JMP lnovq
lnrza:   LXI H,lkant
         SHLD lnrxv
         LXI H,00398h
         SHLD lnroo
         LXI H,0078Dh
         SHLD lnoyh
         SHLD lnolz
lncss:   CALL ljyzs
lnrms:   CALL lnovc
         CALL lnftj
         CALL ljvor
         STA lnckd
lnoxq:   CALL ljmmt
         CALL ljyms
         LXI H,00000h
         SHLD ljmjv
         CALL ljjwp
         ORA A
         JZ ljykn
         LXI H,ljmmh
         DCR M
         JNZ lnoxq
         LXI H,lnctz
         DCR M
         JNZ lnrms
         RET
ljykn:   LXI H,ljjvj
         MOV A,M
         INR A
         ANI 01Fh
         MOV M,A
         JMP lnrms
lnfnl:   LXI H,lkany
         SHLD lnrxv
         LXI H,lncpc
         SHLD lnroo
         LXI H,ljvqn
         SHLD lnoyh
         LXI H,ljvtd
         SHLD lnolz
         CALL ljyif
         JMP lncss

ljmof:   DB 052h
lnrpx:   DB 026h, 00Bh
ljvqn:   DB 0CDh, 089h, 003h, 03Ah, 031h, 008h, 047h, 0E6h, 0F0h, 0C2h
         DB 04Dh, 008h, 02Ah, 032h, 008h, 02Ch, 022h, 032h, 008h, 046h
         DB 078h, 0B7h, 0CCh, 058h, 008h, 078h, 0D6h, 010h, 032h, 031h
         DB 008h, 0E6h, 00Fh, 0C3h, 0A7h, 003h
ljyif:   LXI H,ljjpr
         SHLD lnrpx
         MOV B,M
         MOV A,B
         STA ljmof
         RET

ljvtd:   DB 0CDh, 089h, 003h, 0CDh, 0CCh, 006h, 0FEh, 0FFh, 0C8h, 0FEh
         DB 065h, 0CAh, 07Fh, 008h, 0FEh, 068h, 0CAh, 0A0h, 008h, 0FEh
         DB 020h, 0C0h, 033h, 033h, 033h, 033h, 0C9h, 00Eh, 01Fh, 0CDh
         DB 071h, 003h, 0C3h, 0CFh, 006h
lncpc:   DB 021h, 019h, 00Ah, 0CDh, 09Bh, 003h, 021h, 050h, 009h, 0CDh
         DB 07Ah, 003h, 02Ah, 04Dh, 003h, 0CDh, 074h, 003h, 021h, 056h
         DB 009h, 0CDh, 07Ah, 003h, 0C9h, 00Eh, 01Fh, 0CDh, 071h, 003h
         DB 021h, 003h, 015h, 0CDh, 09Bh, 003h, 021h, 082h, 009h, 0CDh
         DB 07Ah, 003h, 021h, 004h, 014h, 0CDh, 09Bh, 003h, 021h, 090h
         DB 009h, 0CDh, 07Ah, 003h, 021h, 007h, 023h, 0CDh, 09Bh, 003h
         DB 021h, 051h, 00Ah, 0CDh, 07Ah, 003h, 021h, 008h, 028h, 0CDh
         DB 09Bh, 003h, 021h, 064h, 00Ah, 0CDh, 07Ah, 003h, 021h, 009h
         DB 023h, 0CDh, 09Bh, 003h, 021h, 06Ah, 00Ah, 0CDh, 07Ah, 003h
         DB 021h, 00Bh, 025h, 0CDh, 09Bh, 003h, 021h, 07Dh, 00Ah, 0CDh
         DB 07Ah, 003h, 021h, 00Ch, 026h, 0CDh, 09Bh, 003h, 021h, 08Ch
         DB 00Ah, 0CDh, 07Ah, 003h, 021h, 010h, 025h, 0CDh, 09Bh, 003h
         DB 021h, 098h, 00Ah, 0CDh, 07Ah, 003h, 021h, 011h, 025h, 0CDh
         DB 09Bh, 003h, 021h, 0A9h, 00Ah, 0CDh, 07Ah, 003h, 021h, 013h
         DB 023h, 0CDh, 09Bh, 003h, 021h, 0BAh, 00Ah, 0CDh, 07Ah, 003h
         DB 021h, 014h, 026h, 0CDh, 09Bh, 003h, 021h, 0CFh, 00Ah, 0CDh
         DB 07Ah, 003h, 001h, 000h, 012h, 021h, 0F0h, 090h, 0CDh, 003h
         DB 000h, 021h, 019h, 003h, 0CDh, 09Bh, 003h, 021h, 0DEh, 00Ah
         DB 0CDh, 07Ah, 003h, 0CDh, 0C6h, 006h, 0C3h, 0C0h, 006h
ljvtv:   CALL lnfnl
         CALL lnrza
         JMP ljzai
         DB 000h, 000h, 000h, 06Fh, 07Eh, 06Bh, 069h, 03Ah, 000h, 020h
         DB 020h, 03Ch, 045h, 03Eh, 020h, 02Dh, 020h, 077h, 079h, 068h
         DB 06Fh, 064h, 02Ch, 020h, 03Ch, 048h, 03Eh, 020h, 02Dh, 020h
         DB 06Bh, 06Ch, 061h, 077h, 069h, 07Bh, 069h, 02Ch, 020h, 070h
         DB 072h, 06Fh, 062h, 065h, 06Ch, 020h, 02Dh, 020h, 069h, 067h
         DB 072h, 061h, 000h, 07Ah, 020h, 06Fh, 020h, 06Fh, 020h, 070h
         DB 020h, 061h, 020h, 072h, 020h, 06Bh, 000h, 02Dh, 02Dh, 02Dh
         DB 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh
         DB 02Dh, 02Dh, 00Dh, 00Ah, 01Ah, 01Ah, 020h, 020h, 020h, 06Bh
         DB 06Ch, 061h, 077h, 069h, 07Bh, 069h, 020h, 075h, 070h, 072h
         DB 061h, 077h, 06Ch, 065h, 06Eh, 069h, 071h, 00Dh, 00Ah, 020h
         DB 020h, 020h, 020h, 020h, 020h, 020h, 064h, 077h, 069h, 076h
         DB 065h, 06Eh, 069h, 065h, 06Dh, 00Dh, 00Ah, 020h, 020h, 020h
         DB 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh
         DB 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 00Dh, 00Ah
         DB 01Ah, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 077h
         DB 077h, 065h, 072h, 068h, 00Dh, 00Ah, 020h, 020h, 020h, 020h
         DB 020h, 020h, 020h, 020h, 020h, 03Ch, 040h, 03Eh, 00Dh, 00Ah
         DB 01Ah, 020h, 077h, 06Ch, 065h, 077h, 06Fh, 020h, 020h, 077h
         DB 06Eh, 069h, 07Ah, 020h, 020h, 020h, 020h, 077h, 070h, 072h
         DB 061h, 077h, 06Fh, 00Dh
ljmer:   DB 00Ah, 020h, 020h, 03Ch, 02Dh, 02Dh, 020h, 020h, 020h, 03Ch
         DB 072h, 070h, 074h, 03Eh, 020h, 020h, 020h, 020h, 02Dh, 02Dh
         DB 03Eh, 00Dh, 00Ah, 01Ah, 01Ah, 01Ah, 020h, 020h, 020h, 020h
         DB 020h, 06Bh, 06Fh, 06Eh, 065h, 063h, 020h, 069h, 067h, 072h
         DB 079h, 00Dh, 00Ah, 020h, 020h, 020h, 020h, 020h, 020h, 020h
         DB 020h, 020h, 03Ch, 06Bh, 03Eh, 000h, 06Bh, 06Ch, 061h, 077h
         DB 069h, 07Bh, 069h, 020h, 075h, 070h, 072h, 061h, 077h, 06Ch
         DB 065h, 06Eh, 069h, 071h, 000h, 06Fh, 067h, 06Eh, 065h, 06Dh
         DB 000h, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh
         DB 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 000h
         DB 077h, 06Ch, 065h, 077h, 06Fh, 020h, 020h, 020h, 077h, 070h
         DB 072h, 061h, 077h, 06Fh, 000h, 03Ch, 051h, 03Eh, 020h, 020h
         DB 020h, 020h, 020h, 03Ch, 053h, 03Eh, 000h, 069h, 07Ah, 06Dh
         DB 065h, 06Eh, 065h, 06Eh, 069h, 065h, 020h, 075h, 072h, 06Fh
         DB 077h, 06Eh, 071h, 000h, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh
         DB 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh
         DB 000h, 075h, 06Dh, 065h, 06Eh, 078h, 07Bh, 069h, 074h, 078h
         DB 020h, 020h, 075h, 077h, 065h, 06Ch, 069h, 07Eh, 069h, 074h
         DB 078h, 000h, 03Ch, 02Dh, 03Eh, 020h, 020h, 020h, 020h, 020h
         DB 020h, 020h, 020h, 03Ch, 02Bh, 03Eh, 000h, 066h, 069h, 06Ch
         DB 069h, 070h, 070h, 06Fh, 077h, 028h, 070h, 072h, 06Fh, 067h
         DB 072h, 061h, 06Dh, 06Dh, 061h, 029h, 02Ch, 070h, 065h, 072h
         DB 065h, 077h, 065h, 072h, 07Ah, 065h, 077h, 028h, 06Dh, 075h
         DB 06Ch, 078h, 074h, 069h, 070h, 06Ch, 069h, 06Bh, 061h, 063h
         DB 069h, 071h, 029h, 02Ch, 031h, 039h, 038h, 038h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
ljjpr:   DB 013h, 0A2h, 015h, 012h, 050h, 012h, 015h, 092h, 0D3h, 041h
         DB 015h, 071h, 016h, 032h, 064h, 015h, 012h, 015h, 042h, 063h
         DB 031h, 073h, 021h, 015h, 0F0h, 030h, 031h, 013h, 090h, 0F2h
         DB 052h, 020h, 015h, 012h, 0D3h, 091h, 015h, 061h, 015h, 051h
         DB 083h, 010h, 000h, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh
         DB 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 020h
         DB 020h, 020h, 069h, 06Eh, 066h, 06Fh, 072h, 06Dh, 061h, 063h
         DB 069h, 071h, 020h, 020h, 020h, 020h, 020h, 020h, 06Fh, 062h
         DB 020h, 061h, 077h, 074h, 06Fh, 072h, 061h, 068h, 020h, 020h
         DB 020h, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh
         DB 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 020h, 066h, 069h
         DB 06Ch, 069h, 070h, 070h, 06Fh, 077h, 020h, 065h, 02Eh, 077h
         DB 02Eh, 020h, 020h, 020h, 020h, 028h, 070h, 072h, 06Fh, 067h
         DB 072h, 061h, 06Dh, 06Dh, 061h, 029h, 020h, 020h, 020h, 020h
         DB 070h, 065h, 072h, 065h, 077h, 065h, 072h, 07Ah, 065h, 077h
         DB 020h, 073h, 02Eh, 074h, 02Eh, 028h, 07Ah, 06Eh, 061h, 06Bh
         DB 06Fh, 067h, 065h, 06Eh, 065h, 072h, 061h, 074h, 06Fh, 072h
         DB 029h, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh
         DB 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 02Dh, 074h, 02Eh, 032h
         DB 031h, 02Dh, 034h, 030h, 02Dh, 030h, 038h, 020h, 020h, 06Bh
         DB 06Fh, 064h, 020h, 067h, 02Eh, 06Bh, 069h, 07Bh, 069h, 06Eh
         DB 065h, 077h, 020h, 020h, 028h, 030h, 034h, 032h, 029h, 0FFh
         DB 0FFh, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 0EFh, 0EFh, 0EFh, 000h, 0FEh
         DB 0FEh, 0FEh, 000h, 0EFh, 0EFh, 0EFh, 000h, 0FEh, 0FEh, 0FEh
         DB 000h, 039h, 06Ch, 0C7h, 092h, 0C7h, 06Ch, 03Bh, 055h, 0ABh
         DB 03Ah, 06Dh, 0C6h, 093h, 0C6h, 06Dh, 038h, 0BFh, 040h, 040h
         DB 040h, 040h, 040h, 040h, 040h, 0BFh, 040h, 040h, 040h, 040h
         DB 040h, 040h, 040h, 000h, 0FFh, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 002h, 007h, 000h, 00Fh, 03Fh
         DB 02Eh, 03Dh, 01Fh, 00Fh, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 020h, 040h, 080h, 090h, 040h, 020h, 000h, 050h, 080h
         DB 020h, 040h, 080h, 090h, 080h, 040h, 030h, 000h, 003h, 00Eh
         DB 010h, 038h, 024h, 062h, 041h, 041h, 062h, 024h, 038h, 018h
         DB 00Eh, 003h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 0FFh, 0FFh, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 0EFh, 0EFh, 0EFh, 000h, 0FEh, 0FEh, 0FEh, 000h, 0EFh
         DB 0EFh, 0EFh, 000h, 0FEh, 0FEh, 0FEh, 000h, 01Ch, 0B6h, 0E3h
         DB 0C9h, 0E3h, 0B6h, 05Ch, 0D5h, 0AAh, 0DCh, 036h, 0E3h, 0D9h
         DB 0E3h, 036h, 09Ch, 0FDh, 002h, 002h, 002h, 002h, 002h, 002h
         DB 002h, 0FDh, 002h, 002h, 002h, 002h, 002h, 002h, 002h, 000h
         DB 0FFh, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 080h, 0DCh, 0F8h, 070h, 0E0h, 0C0h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 00Ch, 002h, 001h
         DB 009h, 001h, 002h, 004h, 001h, 00Ah, 000h, 002h, 001h, 005h
         DB 001h, 00Ah, 004h, 000h, 0C0h, 070h, 018h, 01Ch, 024h, 046h
         DB 082h, 082h, 046h, 024h, 01Ch, 018h, 070h, 0C0h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h
ljyvh:   DB 000h, 000h, 003h, 002h, 007h, 002h, 003h, 00Fh, 01Fh, 03Fh
         DB 037h, 027h, 00Fh, 00Fh, 00Eh, 01Ch, 000h, 000h, 003h, 007h
         DB 007h, 006h, 00Fh, 01Fh, 03Fh, 033h, 027h, 00Fh, 00Fh, 00Fh
         DB 006h, 00Eh
ljyur:   DB 000h, 000h, 001h, 001h, 003h, 001h, 001h, 000h, 00Bh, 01Fh
         DB 00Fh, 001h, 003h, 007h, 003h, 001h, 000h, 003h, 002h, 007h
         DB 002h, 003h, 037h, 01Fh, 00Fh, 003h, 003h, 007h, 007h, 007h
         DB 006h, 00Ch
ljyvl:   DB 000h, 000h, 007h, 00Eh, 00Fh, 00Ch, 00Fh, 01Fh, 03Fh, 037h
         DB 03Fh, 01Fh, 00Fh, 007h, 00Eh, 01Dh, 000h, 003h, 007h, 007h
         DB 006h, 007h, 01Fh, 03Fh, 07Fh, 067h, 047h, 00Fh, 01Fh, 03Eh
         DB 030h, 000h
ljyuv:   DB 000h, 000h, 003h, 017h, 037h, 033h, 03Bh, 01Fh, 00Fh, 007h
         DB 007h, 007h, 00Fh, 00Eh, 00Eh, 01Ch, 000h, 000h, 003h, 007h
         DB 007h, 003h, 00Fh, 01Fh, 03Bh, 033h, 027h, 007h, 007h, 003h
         DB 007h, 000h
ljyvg:   DB 000h, 003h, 006h, 007h, 063h, 037h, 03Fh, 01Fh, 007h, 007h
         DB 003h, 007h, 007h, 007h, 007h, 00Eh, 000h, 003h, 006h, 007h
         DB 003h, 007h, 00Fh, 00Fh, 01Dh, 01Bh, 017h, 007h, 003h, 007h
         DB 000h, 000h
ljyuq:   DB 01Ch, 000h, 01Ch, 018h, 019h, 01Ch, 00Eh, 00Fh, 007h, 007h
         DB 007h, 003h, 003h, 001h, 000h, 000h, 000h, 000h, 000h, 001h
         DB 003h, 021h, 031h, 03Bh, 01Fh, 00Fh, 001h, 00Bh, 00Fh, 00Fh
         DB 000h, 000h
ljyvk:   DB 000h, 000h, 000h, 00Fh, 01Dh, 01Fh, 019h, 03Fh, 07Fh, 0FFh
         DB 0FFh, 09Fh, 03Fh, 073h, 067h, 006h, 070h, 000h, 070h, 067h
         DB 06Eh, 06Fh, 07Ch, 03Fh, 01Fh, 01Fh, 01Fh, 01Fh, 01Dh, 018h
         DB 01Ch, 000h
ljyuu:   DB 038h, 000h, 038h, 033h, 036h, 037h, 03Bh, 01Fh, 00Fh, 007h
         DB 007h, 003h, 003h, 007h, 00Eh, 000h, 070h, 000h, 070h, 033h
         DB 036h, 037h, 03Bh, 01Fh, 00Fh, 007h, 007h, 007h, 007h, 003h
         DB 001h, 000h, 000h, 000h, 0C0h, 0E0h, 0E0h, 060h, 0F0h, 0F8h
         DB 0FCh, 0FEh, 0E6h, 0F0h, 0F0h, 070h, 038h, 000h, 000h, 000h
         DB 0C0h, 040h, 0E0h, 040h, 0C0h, 0F0h, 0F8h
ljmfz:   DB 0FCh, 0ECh, 0E0h, 0E0h, 070h, 038h, 01Ch, 000h, 000h, 0E0h
         DB 070h, 0F0h, 030h, 0F8h, 0FCh, 0FEh, 0F6h, 0FCh, 0F8h, 0F0h
         DB 0E0h, 070h, 0B0h, 000h, 0C0h, 0E0h, 0E0h, 060h, 0F8h, 0FCh
         DB 0FEh, 0F7h, 0F3h, 0F0h, 0F0h, 0FCh, 01Ch, 004h, 000h, 000h
         DB 000h, 080h, 080h, 0C0h, 080h, 080h, 0D8h, 0F0h, 0E0h, 080h
         DB 0C0h, 0E0h, 0E0h, 0C0h, 0C0h, 000h, 0C0h, 040h, 0E0h, 040h
         DB 0C0h, 0E6h, 0FCh, 0F8h, 0E0h, 0C0h, 0E0h, 0F0h, 070h, 030h
         DB 038h, 000h, 000h, 0C0h, 0E0h, 0E0h, 0C0h, 0F0h, 0F8h, 0FCh
         DB 0ECh, 0E4h, 0E0h, 070h, 078h, 000h, 000h, 000h, 000h, 0C0h
         DB 0E4h, 0EEh, 0DCh, 0F8h, 0F0h, 0E0h, 0E0h, 0F0h, 0F0h, 0F8h
         DB 0B8h, 018h, 01Ch, 000h, 0E0h, 0B0h, 0F0h, 060h, 0F0h, 0F8h
         DB 0FCh, 0FEh, 0F6h, 0E0h, 0F0h, 078h, 01Ch, 000h, 000h, 000h
         DB 0E0h, 0B0h, 0F2h, 066h, 0F6h, 0FEh, 0FCh, 0F8h, 0F0h, 0F0h
         DB 0B8h, 078h, 0B8h, 030h, 038h, 000h, 000h, 000h, 0F0h, 0B8h
         DB 0F8h, 098h, 0FCh, 0FEh, 0FEh, 0F6h, 0F0h, 0BEh, 0DEh, 0E2h
         DB 020h, 00Eh, 000h, 00Eh, 0ECh, 07Ch, 0FCh, 03Ch, 0FCh, 0F8h
         DB 0F0h, 0F8h, 0FCh, 0DCh, 00Ch, 01Ch, 000h, 038h, 000h, 038h
         DB 018h, 098h, 038h, 078h, 0F0h, 0E0h, 0E0h, 0C0h, 0C0h, 080h
         DB 080h, 000h, 000h, 000h, 000h, 000h, 080h, 0C0h, 084h, 08Ch
         DB 0DCh, 0F8h, 0E0h, 080h, 0C0h, 0E0h, 070h, 000h, 000h, 007h
         DB 000h, 007h, 0E6h, 0B6h, 0F6h, 06Eh, 0FCh, 0F8h, 0F8h, 0F8h
         DB 0FCh, 09Ch, 038h, 000h, 000h, 00Eh, 000h, 00Eh, 0E6h, 0B6h
         DB 0F6h, 066h, 0FEh, 0FCh, 0F8h, 0F0h, 0F0h, 0F0h, 0B8h, 0DCh
         DB 000h, 000h, 001h, 00Fh, 002h, 007h, 003h, 001h, 007h, 00Fh
         DB 01Bh, 000h, 003h, 007h, 006h, 006h, 00Ch, 000h, 003h, 003h
         DB 003h, 003h, 003h, 001h, 00Fh, 01Fh, 013h, 000h, 003h, 007h
         DB 006h, 006h, 00Ch, 000h, 001h, 007h, 001h, 003h, 001h, 000h
         DB 001h, 00Bh, 007h, 000h, 001h, 003h, 003h, 001h, 000h, 003h
         DB 00Fh, 002h, 007h, 003h, 001h, 037h, 01Fh, 003h, 002h, 000h
         DB 003h, 007h, 006h, 004h, 00Ch, 000h, 003h, 007h, 006h, 007h
         DB 003h, 007h, 00Bh, 01Dh, 00Eh, 000h, 00Fh, 007h, 003h, 007h
         DB 005h, 001h, 003h, 003h, 003h, 003h, 001h, 01Bh, 03Dh, 066h
         DB 047h, 000h, 007h, 00Eh, 038h, 020h, 000h, 000h, 001h, 003h
         DB 013h, 011h, 019h, 01Bh, 00Dh, 006h, 003h, 000h, 003h, 007h
         DB 006h, 006h, 00Ch, 000h, 000h, 001h, 003h, 001h, 003h, 00Dh
         DB 01Eh, 01Bh, 011h, 010h, 003h, 003h, 003h, 006h, 000h
lkamq:   DB 003h, 00Fh, 002h, 007h, 003h, 011h, 01Bh, 00Fh, 007h, 002h
         DB 000h, 001h, 003h, 003h, 003h, 006h, 000h, 001h, 001h, 001h
         DB 001h, 000h, 003h, 007h, 00Dh, 009h, 000h, 003h, 003h, 006h
         DB 000h, 000h, 00Ch, 000h, 00Dh, 008h, 009h, 00Ch, 00Eh, 007h
         DB 003h, 003h, 000h, 003h, 001h, 001h, 000h, 000h, 000h, 000h
         DB 007h, 001h, 003h, 001h, 020h, 033h, 01Fh, 006h, 000h, 001h
         DB 00Bh, 00Eh, 000h, 000h, 000h, 000h, 00Fh, 00Eh, 00Dh, 00Fh
         DB 006h, 01Bh, 03Dh, 02Eh, 020h, 007h, 007h, 03Dh, 027h, 004h
         DB 018h, 000h, 01Bh, 00Bh, 00Eh, 00Fh, 00Bh, 00Dh, 00Eh, 007h
         DB 000h, 00Fh, 019h, 018h, 00Ch, 000h, 018h, 000h, 019h, 013h
         DB 012h, 01Bh, 019h, 00Fh, 00Fh, 003h, 000h, 001h, 001h, 003h
         DB 006h, 000h, 030h, 000h, 031h, 013h, 012h, 01Bh, 019h, 00Fh
         DB 00Fh, 002h, 000h, 003h, 006h, 003h, 000h, 000h, 000h, 0C0h
         DB 0C0h, 0C0h, 0C0h, 0C0h, 0E0h, 0D8h, 0BCh, 064h, 000h, 0E0h
         DB 070h, 030h, 018h, 000h, 000h, 0C0h, 0F0h, 040h, 0E0h, 0C0h
         DB 080h, 0D0h, 0B8h, 06Ch, 000h, 0E0h, 060h, 030h, 018h, 01Ch
         DB 000h, 0C0h, 0E0h, 060h, 0E0h, 0C0h, 0E0h, 0D0h, 0B8h, 070h
         DB 000h, 0F0h, 0E0h, 0C0h, 0E0h, 0A0h, 080h, 0C0h, 0C0h, 0C0h
         DB 0C0h, 080h, 0D8h, 0BCh, 066h, 0E2h, 000h, 0E0h, 070h, 01Ch
         DB 004h, 000h, 000h, 080h, 0E0h, 080h, 0C0h, 080h, 000h, 080h
         DB 0D0h, 0E0h, 000h, 080h, 0C0h, 0C0h, 080h, 000h, 0C0h, 0F0h
         DB 040h, 0E0h, 0C0h, 080h, 0ECh, 0F8h, 0C0h, 040h, 000h, 0C0h
         DB 0E0h, 060h, 020h, 030h, 000h, 080h, 0C0h, 0C0h, 080h, 0E0h
         DB 0F0h, 0D8h, 0CCh, 044h, 000h, 0E0h, 070h, 018h, 000h, 000h
         DB 000h, 0C0h, 0E4h, 0ECh, 0CCh, 0D8h, 0F0h, 0F0h, 060h, 0A0h
         DB 000h, 0E0h, 0F0h, 030h, 010h, 018h, 080h, 0C0h, 0C0h, 0C0h
         DB 0C0h, 080h, 0E0h, 0B0h, 078h, 0C8h, 000h, 0E0h, 030h, 018h
         DB 000h, 000h, 0E0h, 0F8h, 0A0h, 0F0h, 0E0h, 0C4h, 0F4h, 0D8h
         DB 0B0h, 060h, 000h, 0E0h, 0B0h, 030h, 020h, 030h, 000h, 000h
         DB 0F0h, 0B0h, 0F0h, 0F0h, 060h, 0D8h, 0BCh, 074h, 004h, 0E0h
         DB 0E0h, 0BCh, 0E4h, 020h, 018h, 000h, 0D8h, 0D0h, 070h, 0F0h
         DB 0D0h, 0B0h, 070h, 0E0h, 000h, 0F0h, 098h, 018h, 030h, 000h
         DB 030h, 000h, 0B0h, 010h, 090h, 030h, 070h, 0E0h, 0C0h, 0C0h
         DB 000h, 0C0h, 080h, 080h, 000h, 000h, 000h, 000h, 0C0h, 080h
         DB 0C0h, 080h, 004h, 0CCh, 0F8h, 060h, 000h, 080h, 0D0h, 070h
         DB 000h, 000h, 006h, 000h, 0C6h, 0E4h, 0A4h, 0ECh, 04Ch, 0F8h
         DB 0B8h, 060h, 000h, 0F0h, 098h, 030h, 000h, 000h, 00Ch, 000h
         DB 0CCh, 0E4h, 0A4h, 0ECh, 0CCh, 0B8h, 078h, 0E0h, 000h, 0E0h
         DB 060h, 030h, 018h, 000h, 000h, 000h, 003h, 004h, 008h, 011h
         DB 012h, 012h, 012h, 012h, 011h, 008h, 004h, 003h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h
lkami:   DB 000h, 003h, 002h, 007h, 002h, 003h, 017h, 01Fh, 00Fh, 023h
         DB 043h, 087h, 007h, 007h, 006h, 00Ch, 000h, 000h, 003h, 003h
         DB 007h, 002h, 003h, 02Fh, 03Fh, 01Fh, 007h, 007h, 007h, 007h
         DB 00Eh, 000h
lkals:   DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 008h
         DB 005h, 024h, 044h, 048h, 028h, 019h
lkajg:   DB 02Bh, 012h, 014h, 098h, 04Dh, 022h, 038h, 054h, 0ABh, 03Ah
         DB 06Dh, 0C6h, 093h, 0C6h, 06Dh, 038h
lkamm:   DB 000h, 003h, 007h, 007h, 006h, 007h, 01Fh, 03Fh, 077h, 047h
         DB 007h, 007h, 00Fh, 00Eh, 00Ch, 018h, 000h, 000h, 003h, 007h
         DB 007h, 006h, 00Fh, 01Fh, 03Fh, 033h, 027h, 00Fh, 00Fh, 00Fh
         DB 006h, 00Eh
lkalw:   DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 001h, 001h
         DB 009h, 008h, 086h, 044h, 024h, 012h
lkajk:   DB 008h, 064h, 0C2h, 091h, 0C0h, 068h, 03Ah, 055h, 0ABh, 03Ah
         DB 06Dh, 0C6h, 093h, 0C6h, 06Dh, 038h, 000h, 000h, 0E0h, 010h
         DB 008h, 0C4h, 024h, 004h, 004h, 024h, 0C4h, 008h, 010h, 0E0h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 0C0h, 0E0h, 0E0h, 060h, 0F8h
         DB 0FCh, 0FEh, 0F7h, 0F3h, 0F0h, 0F0h, 0F8h, 078h, 038h, 01Ch
         DB 000h, 000h, 0C0h, 0E0h, 0E0h, 066h, 0FEh, 0FEh, 0FCh, 0F0h
         DB 0F0h, 0F0h, 0F0h, 070h, 070h, 038h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 080h, 000h, 0A0h, 041h, 082h
         DB 084h, 008h, 010h, 026h, 043h, 089h, 023h, 036h, 01Ch, 0D5h
         DB 0AAh, 0DCh, 036h, 0E3h, 0D9h, 0E3h, 036h, 09Ch, 000h, 0C0h
         DB 040h, 0E0h, 040h, 0C0h, 0F0h, 0F8h, 0D8h, 0C4h, 0C2h, 0E1h
         DB 0F0h, 070h, 030h, 038h, 000h, 000h, 0C0h, 040h, 0E0h, 040h
         DB 0C0h, 0F0h, 0F8h, 0FCh, 0ECh, 0E0h, 0E0h, 070h, 038h, 01Ch
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 080h, 000h, 020h
         DB 010h, 08Ah, 04Ch, 048h, 090h, 0B0h, 090h, 056h, 053h, 021h
         DB 083h, 046h, 01Ch, 055h, 0AAh, 0DCh, 036h, 0E3h, 0D9h, 0E3h
         DB 036h, 09Ch
lkanx:   DB 010h, 010h, 010h, 010h, 010h, 010h, 010h, 010h, 010h, 010h
         DB 010h, 010h, 010h, 010h, 010h
lndyv:   DB 000h, 030h, 030h, 030h, 060h, 060h, 060h, 060h, 060h, 040h
         DB 060h, 030h, 020h, 020h, 060h, 030h, 000h, 040h, 060h, 020h
         DB 020h, 050h, 020h, 020h, 060h, 040h, 060h, 020h, 020h, 060h
         DB 030h, 010h, 000h, 040h, 060h, 020h, 020h, 020h, 020h, 020h
         DB 060h, 040h, 060h, 020h, 060h, 030h, 010h, 010h, 000h, 040h
         DB 060h, 020h, 020h, 050h, 020h, 020h, 060h, 040h, 060h, 060h
         DB 030h, 010h, 010h, 060h, 000h, 040h, 050h, 050h, 050h, 050h
         DB 050h, 050h, 050h, 040h, 060h, 030h, 010h, 010h, 060h, 060h
         DB 000h, 030h, 030h, 030h, 030h, 030h, 030h, 030h, 030h, 030h
         DB 030h, 010h, 010h, 060h, 050h, 020h, 000h, 040h, 060h, 060h
         DB 060h, 050h, 060h, 060h, 060h, 040h, 060h, 010h, 060h, 060h
         DB 060h, 020h, 000h, 040h, 040h, 060h, 060h, 050h, 060h, 060h
         DB 040h, 040h, 060h, 020h, 020h, 020h, 020h, 020h, 000h, 060h
         DB 040h, 040h, 060h, 050h, 060h, 040h, 040h, 060h, 060h, 020h
         DB 060h, 060h, 050h, 020h, 000h, 060h, 060h, 040h, 040h, 020h
         DB 040h, 040h, 060h, 060h, 060h, 020h, 060h, 060h, 030h, 030h
         DB 000h, 060h, 060h, 060h, 040h, 040h, 040h, 050h, 060h, 060h
         DB 060h, 020h, 050h, 030h, 030h, 030h, 000h, 060h, 060h, 060h
         DB 040h, 040h, 040h, 050h, 060h, 060h, 030h, 030h, 030h, 030h
         DB 030h, 030h, 000h, 060h, 060h, 040h, 040h, 020h, 040h, 040h
         DB 060h, 060h, 060h, 020h, 060h, 060h, 030h, 030h, 000h, 060h
         DB 040h, 040h, 060h, 050h, 060h, 040h, 040h, 060h, 060h, 020h
         DB 060h, 060h, 050h, 020h, 000h, 040h, 040h, 060h, 060h, 050h
         DB 060h, 060h, 040h, 040h, 060h, 020h, 020h, 020h, 020h, 020h
         DB 000h, 040h, 060h, 060h, 060h, 050h, 060h, 060h, 060h, 040h
         DB 060h, 010h, 060h, 060h, 050h, 020h, 000h, 030h, 030h, 030h
         DB 030h, 030h, 030h, 030h, 030h, 030h, 030h, 010h, 010h, 060h
         DB 060h, 020h, 000h, 050h, 050h, 050h, 020h, 050h, 020h, 050h
         DB 020h, 040h, 060h, 030h, 010h, 010h, 060h, 060h, 000h, 040h
         DB 060h, 060h, 050h, 020h, 050h, 020h, 050h, 040h, 050h, 060h
         DB 030h, 010h, 010h, 060h, 000h, 040h, 060h, 060h, 020h, 050h
         DB 020h, 050h, 020h, 040h, 060h, 050h, 060h, 030h, 010h, 010h
         DB 000h, 040h, 060h, 060h, 050h, 020h, 050h, 020h, 050h, 040h
         DB 060h, 060h, 050h, 060h, 030h, 010h, 000h, 030h, 030h, 030h
         DB 030h, 030h, 030h, 030h, 030h, 040h, 060h, 050h, 060h, 050h
         DB 060h, 030h, 000h, 010h, 010h, 010h, 010h, 010h, 010h, 010h
         DB 010h, 010h, 010h, 010h, 010h, 010h, 010h, 010h, 000h
lkany:   DB 011h, 011h, 011h, 011h, 011h, 011h, 011h, 001h, 033h, 033h
         DB 033h, 033h, 033h, 033h, 033h, 003h, 064h, 066h, 066h, 066h
         DB 033h, 033h, 063h, 002h, 064h, 066h, 066h, 066h, 011h, 011h
         DB 061h, 002h, 033h, 033h, 033h, 043h, 031h, 033h, 063h, 002h
         DB 036h, 062h, 026h, 043h, 031h, 033h, 063h, 002h, 026h, 066h
         DB 066h, 042h, 011h, 011h, 061h, 002h, 026h, 026h, 056h, 042h
         DB 033h, 033h, 063h, 002h, 036h, 062h, 022h
lnhjq:   DB 043h, 033h, 011h, 061h, 002h, 036h, 033h, 033h, 043h, 013h
         DB 013h, 063h, 002h, 036h, 022h, 022h, 043h, 031h, 013h, 063h
         DB 002h, 026h, 066h, 066h, 042h, 011h, 011h, 061h, 002h, 026h
         DB 066h, 056h, 042h, 033h, 033h, 063h, 002h, 036h, 022h, 022h
         DB 043h, 011h, 011h, 061h, 002h, 036h, 033h, 033h, 043h, 031h
         DB 013h, 063h, 002h, 036h, 022h, 022h, 043h, 031h, 013h, 063h
         DB 002h, 026h, 066h, 066h, 042h, 013h, 031h, 063h, 002h, 026h
         DB 066h, 056h, 042h, 033h, 033h, 063h, 002h, 036h, 022h, 022h
         DB 043h, 011h, 011h, 061h, 002h, 033h, 033h, 033h, 043h, 033h
         DB 031h, 063h, 002h, 064h, 066h, 066h, 066h, 013h, 013h, 063h
         DB 002h, 064h, 066h, 066h, 066h, 031h, 033h, 061h, 002h, 033h
         DB 033h, 033h, 033h, 033h, 033h, 033h, 003h, 011h, 011h, 011h
         DB 011h, 011h, 011h, 011h, 001h
lkant:   DB 011h, 011h, 011h, 011h, 011h, 011h, 011h, 001h, 033h, 063h
         DB 066h, 036h, 033h, 033h, 066h, 006h, 064h, 012h, 061h, 015h
         DB 064h, 066h, 062h, 005h, 064h, 052h, 061h, 016h, 064h, 066h
         DB 033h, 003h, 054h, 062h, 066h, 066h, 064h, 066h, 011h, 001h
         DB 064h, 062h, 025h, 066h, 054h, 062h, 033h, 003h, 064h, 062h
         DB 026h, 066h, 064h, 066h, 061h, 006h, 036h, 033h, 033h, 033h
         DB 033h, 033h, 061h, 006h, 016h, 066h, 026h, 066h, 016h, 066h
         DB 061h, 006h, 015h, 066h, 026h, 015h, 013h, 056h, 062h, 006h
         DB 016h, 066h, 026h, 066h, 036h, 033h, 033h, 003h, 036h, 033h
         DB 033h, 033h, 013h, 066h, 061h, 006h, 016h, 046h, 026h, 066h
         DB 026h, 056h, 061h, 006h, 036h, 043h, 026h, 066h, 026h, 066h
         DB 061h, 005h, 064h, 066h, 026h, 036h, 033h, 033h, 033h, 003h
         DB 033h, 033h, 033h, 033h, 046h, 066h, 022h, 002h, 064h, 066h
         DB 066h, 066h, 046h, 066h, 022h, 002h, 064h, 011h, 011h, 066h
         DB 046h, 036h, 022h, 005h, 064h, 022h, 016h, 066h, 046h, 016h
         DB 011h, 001h, 064h, 022h, 015h, 016h, 061h, 036h, 033h, 003h
         DB 064h, 022h, 022h, 036h, 063h, 015h, 066h, 006h, 064h, 022h
         DB 062h, 066h, 061h, 026h, 066h, 006h, 064h, 022h, 062h, 065h
         DB 061h, 026h, 056h, 006h, 011h, 011h, 011h, 011h, 011h, 011h
         DB 011h, 001h, 011h, 011h, 011h, 011h, 011h, 011h, 011h, 001h
         DB 033h, 033h, 033h, 033h, 033h, 033h, 033h, 003h, 026h, 062h
         DB 016h, 066h, 026h, 062h, 066h, 006h, 026h, 062h, 016h, 066h
         DB 026h, 052h, 062h, 006h, 026h, 052h, 016h, 066h, 026h, 066h
         DB 066h, 006h, 026h, 062h, 026h, 066h, 026h, 066h, 061h, 006h
         DB 036h, 033h, 033h, 066h, 036h, 033h, 033h, 003h, 026h, 022h
         DB 022h, 065h, 016h, 066h, 061h, 006h, 064h, 066h, 066h, 066h
         DB 016h, 066h, 062h, 006h, 064h, 033h, 033h, 063h, 016h, 065h
         DB 062h, 006h, 054h, 061h, 061h, 052h, 026h, 032h, 061h, 006h
         DB 064h, 066h, 061h, 066h, 026h, 066h, 061h, 006h, 033h, 033h
         DB 033h, 033h, 033h, 033h, 033h, 003h, 064h, 066h, 061h, 066h
         DB 016h, 066h, 061h, 006h, 054h, 061h, 061h, 052h, 016h, 066h
         DB 061h, 006h, 064h, 033h, 033h, 063h, 036h, 066h, 063h, 006h
         DB 064h, 066h, 066h, 052h, 016h, 066h, 061h, 006h, 026h, 065h
         DB 066h, 066h, 016h, 066h, 061h, 006h, 036h, 033h, 033h, 033h
         DB 033h, 033h, 063h, 005h, 026h, 022h, 012h, 061h, 016h, 066h
         DB 061h, 001h, 026h, 022h, 033h, 062h, 026h, 066h, 061h, 003h
         DB 016h, 056h, 062h, 062h, 026h, 066h, 022h, 006h, 016h, 066h
         DB 052h, 033h, 033h, 033h, 013h, 005h, 011h, 011h, 011h, 011h
         DB 011h, 011h, 011h, 001h, 011h, 011h, 011h, 011h, 011h, 011h
         DB 011h, 001h, 033h, 033h, 033h, 033h, 033h, 033h, 063h, 006h
         DB 064h, 066h, 066h, 064h, 066h, 066h, 064h, 006h, 034h, 033h
         DB 033h, 033h, 033h, 033h, 033h, 003h, 046h, 066h, 066h, 066h
         DB 066h, 033h, 033h, 006h, 046h, 066h, 066h, 066h, 036h, 026h
         DB 012h, 006h, 064h, 052h, 033h, 063h, 063h, 026h, 015h, 006h
         DB 064h, 062h, 066h, 036h, 066h, 026h, 012h, 006h, 064h, 033h
         DB 033h, 033h, 033h, 033h, 033h, 003h, 064h, 011h, 061h, 016h
         DB 061h, 061h, 011h, 001h, 033h, 033h, 033h, 064h, 066h, 066h
         DB 033h, 003h, 046h, 026h, 026h, 064h, 056h, 062h, 046h, 006h
         DB 046h, 026h, 026h, 054h, 033h, 062h, 046h, 006h, 046h, 066h
         DB 026h, 064h, 036h, 033h, 033h, 003h, 064h, 025h, 026h, 026h
         DB 066h, 062h, 046h, 006h, 064h, 026h, 026h, 025h, 035h, 033h
         DB 033h, 006h, 064h, 026h, 026h, 022h, 066h, 064h, 046h, 006h
         DB 064h, 026h, 026h, 025h, 066h, 036h, 033h, 003h, 033h, 023h
         DB 016h, 011h, 011h, 016h, 011h, 001h, 064h, 066h, 064h, 036h
         DB 033h, 033h, 033h, 003h, 064h, 026h, 066h, 046h, 066h, 066h
         DB 066h, 006h, 064h, 026h, 066h, 046h, 056h, 066h, 066h, 006h
         DB 033h, 033h, 033h, 033h, 033h, 033h, 033h, 003h, 011h, 011h
         DB 011h, 011h, 011h, 011h, 011h, 001h, 011h, 011h, 011h, 011h
         DB 011h, 011h, 011h, 001h, 064h, 066h, 066h, 066h, 066h, 064h
         DB 066h, 006h, 044h, 066h, 046h, 066h, 066h, 064h, 046h, 006h
         DB 034h, 033h, 036h, 033h, 036h, 033h, 036h, 003h, 044h, 046h
         DB 046h, 046h, 046h, 046h, 046h, 006h, 044h, 046h, 046h, 046h
         DB 046h, 046h, 046h, 006h, 044h, 046h, 046h, 033h, 033h, 046h
         DB 046h, 006h, 044h, 046h, 046h, 011h, 011h, 041h, 045h, 006h
         DB 044h, 045h, 046h, 046h, 046h, 046h, 046h, 006h, 044h, 046h
         DB 046h, 046h, 046h, 046h, 046h, 006h, 044h, 046h, 046h, 046h
         DB 046h, 046h, 046h, 006h, 033h, 033h, 033h, 033h, 033h, 033h
         DB 033h, 003h, 046h, 046h, 046h, 046h, 046h, 046h, 046h, 006h
         DB 046h, 046h, 046h, 046h, 046h, 046h, 046h, 006h, 046h, 046h
         DB 046h, 046h, 022h, 046h, 046h, 006h, 046h, 046h, 045h, 046h
         DB 046h, 046h, 042h, 006h, 046h, 046h, 046h, 046h, 046h, 046h
         DB 042h, 005h, 046h, 046h, 046h, 046h, 046h, 046h, 042h, 006h
         DB 043h, 046h, 046h, 046h, 046h, 046h, 046h, 006h, 045h, 046h
         DB 046h, 045h, 046h, 046h, 046h, 006h, 046h, 046h, 046h, 046h
         DB 046h, 046h, 046h, 006h, 046h, 036h, 033h, 036h, 033h, 036h
         DB 033h, 006h, 036h, 063h, 066h, 063h, 066h, 063h, 036h, 003h
         DB 011h, 011h, 011h, 011h, 011h, 011h, 011h, 001h, 011h, 011h
         DB 011h, 011h, 011h, 011h, 011h, 001h, 053h, 016h, 033h, 056h
         DB 066h, 066h, 066h, 006h, 064h, 066h, 064h, 066h, 066h, 065h
         DB 066h, 006h, 064h, 033h, 062h, 066h, 066h, 066h, 066h, 006h
         DB 064h, 061h, 062h, 033h, 033h, 033h, 033h, 003h, 064h, 061h
         DB 062h, 011h, 011h, 011h, 061h, 006h, 064h, 061h, 062h, 064h
         DB 065h, 066h, 061h, 006h, 064h, 061h, 062h, 064h, 066h, 066h
         DB 064h, 006h, 054h, 061h, 062h, 064h, 066h, 065h, 064h, 006h
         DB 064h, 061h, 062h, 066h, 066h, 066h, 063h, 006h, 064h, 061h
         DB 011h, 011h, 011h, 066h, 061h, 006h, 064h, 061h, 033h, 033h
         DB 013h, 066h, 061h, 006h, 064h, 061h, 066h, 066h, 015h, 066h
         DB 061h, 006h, 064h, 061h, 033h, 033h, 013h, 066h, 061h, 006h
         DB 064h, 061h, 013h, 011h, 033h, 066h, 061h, 006h, 064h, 061h
         DB 036h, 066h, 046h, 066h, 061h, 006h, 064h, 061h, 041h, 056h
         DB 066h, 066h, 061h, 006h, 064h, 033h, 041h, 066h, 066h, 066h
         DB 061h, 006h, 064h, 061h, 031h, 033h, 033h, 033h, 061h, 005h
         DB 064h, 061h, 011h, 011h, 011h, 011h, 061h, 006h, 033h, 041h
         DB 066h, 015h, 066h, 066h, 066h, 006h, 064h, 031h, 033h, 033h
         DB 033h, 033h, 033h, 003h, 065h, 061h, 066h, 066h, 066h, 065h
         DB 066h, 006h, 011h, 011h, 011h, 011h, 011h, 011h, 011h, 001h
         DB 011h, 011h, 011h, 011h, 011h, 011h, 011h, 001h, 033h, 043h
         DB 066h, 036h, 033h, 043h, 066h, 003h, 064h, 033h, 063h, 045h
         DB 066h, 042h, 065h, 001h, 064h, 042h, 033h, 043h, 066h, 042h
         DB 066h, 001h, 064h, 042h, 066h, 033h, 063h, 042h, 066h, 003h
         DB 064h, 042h, 066h, 042h, 033h, 043h, 066h, 006h, 054h, 042h
         DB 065h, 042h, 066h, 033h, 033h, 004h, 064h, 042h, 066h, 042h
         DB 066h, 042h, 066h, 006h, 064h, 042h, 066h, 042h, 066h, 042h
         DB 066h, 003h, 064h, 042h, 066h, 042h, 022h, 042h, 066h, 001h
         DB 064h, 042h, 065h, 042h, 052h, 033h, 063h, 001h, 034h, 033h
         DB 066h, 042h, 062h, 042h, 053h, 001h, 064h, 046h, 036h, 033h
         DB 062h, 042h, 063h, 003h, 054h, 066h, 066h, 042h, 062h, 042h
         DB 063h, 006h, 034h, 033h, 065h, 042h, 062h, 042h, 063h, 006h
         DB 064h, 042h, 066h, 042h, 062h, 042h, 063h, 003h, 064h, 042h
         DB 066h, 042h, 062h, 042h, 033h, 001h, 064h, 042h, 033h, 043h
         DB 062h, 042h, 065h, 003h, 064h, 042h, 064h, 042h, 062h, 042h
         DB 066h, 003h, 064h, 042h, 064h, 032h, 033h, 033h, 033h, 003h
         DB 064h, 042h, 033h, 043h, 062h, 042h, 066h, 001h, 064h, 042h
         DB 066h, 042h, 062h, 042h, 066h, 001h, 033h, 033h, 033h, 033h
         DB 033h, 033h, 033h, 003h, 011h, 011h, 011h, 011h, 011h, 011h
         DB 011h, 001h, 011h, 011h, 011h, 011h, 011h, 011h, 011h, 001h
         DB 066h, 033h, 033h, 033h, 033h, 033h, 013h, 006h, 051h, 011h
         DB 011h, 011h, 011h, 011h, 015h, 006h, 061h, 061h, 033h, 033h
         DB 033h, 013h, 016h, 006h, 061h, 061h, 011h, 011h, 011h, 016h
         DB 016h, 006h, 033h, 061h, 035h, 033h, 013h, 016h, 016h, 006h
         DB 064h, 066h, 066h, 066h, 016h, 015h, 016h, 006h, 064h, 066h
         DB 066h, 065h, 016h, 016h, 016h, 006h, 033h, 061h, 061h, 066h
         DB 016h, 016h, 016h, 006h, 061h, 033h, 033h, 043h, 036h, 033h
         DB 036h, 003h, 061h, 061h, 061h, 041h, 016h, 016h, 016h, 006h
         DB 061h, 061h, 061h, 041h, 016h, 016h, 016h, 006h, 061h, 061h
         DB 061h, 041h, 016h, 016h, 016h, 006h, 061h, 033h, 061h, 041h
         DB 016h, 016h, 046h, 006h, 061h, 054h, 061h, 041h, 065h, 066h
         DB 046h, 006h, 061h, 064h, 061h, 041h, 016h, 016h, 046h, 006h
         DB 061h, 033h, 061h, 031h, 013h, 016h, 036h, 004h, 061h, 061h
         DB 061h, 011h, 011h, 016h, 016h, 006h, 061h, 061h, 061h, 033h
         DB 033h, 013h, 016h, 005h, 061h, 061h, 011h, 011h, 011h, 011h
         DB 036h, 003h, 051h, 061h, 066h, 066h, 066h, 066h, 016h, 006h
         DB 061h, 011h, 011h, 011h, 011h, 011h, 016h, 006h, 061h, 033h
         DB 033h, 033h, 033h, 033h, 033h, 003h, 011h, 011h, 011h, 011h
         DB 011h, 011h, 011h, 001h, 011h, 011h, 011h, 011h, 011h, 011h
         DB 011h, 001h, 033h, 063h, 066h, 066h, 064h, 023h, 062h, 003h
         DB 064h, 022h, 025h, 062h, 064h, 022h, 036h, 001h, 064h, 022h
         DB 022h, 062h, 064h, 062h, 013h, 001h, 064h, 022h, 025h, 062h
         DB 064h, 036h, 011h, 006h, 054h, 055h, 055h, 055h, 064h, 013h
         DB 061h, 006h, 033h, 033h, 033h, 033h, 033h, 011h, 056h, 002h
         DB 064h, 066h, 065h, 066h, 064h, 061h, 066h, 002h, 044h, 066h
         DB 065h, 046h, 064h, 022h, 022h, 002h, 046h, 064h, 065h, 044h
         DB 066h, 062h, 056h, 002h, 066h, 044h, 042h, 064h, 066h, 062h
         DB 036h, 003h, 066h, 046h, 044h, 065h, 066h, 052h, 033h, 003h
         DB 066h, 046h, 044h, 065h, 036h, 033h, 033h, 003h, 066h, 044h
         DB 042h, 064h, 066h, 062h, 036h, 003h, 046h, 064h, 065h, 044h
         DB 066h, 062h, 056h, 002h, 044h, 066h, 065h, 046h, 064h, 022h
         DB 022h, 002h, 064h, 066h, 065h, 066h, 064h, 061h, 056h, 002h
         DB 033h, 033h, 033h, 033h, 033h, 011h, 066h, 002h, 055h, 025h
         DB 025h, 025h, 064h, 013h, 061h, 006h, 064h, 056h, 052h, 052h
         DB 054h, 036h, 011h, 006h, 064h, 026h, 025h, 025h, 064h, 065h
         DB 013h, 001h, 064h, 056h, 052h, 052h, 064h, 056h, 036h, 001h
         DB 033h, 033h, 033h, 033h, 064h, 065h, 065h, 003h, 011h, 011h
         DB 011h, 011h, 011h, 011h, 011h, 001h, 011h, 011h, 011h, 011h
         DB 011h, 011h, 011h, 001h, 066h, 066h, 066h, 066h, 066h, 066h
         DB 066h, 006h, 066h, 066h, 066h, 066h, 066h, 066h, 066h, 006h
         DB 066h, 066h, 066h, 066h, 066h, 066h, 066h, 006h, 066h, 066h
         DB 066h, 066h, 066h, 066h, 066h, 006h, 066h, 066h, 066h, 066h
         DB 066h, 066h, 066h, 006h, 066h, 066h, 066h, 066h, 066h, 066h
         DB 066h, 006h, 066h, 066h, 066h, 066h, 066h, 066h, 066h, 006h
         DB 066h, 066h, 066h, 066h, 066h, 066h, 066h, 006h, 066h, 066h
         DB 066h, 066h, 066h, 066h, 066h, 006h, 066h, 066h, 066h, 066h
         DB 066h, 066h, 066h, 006h, 066h, 066h, 066h, 066h, 066h, 066h
         DB 066h, 006h, 066h, 066h, 066h, 066h, 066h, 066h, 066h, 006h
         DB 066h, 066h, 066h, 066h, 066h, 066h, 066h, 006h, 066h, 066h
         DB 066h, 066h, 066h, 066h, 066h, 006h, 066h, 066h, 066h, 066h
         DB 066h, 066h, 066h, 006h, 066h, 066h, 066h, 066h, 066h, 066h
         DB 066h, 006h, 066h, 066h, 066h, 066h, 066h, 066h, 066h, 006h
         DB 066h, 066h, 066h, 066h, 066h, 066h, 066h, 006h, 066h, 066h
         DB 066h, 066h, 066h, 066h, 066h, 006h, 066h, 066h, 066h, 066h
         DB 066h, 066h, 066h, 006h, 066h, 066h, 066h, 066h, 066h, 066h
         DB 066h, 006h, 066h, 066h, 066h, 066h, 066h, 066h, 066h, 006h
         DB 066h, 066h, 066h, 066h, 066h, 066h, 066h, 006h
lkajb:   PUSH B
         MOV A,H
         CALL lnpxa
         MOV A,L
         CALL lnpxa
         CALL lnsvj
         POP B
         RET
lnpxb:   MOV A,M
         MOV C,A
         CPI 000h
         RZ
         CALL ljnta
         INX H
         JMP lnpxb
lnsvj:   MVI C,020h
         CALL ljnta
         RET
         DB 0CDh, 000h, 01Dh, 006h, 010h, 07Eh, 0CDh, 08Eh, 01Dh, 0CDh
         DB 01Ah, 01Dh, 0CDh, 027h, 0C4h, 0C8h, 005h, 023h, 032h, 025h
         DB 01Dh, 0EDh, 04Dh, 0CEh, 0CDh, 043h, 0CFh, 0C3h, 020h, 01Dh
         DB 0CDh, 04Dh, 01Dh, 0FEh, 01Fh, 0C0h, 0CDh, 037h, 0C3h, 0FEh
         DB 01Fh, 0C0h, 0C3h, 000h, 0C8h
ljkvn:   CALL lnqep
         PUSH PSW
         CALL ldiev
         POP PSW
         RET
lnqep:   PUSH H
         PUSH B
         CALL lhduj
         LDA ldstf
         CPI 0FFh
         JNZ lnhbr
         LDA lhlrv
         ORI 0F0h
         CPI 0FFh
         JZ ldkyf
         MOV H,A
         MVI L,0FFh
         JMP lnqdz
lnhbr:   MOV L,A
         MVI H,0FFh
lnqdz:   MVI C,0FBh
ljzwh:   INR C
         DAD H
         JC ljzwh
         MOV L,C
         CALL ldiev
         LDA ldgqd
         ORI 003h
         CPI 0FFh
         JNZ lcwaz
         JMP ldkyf
lnpxa:   PUSH D
         PUSH B
         CALL lnpuo
         MOV C,D
         CALL ljnta
         MOV C,E
         CALL ljnta
         POP B
         POP D
         RET
lnpuo:   MOV E,A
         RRC
         RRC
         RRC
         RRC
         CALL ljkus
         MOV D,A
         MOV A,E
         CALL ljkus
         MOV E,A
         RET
ljkus:   ANI 00Fh
         CPI 00Ah
         JC lnqdu
         ADI 007h
lnqdu:   ADI 030h
         RET
ljnta:   PUSH PSW
         MOV A,C
         CPI 007h
         CZ ldlfj
         CPI 020h
         JC ljodq
         PUSH B
         MVI C,07Fh
         CALL lnqeo
         MVI C,008h
         CALL lnqeo
         POP B
ljodq:   CALL lnqeo
         POP PSW
         RET
lnqeo:   LDA lcjko
         CPI 0F8h
         CNC lnthe
         CALL lgozx
         RET
lnthe:   MOV A,C
         CPI 00Ah
         JZ lnhbq
         CPI 01Ah
         JZ lnhbq
         LDA lbxhm
         CPI 0BEh
         RC
lnhbq:   PUSH H
         PUSH D
         PUSH B
         LXI H,lcopl
         LXI D,lghef
         MVI B,030h
lnpuc:   MVI C,078h
lkair:   LDAX D
         MOV M,A
         INX H
         INX D
         LDAX D
         MOV M,A
         INX H
         INX D
         DCR C
         JNZ lkair
         LDA lgfjy
         MVI C,010h
ljodd:   MOV M,A
         INX H
         INX D
         DCR C
         JNZ ljodd
         DCR B
         JNZ lnpuc
         LXI H,000F8h
         SHLD lcjko
         POP B
         POP D
         POP H
         MOV A,C
         CPI 00Ah
         RNZ
         MVI C,01Ah
         RET
         DB 000h, 000h, 000h, 000h
END