;*********************************************************************************************************
; 
; Autogenerated by DizAssembler:
;   https://github.com/codenjoyme/8080-emulator/blob/master/src/main/java/spec/assembler/DizAssembler.java
; From: src/main/resources/lik/apps/buran/buran.rks
; In test: DizAssemblerTest.testDizAssembly()
; 
;*********************************************************************************************************

         CPU  8080
         .ORG 00000h
lkahx    EQU 01840h
lkfau    EQU 02080h
lkezb    EQU 02530h
lkgnt    EQU 03060h
lkglh    EQU 03070h
lodqa    EQU 044DBh
lonea    EQU 044E6h
lktws    EQU 049B4h
lofpj    EQU 05703h
lolqx    EQU 07703h
lcncb    EQU 08000h
lcayz    EQU 08001h
lggar    EQU 08002h
lftxp    EQU 08003h
lbxyf    EQU 08005h
lfqwv    EQU 08007h
lcmsf    EQU 08008h
lcmzp    EQU 08010h
lcmpt    EQU 08018h
lcnbl    EQU 08020h
lcmyz    EQU 08030h
lcncf    EQU 08040h
lcazd    EQU 08041h
lcawr    EQU 08051h
lgfyj    EQU 08052h
lcndh    EQU 08400h
lcasc    EQU 08FF1h
lgfjy    EQU 08FFAh
lcjko    EQU 08FFCh
lcopl    EQU 09000h
lcomj    EQU 09030h
lfrxw    EQU 0909Fh
lcopq    EQU 091C0h
lcomf    EQU 09270h
lcomg    EQU 093F0h
lccno    EQU 09481h
lfskp    EQU 09727h
lggzl    EQU 0984Ah
lcoia    EQU 09890h
lcoaa    EQU 098A8h
lcbwy    EQU 098A9h
lggyq    EQU 098AAh
lbzgd    EQU 09925h
lcbxb    EQU 09929h
lghje    EQU 09982h
lcohq    EQU 099F0h
lcnzt    EQU 09A28h
lbzdh    EQU 09A35h
lghgl    EQU 09B12h
lcohf    EQU 09B30h
lccgt    EQU 09B61h
lcljm    EQU 09B84h
lfvgv    EQU 09C63h
lcocd    EQU 09D48h
lcojn    EQU 09D50h
lccgl    EQU 09D51h
lghid    EQU 09D52h
lbzhr    EQU 09F05h
lcgye    EQU 0A0D1h
lfwvn    EQU 0A177h
lctcv    EQU 0A260h
lctau    EQU 0A290h
lcgxs    EQU 0A291h
lglzk    EQU 0A292h
lctcu    EQU 0A2E0h
lgiyx    EQU 0A356h
lfzyk    EQU 0A3E3h
lchbd    EQU 0A421h
lcgoz    EQU 0A479h
lgipw    EQU 0A4FEh
lcgyn    EQU 0A671h
lctdw    EQU 0A6A0h
lfzps    EQU 0A6EBh
lgaad    EQU 0A703h
lfwyt    EQU 0A727h
lcsug    EQU 0A7E8h
lcsmj    EQU 0A818h
lcsyv    EQU 0A840h
lcsvv    EQU 0A970h
lcduw    EQU 0A985h
lcsxt    EQU 0AA20h
lcgur    EQU 0AA21h
lglwj    EQU 0AA22h
lglmm    EQU 0AAAAh
lcdtz    EQU 0AB25h
lgivv    EQU 0AB66h
lfwrw    EQU 0AE97h
lginc    EQU 0AEEEh
lcszv    EQU 0AF40h
lgnor    EQU 0B222h
lcuoj    EQU 0B250h
lgnmz    EQU 0B252h
lcuqd    EQU 0B320h
lcrrp    EQU 0B444h
lcifj    EQU 0B509h
lcupu    EQU 0B590h
lcfes    EQU 0B5CDh
lciol    EQU 0B761h
lgbhd    EQU 0B863h
lgbeh    EQU 0BB33h
lgnkp    EQU 0BB42h
lgnlh    EQU 0BC22h
lciab    EQU 0BE09h
ldlif    EQU 0C000h
ldlft    EQU 0C010h
lgozx    EQU 0C037h
ldlfj    EQU 0C170h
lgozr    EQU 0C337h
ldkwn    EQU 0C438h
ldmqr    EQU 0D800h
lhlqv    EQU 0F802h
ldstf    EQU 0FF00h
lhlrv    EQU 0FF02h
lgzot    EQU 0FF03h
ldsqg    EQU 0FFF0h
ldsgk    EQU 0FFF8h
lgwbe    EQU 0FFFFh
         LXI H,00000h
         SHLD lcawr
lnoxd:   CALL ldlft
         LXI H,lkezb
         SHLD lcjko
         CALL ljyzq
         LXI H,ljjgx
         CALL ldkwn
         CALL ljmms
         LXI H,lcocd
         LXI B,ljmrd
         CALL lnolv
         CALL ljyzq
         LXI H,lcncb
         MVI A,04Fh
ljvob:   MVI M,000h
         INX H
         DCR A
         JNZ ljvob
         LXI H,lndxz
         MVI A,020h
ljymj:   MVI M,000h
         INX H
         DCR A
         JNZ ljymj
         SHLD lftxp
         MVI A,097h
         STA lggar
         LXI D,ljyzm
         LXI H,lkama
         SHLD lcjko
         MOV B,H
         XCHG
lnrvp:   XCHG
         LHLD lcjko
         MOV H,B
         MOV A,L
         ADI 00Ah
         MOV L,A
         SHLD lcjko
         XCHG
         CALL ldkwn
         INX H
         MOV A,M
         ANA A
         JNZ lnrvp
         LHLD lcawr
         MOV A,L
         MOV D,H
         LXI H,lodqa
         SHLD lcjko
         CMP D
         JC lnfib
         MOV D,A
         STA lgfyj
lnfib:   CALL ljyxj
         MOV A,D
         LXI H,lonea
         SHLD lcjko
         CALL ljyxj
ljypk:   LHLD lnokg
         CALL lnonq
         LXI B,0051Fh
         CALL ljjjg
         CALL ljyzq
         CALL lgozr
         CALL lnrvv
         CPI 002h
         JZ ljvya
         CPI 003h
         JZ ljmtg
         CPI 006h
         JNZ ljypk
         MOV A,L
         CPI 0BEh
         RNC
         CPI 0B4h
         JNC ljjvr
         CPI 0AAh
         JNC lnrnn
         LXI H,lcomj
         LXI D,lkglh
         MVI C,000h
         CALL lnflb
         LXI H,lctdw
         LXI D,lkahx
         CALL lnflb
         LXI H,lkacz
         SHLD lcjko
         LXI H,ljjwo
         CALL ldkwn
         JMP ljypk
ljjjg:   MOV M,C
         DCX H
         DCR B
         JNZ ljjjg
         RET
ljvya:   LDA lnokg
         CPI 0AAh
         JC ljypk
         MVI A,0F6h
         JMP lnfia
ljmtg:   LDA lnokg
         CPI 0BEh
         JNC ljypk
         MVI A,00Ah
lnfia:   LHLD lnokg
         ADD L
         STA lnokg
         LXI B,00500h
         CALL ljjjg
         JMP ljypk
lnflb:   MOV B,E
ljvot:   MOV M,C
         INX H
         DCR B
         JNZ ljvot
         MOV A,L
         SUB E
         MOV L,A
         INR H
         DCR D
         JNZ lnflb
         RET
lnfip:   PUSH B
         MVI C,07Fh
         CALL lgozx
         MVI C,008h
         CALL lgozx
         POP B
         JMP lgozx
lnrnn:   LDA lnola
         INR A
         CPI 034h
         JC ljjsl
         MVI A,031h
ljjsl:   STA lnola
         MOV C,A
         LXI H,lktws
         SHLD lcjko
         CALL lnfip
         JMP ljypk
ljjvr:   CALL ldlft
         LDA lnola
         SUI 02Fh
         MOV C,A
         MVI A,0FFh
ljyxb:   ANA A
         RAR
         DCR C
         JNZ ljyxb
         STA lfqwv
         CALL ljmwt
         CALL lnoog
         LXI H,lcsmj
         SHLD lcjko
         LXI H,ljvwk
         CALL ldkwn
         LXI H,lcsug
         LXI B,lndwo
         CALL lnolv
         LXI H,lcopl
         LXI B,lnfqy
         CALL ljvyw
         CALL lnolv
         LXI H,lcfes
         LXI B,ljojo
         CALL ljyzq
         CALL lnolv
         CALL lncvd
         XRA A
ljyww:   STA lcmpt
         LXI H,lfqwv
         MOV C,M
         ANA C
         JZ lnfug
         ANI 001h
         JZ ljvli
         JMP ljjmh
lnfug:   CALL lnrvt
         MOV A,L
         ANI 0ABh
         JNZ lnfur
         MVI B,007h
         LXI H,lcmsf
ljmte:   CALL lnfji
         JZ ljywn
         DCR B
         JNZ ljmte
         JMP ljvli

lnokg:   DB 0A8h, 092h
ljyzm:   DB 069h, 06Eh, 073h, 074h, 072h, 075h, 06Bh, 063h, 069h, 071h
         DB 000h, 075h, 072h, 06Fh, 077h, 065h, 06Eh, 078h, 020h, 073h
         DB 06Ch, 06Fh, 076h, 06Eh, 06Fh, 073h, 074h, 069h, 020h, 020h
lnola:   DB 032h, 000h, 069h, 067h, 072h, 061h, 000h, 077h, 079h, 068h
         DB 06Fh, 064h, 000h, 020h, 000h, 075h, 06Eh, 069h, 07Eh, 074h
         DB 06Fh, 076h, 065h, 06Eh, 06Fh, 020h, 063h, 065h, 06Ch, 065h
         DB 06Ah, 000h, 06Ch, 075h, 07Eh, 07Bh, 069h, 06Ah, 020h, 072h
         DB 065h, 07Ah, 075h, 06Ch, 078h, 074h, 061h, 074h, 000h, 000h
ljywn:   INR A
         CALL lncuz
         CALL lnrvt
         XCHG
         LXI H,lcnbl
         CALL ljjkb
lnokn:   CALL lnrvt
         MOV A,H
         ANI 07Eh
         CPI 011h
         JC lnokn
         MOV D,A
         MOV E,L
         LXI H,lcmyz
         CALL ljjkb
         MVI A,080h
         LXI H,lcmzp
         CALL lncuz
         CALL ljmwt
         LXI H,lcncf
         INR M
         CALL ljmwt
lnfur:   CALL lncvd
         MVI B,001h
ljyph:   LXI H,lcmsf
         CALL lnfji
         JZ lnfrm
         LXI H,lcnbl
         CALL lnrwj
         PUSH D
         LXI H,lcmyz
         CALL lnrwj
         XCHG
         POP D
         CALL lnoxy
         DCR L
         DCR L
         MVI C,003h
lncth:   MVI E,004h
ljmlp:   MVI M,000h
         INR L
         DCR E
         JNZ ljmlp
         LXI D,000FCh
         DAD D
         DCR C
         JNZ lncth
         CALL lnrvt
         MOV A,H
         MVI E,004h
         CALL ljmww
         ANA A
         RAR
         JC lncts
         CMA
lncts:   MOV C,A
ljypc:   LXI H,lcmzp
         CALL lnfji
         ADD C
         CALL lncuz
         CALL ljjjv
         MOV A,D
         ANA A
         JNZ lnchk
lnrlg:   MVI C,080h
         JMP ljypc
lnchk:   MOV A,H
         CPI 010h
         JC lnrlg
         CPI 080h
         JNC lnrlg
         CALL lnoxy
         DCR L
         DCR L
         SHLD lbxyf
         LXI H,lcmpt
         CALL lnfji
         PUSH H
         PUSH PSW
         MVI E,005h
         CALL ljmww
         LXI H,lndxx
         LXI D,00008h
         CALL ljyqc
         POP PSW
         POP H
         INR A
         CALL lncuz
         ANA A
         JNZ lnfrm
         PUSH B
         LXI H,lcnbl
         CALL lnrwj
         PUSH D
         LXI H,lcmyz
         CALL lnrwj
         INR D
         CALL ljjkb
         POP H
         XRA A
         STA lcncb
         MOV B,A
         MOV C,A
         MVI A,088h
         SUB H
         JNC lnotw
         STA lcncb
         CMA
         INR A
lnotw:   MOV H,A
         MVI A,0E0h
         SUB D
         CMA
         INR A
         MVI D,0FFh
         MOV E,A
lncgy:   DAD D
         INX B
         MOV A,H
         ANA A
         JNZ lncgy
         MOV A,B
         ANA A
         JZ ljjlj
         MVI C,0FFh
ljjlj:   MOV A,C
         ANA A
         RAR
         ANA A
         RAR
         ANA A
         RAR
         LXI H,lcncb
         INR M
         DCR M
         JNZ lnokp
         CMA
         INR A
lnokp:   ADI 080h
         POP B
         PUSH PSW
lnrxb:   POP PSW
         PUSH PSW
         CALL ljjjv
         CALL lnoxy
         INR H
         CALL lnonq
         MVI A,080h
         JZ ljymd
lnfrn:   RRC
         DCR C
         JNZ lnfrn
ljymd:   MOV M,A
         MOV A,L
         ANA A
         JNZ lnrxb
         POP PSW
         LXI H,00101h
lnrxv:   SHLD lcasc
         CALL ldlfj
         INR H
         INR L
         INR L
         MOV A,L
         CPI 03Ch
         JC lnrxv
ljmtr:   SHLD lcasc
         CALL ldlfj
         DCR H
         DCR L
         DCR L
         JP ljmtr
         LXI H,lkfau
         SHLD lcasc
         CALL ljmms
         LXI H,lgwbe
         SHLD lgfjy
         CALL ldlft
         CALL ljyzq
         LXI H,lhlqv
         LXI D,00020h
         MVI B,032h
lnrkx:   MOV M,E
         CALL lncsp
         MVI M,000h
         MOV A,B
         CALL lncsp
         INR B
         MOV A,B
         CPI 0C8h
         JNZ lnrkx
         XRA A
         MOV H,A
         MOV L,A
         SHLD lgfjy
         LDA lcazd
         STA lcawr
         JMP lnoxd
         DB 0AFh, 057h, 05Fh, 01Ah, 067h, 013h, 01Ah, 06Fh, 013h, 022h
         DB 003h, 080h, 0CDh, 032h, 007h, 0C0h, 07Ah, 0FEh, 009h, 0C2h
         DB 09Dh, 003h, 0C3h, 09Ah, 003h
lnfrm:   INR B
         MOV A,B
         CPI 008h
         JNZ ljyph
         MVI B,000h
ljvli:   CALL lnrvv
         PUSH PSW
         LDA lcmsf
         ANA A
         JNZ ljvxu
         POP PSW
         CPI 006h
         JNZ ljyqd
         LXI H,lcmsf
         INR M
         LXI H,lcndh
         SHLD lcnbl
         LXI H,ldmqr
         SHLD lcmyz
         XRA A
         STA lcmzp
         JMP lnrzd
ljvxu:   LDA lcmpt
         ANI 003h
         JZ lnomo
         POP H
         PUSH PSW
lnomo:   POP PSW
         LXI H,lcmzp
         CPI 009h
         JZ lnokc
         CPI 007h
         JNZ ljjik
         DCR M
ljjik:   DCR M
lnokc:   INR M
         LDA lcmzp
lnrzd:   CALL ljjjv
         PUSH H
         PUSH D
         MVI B,007h
ljmnp:   LXI H,lcmsf
         CALL lnfji
         JZ lnooa
         POP H
         PUSH H
         MOV A,H
         LXI H,lcnbl
         CALL lnrwj
         SUB D
         JP ljmwv
         CMA
         INR A
ljmwv:   CPI 003h
         JNC lnooa
         POP D
         POP H
         PUSH H
         PUSH D
         MOV A,H
         LXI H,lcmyz
         CALL lnrwj
         SUB D
         JP lncsf
         CMA
         INR A
lncsf:   CPI 003h
         JNC lnooa
         POP D
         POP H
         CALL lnoxy
         XRA A
         LXI D,ldsgk
ljjwv:   DAD D
         SHLD lbxyf
         PUSH PSW
         CALL lnonq
         POP PSW
         PUSH PSW
         LXI D,00020h
         LXI H,lndyb
         CALL ljyqc
         CALL ljyzq
         POP PSW
         PUSH PSW
         PUSH B
         ANA A
         JNZ lnrov
         MVI B,014h
ljvzh:   DCX B
         MOV A,B
         ANA A
         JNZ ljvzh
lnrov:   ADI 003h
         RLC
         RLC
         LXI H,ldlif
         MVI E,000h
         MOV B,A
ljvwv:   MOV C,B
         MOV A,M
         ANI 020h
ljynt:   STA lhlqv
         DCR C
         JNZ ljynt
         INX H
         DCR E
         JNZ ljvwv
         POP B
         LHLD lbxyf
         LXI D,ldsqg
         POP PSW
         INR A
         CPI 007h
         JC ljjwv
         XRA A
         STA lcncb
         LXI H,lcmsf
         MOV M,A
         CALL lncuz
         LXI H,lcmpt
         CALL lncuz
         CALL ljmwt
         CALL lnoog
         LXI H,lcazd
         MOV A,M
         INR A
         DAA
         MOV M,A
         DCX H
         DCR M
         CPI 080h
         JNC ljzaq
         CALL ljmwt
         CALL lnoog
         JMP ljjmh
ljzaq:   MVI C,033h
         CALL ldlft
         CALL ljvyw
         LXI H,lcopl
         LXI D,lkgnt
         PUSH D
         CALL lnflb
         POP D
         LXI H,lfrxw
         CALL lnflb
         CALL ljyzq
         LXI H,lnhfh
         SHLD lcjko
         LXI H,lnopj
         CALL ldkwn
         CALL lgozr
         JMP lnoxd
lnooa:   DCR B
         JNZ ljmnp
         POP D
         POP H
         MOV A,H
         ANA A
         JZ lnrzf
         MOV A,D
         ANA A
         JZ lnrzf
         INR A
         JNZ ljyqt
lnrzf:   STA lcmsf
         JMP ljjmh
ljyqt:   PUSH H
         LHLD lcayz
         LDA lcncb
         MOV M,A
         POP H
         CALL lnoxy
         INR H
         MVI A,080h
         JZ lncjb
lnrmx:   RRC
         DCR C
         JNZ lnrmx
lncjb:   MOV C,M
         MOV M,A
         MOV A,C
         STA lcncb
         SHLD lcayz
ljyqd:   ANA A
ljmnb:   DCR A
         JNZ ljmnb
ljjmh:   LDA lcazd
         RLC
         CMA
lnrwd:   DCR A
         JNZ lnrwd
         LDA lcmpt
         INR A
         JMP ljyww
ljjjv:   LXI H,lcnbl
         CALL lnrwj
         PUSH D
         LXI H,lcmyz
         CALL lnrwj
         MOV H,B
         POP B
         ANA A
         RAL
         JNC ljyxr
         DCR B
         ANA A
         RAL
         JNC lnoxz
         DCR D
         ANA A
         RAL
         JNC lncvi
ljjkp:   ADD C
         JNC lnryt
         INR B
lnryt:   MOV C,A
         JMP lnooo
lnoxz:   ANA A
         RAL
         JC lncvi
lnflv:   INR D
         CMA
         JMP ljjkp
ljyxr:   ANA A
         RAL
         JC lncip
         DCR D
         ANA A
         RAL
         JNC ljjkp
lnfjj:   INR B
         JMP ljyqs
lncip:   ANA A
         RAL
         JNC lnfjj
         JMP lnflv
lncvi:   CMA
ljyqs:   ADD E
         JNC ljjmw
         INR D
ljjmw:   MOV E,A
lnooo:   PUSH B
         MOV B,H
         LXI H,lcmyz
         CALL ljjkb
         POP H
         XCHG
         PUSH H
         LXI H,lcnbl
         CALL ljjkb
         POP H
         RET
ljmww:   ANA A
         RAR
         DCR E
         JNZ ljmww
         RET
ljyqc:   ANA A
         JZ ljmuk
ljvpi:   DAD D
         DCR A
         JNZ ljvpi
ljmuk:   MOV A,E
         ANA A
         RAR
         PUSH B
ljjtq:   PUSH PSW
         MOV D,M
         INX H
         MOV E,M
         INX H
         MVI B,000h
         PUSH H
         MOV A,C
         ANA A
         JZ ljyyg
         MOV H,C
lnfwg:   MOV A,D
         RAR
         MOV D,A
         MOV A,E
         RAR
         MOV E,A
         MOV A,B
         RAR
         MOV B,A
         DCR H
         JNZ lnfwg
ljyyg:   LHLD lbxyf
         MOV M,D
         INR H
         MOV M,E
         INR H
         MOV M,B
         DCR H
         DCR H
         INR L
         SHLD lbxyf
         POP H
         POP PSW
         DCR A
         JNZ ljjtq
         POP B
         RET
lnoxy:   MOV L,H
         MOV A,D
         MOV C,D
         MVI E,003h
         CALL ljmww
         MOV E,A
         ADI 097h
         MOV H,A
         MOV A,E
         RLC
         RLC
         RLC
         SUB C
         CMA
         INR A
         MOV C,A
         RET
lnfji:   PUSH B
         PUSH H
ljjjy:   INX H
         DCR B
         JNZ ljjjy
         MOV A,M
         POP H
         POP B
         ANA A
         RET
lncuz:   PUSH B
         PUSH H
ljmnh:   INX H
         DCR B
         JNZ ljmnh
         MOV M,A
         POP H
         POP B
         RET
lnrwj:   PUSH B
         PUSH H
         CALL ljypt
         MOV E,M
         INX H
         MOV D,M
         POP H
         POP B
         RET
ljjkb:   PUSH B
         PUSH H
         CALL ljypt
         MOV M,E
         INX H
         MOV M,D
         POP H
         POP B
         RET
ljypt:   INR B
         DCR B
         RZ
lnflh:   INX H
         INX H
         DCR B
         JNZ lnflh
         RET
lnrvt:   LHLD lftxp
         MVI C,010h
lncrx:   MOV A,H
         DAD H
         ANI 060h
         JPE lncib
         INX H
lncib:   DCR C
         JNZ lncrx
         SHLD lftxp
         RET
lncvd:   CALL ljvyw
         MVI A,004h
         STA lcojn
         STA lcopq
         STA lcomg
         STA lggzl
         STA lchbd
         STA lfwyt
         STA lgivv
         STA lcsvv
         STA lcohf
         STA lbzdh
         STA lcomf
         STA lccno
         STA lcdtz
         STA lcoaa
         STA lggyq
         STA lcszv
         STA lcuoj
         STA lgnor
         STA lcuqd
         STA lcrrp
         STA lcifj
         STA lcupu
         STA lginc
         STA lgipw
         STA lfzps
         STA lcohq
         STA lctau
         STA lglzk
         STA lghid
         STA lcsxt
         STA lglwj
         STA lcduw
         STA lcsyv
         STA lfwvn
         STA lctcv
         STA lgiyx
         STA lcgoz
         STA lcgyn
         MVI A,001h
         STA lgnmz
         STA lcnzt
         STA lbzgd
         STA lglmm
         STA lfskp
         STA lcgye
         STA lctcu
         STA lfzyk
         STA lfwrw
         STA lgbeh
         STA lgnkp
         STA lciab
         STA lgnlh
         STA lgbhd
         STA lciol
         STA lcbxb
         STA lbzhr
         STA lghgl
         STA lcoia
         STA lghje
         STA lccgt
         STA lfvgv
         STA lcljm
         MVI A,00Eh
         STA lccgl
         STA lcgxs
         STA lcgur
         STA lcbwy
         CALL ljyzq
         RET
lncsp:   DCR A
         XTHL
         XTHL
         JNZ lncsp
         RET
lnolv:   LDAX B
         INX B
         MOV D,A
ljmwp:   LDAX B
         INX B
         MOV M,A
         INX H
         DCR D
         JNZ ljmwp
         LDAX B
         INX B
         ANA A
         RZ
         MOV E,A
         DAD D
         JMP lnolv
lnrvv:   PUSH B
         MVI A,091h
         STA lgzot
         MVI C,000h
         LDA ldstf
         MVI B,008h
lncid:   RAR
         JNC lnovv
         INR C
         DCR B
         JNZ lncid
         LDA lhlrv
         MVI B,003h
ljjmt:   RAR
         JNC lnovv
         INR C
         DCR B
         JNZ ljjmt
lnovv:   MVI A,082h
         STA lgzot
         MOV A,C
         CMA
         ADI 00Ch
         POP B
         RET
ljmwt:   LXI H,005D0h
         SHLD lcjko
         LXI H,ljmoh
         CALL ldkwn
         LDA lcncf
ljyxj:   PUSH B
         MOV B,A
         CALL lnfjb
         MOV A,B
         CALL lncih
         POP B
         RET
lnfjb:   RRC
         RRC
         RRC
         RRC
lncih:   ANI 00Fh
         CPI 00Ah
         JC ljyqk
         ADI 007h
ljyqk:   ADI 030h
         MOV C,A
         JMP lgozx
lnoog:   LXI H,005E0h
         SHLD lcjko
         LXI H,lncch
         CALL ldkwn
         LDA lcazd
         JMP ljyxj
ljyzq:   XRA A
         JMP ljyxe
ljvyw:   MVI A,040h
         JMP ljyxe
ljmms:   MVI A,080h
         JMP ljyxe
lnonq:   MVI A,0C0h
ljyxe:   STA lhlrv
         RET

ljvwk:   DB 02Ah, 020h, 041h, 044h, 044h, 020h, 02Ah, 000h, 020h, 02Ah
         DB 020h, 031h, 039h, 038h, 039h, 020h, 02Ah
ljjwo:   DB 077h, 079h, 020h, 02Dh, 020h, 070h, 069h, 06Ch, 06Fh, 074h
         DB 020h, 06Bh, 06Fh, 073h, 06Dh, 069h, 07Eh, 065h, 073h, 06Bh
         DB 06Fh, 067h, 06Fh, 020h, 06Bh, 06Fh, 072h, 061h, 062h, 06Ch
         DB 071h, 020h, 074h, 069h, 070h, 061h, 020h, 022h, 062h, 075h
         DB 072h, 061h, 06Eh, 022h, 00Ah, 020h, 020h, 020h, 06Eh, 061h
         DB 020h, 073h, 074h, 06Fh, 072h, 06Fh, 06Eh, 065h, 020h, 070h
         DB 072h, 06Fh, 074h, 069h, 077h, 06Eh, 069h, 06Bh, 061h, 020h
         DB 06Dh, 061h, 06Eh, 065h, 077h, 072h, 065h, 06Eh, 06Eh, 079h
         DB 065h, 020h, 073h, 070h, 075h, 074h, 06Eh, 069h, 06Bh, 069h
         DB 02Dh, 069h, 073h, 074h, 072h, 065h, 062h, 069h, 074h, 065h
         DB 06Ch, 069h, 00Ah, 020h, 020h, 020h, 073h, 020h, 06Ch, 061h
         DB 07Ah, 065h, 072h, 06Eh, 079h, 06Dh, 020h, 077h, 06Fh, 06Fh
         DB 072h, 075h, 076h, 065h, 06Eh, 069h, 065h, 06Dh, 020h, 06Dh
         DB 061h, 06Ch, 06Fh, 06Ah, 020h, 064h, 061h, 06Ch, 078h, 06Eh
         DB 06Fh, 073h, 074h, 069h, 00Ah, 020h, 020h, 020h, 077h, 061h
         DB 07Bh, 061h, 020h, 07Ah, 061h, 064h, 061h, 07Eh, 061h, 020h
         DB 02Dh, 020h, 075h, 06Eh, 069h, 07Eh, 074h, 06Fh, 076h, 069h
         DB 074h, 078h, 020h, 061h, 070h, 070h, 061h, 072h, 061h, 074h
         DB 079h, 020h, 070h, 072h, 069h, 07Bh, 065h, 06Ch, 078h, 063h
         DB 065h, 077h, 020h, 072h, 061h, 06Eh, 078h, 07Bh, 065h, 02Ch
         DB 00Ah, 020h, 020h, 020h, 07Eh, 065h, 06Dh, 020h, 06Fh, 06Eh
         DB 069h, 020h, 070h, 072h, 069h, 062h, 06Ch, 069h, 07Ah, 071h
         DB 074h, 073h, 071h, 020h, 06Eh, 061h, 020h, 072h, 061h, 073h
         DB 073h, 074h, 06Fh, 071h, 06Eh, 069h, 065h, 020h, 077h, 079h
         DB 073h, 074h, 072h, 065h, 06Ch, 061h, 00Ah, 020h, 020h, 020h
         DB 06Eh, 061h, 020h, 06Bh, 06Fh, 072h, 061h, 062h, 06Ch, 065h
         DB 020h, 069h, 06Dh, 065h, 065h, 074h, 073h, 071h, 020h, 06Eh
         DB 065h, 06Fh, 067h, 072h, 061h, 06Eh, 069h, 07Eh, 065h, 06Eh
         DB 06Eh, 079h, 06Ah, 020h, 07Ah, 061h, 070h, 061h, 073h, 020h
         DB 075h, 070h, 072h, 061h, 077h, 06Ch, 071h, 065h, 06Dh, 079h
         DB 068h, 020h, 072h, 061h, 06Bh, 065h, 074h, 00Ah, 020h, 020h
         DB 020h, 070h, 075h, 073h, 06Bh, 020h, 072h, 061h, 06Bh, 065h
         DB 074h, 079h, 020h, 02Dh, 020h, 070h, 072h, 06Fh, 062h, 065h
         DB 06Ch, 00Ah, 020h, 020h, 020h, 075h, 070h, 072h, 061h, 077h
         DB 06Ch, 065h, 06Eh, 069h, 065h, 020h, 02Dh, 020h, 06Bh, 06Ch
         DB 061h, 077h, 069h, 07Bh, 069h, 020h, 06Bh, 075h, 072h, 073h
         DB 06Fh, 072h, 061h, 000h
ljmoh:   DB 077h, 069h, 076h, 075h, 020h, 063h, 065h, 06Ch, 065h, 06Ah
         DB 020h, 02Dh, 020h, 000h
lncch:   DB 075h, 06Eh, 069h, 07Eh, 074h, 06Fh, 076h, 065h, 06Eh, 06Fh
         DB 020h, 02Dh, 020h, 000h
ljjgx:   DB 02Ah, 020h, 02Ah, 020h, 02Ah, 020h, 020h, 07Ah, 020h, 077h
         DB 020h, 065h, 020h, 07Ah, 020h, 064h, 020h, 06Eh, 020h, 079h
         DB 020h, 065h, 020h, 020h, 020h, 077h, 020h, 06Fh, 020h, 06Ah
         DB 020h, 06Eh, 020h, 079h, 020h, 02Ah, 020h, 02Ah, 020h, 02Ah
         DB 000h
lnopj:   DB 075h, 063h, 065h, 06Ch, 065h, 077h, 07Bh, 069h, 065h, 020h
         DB 069h, 073h, 074h, 072h, 065h, 062h, 069h, 074h, 065h, 06Ch
         DB 069h, 020h, 061h, 067h, 072h, 065h, 073h, 073h, 069h, 077h
         DB 06Eh, 079h, 068h, 020h, 067h, 075h, 06Dh, 061h, 06Eh, 06Fh
         DB 069h, 064h, 06Fh, 077h, 00Ah, 020h, 020h, 020h, 020h, 077h
         DB 020h, 070h, 061h, 06Eh, 069h, 06Bh, 065h, 020h, 070h, 06Fh
         DB 06Bh, 069h, 064h, 061h, 060h, 074h, 020h, 06Fh, 06Bh, 06Fh
         DB 06Ch, 06Fh, 07Ah, 065h, 06Dh, 06Eh, 06Fh, 065h, 020h, 070h
         DB 072h, 06Fh, 073h, 074h, 072h, 061h, 06Eh, 073h, 074h, 077h
         DB 06Fh, 02Eh, 00Ah, 020h, 020h, 020h, 020h, 072h, 065h, 07Bh
         DB 065h, 06Eh, 069h, 065h, 06Dh, 020h, 077h, 073h, 065h, 06Dh
         DB 069h, 072h, 06Eh, 06Fh, 067h, 06Fh, 020h, 073h, 06Fh, 077h
         DB 065h, 074h, 061h, 020h, 077h, 061h, 06Dh, 020h, 070h, 072h
         DB 069h, 073h, 077h, 061h, 069h, 077h, 061h, 065h, 074h, 073h
         DB 071h, 020h, 07Ah, 077h, 061h, 06Eh, 069h, 065h, 00Ah, 020h
         DB 020h, 020h, 020h, 022h, 073h, 06Bh, 072h, 06Fh, 06Dh, 06Eh
         DB 079h, 06Ah, 020h, 067h, 065h, 072h, 06Fh, 06Ah, 020h, 06Fh
         DB 062h, 06Fh, 07Ah, 072h, 069h, 06Dh, 06Fh, 06Ah, 020h, 077h
         DB 073h, 065h, 06Ch, 065h, 06Eh, 06Eh, 06Fh, 06Ah, 022h, 02Eh
         DB 020h, 070h, 06Fh, 07Ah, 064h, 072h, 061h, 077h, 06Ch, 071h
         DB 060h, 021h, 000h
ljmrd:   DB 00Dh, 00Fh, 030h, 040h, 080h, 081h, 080h, 042h, 020h, 010h
         DB 008h, 004h, 002h, 001h, 0F3h, 015h, 0FFh, 000h, 088h, 000h
         DB 010h, 000h, 020h, 000h, 000h, 000h, 000h, 000h, 000h, 080h
         DB 040h, 020h, 010h, 008h, 004h, 002h, 001h, 0EBh, 01Bh, 0FFh
         DB 000h, 007h, 00Ah, 01Ch, 000h, 038h, 028h, 028h, 038h, 028h
         DB 026h, 029h, 011h, 009h, 007h, 000h, 000h, 000h, 000h, 000h
         DB 080h, 040h, 020h, 018h, 006h, 001h, 0E5h, 01Fh, 0FFh, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 001h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 080h, 060h, 018h, 006h, 001h, 0E1h
         DB 023h, 0FFh, 000h, 000h, 000h, 000h, 000h, 030h, 07Ch, 018h
         DB 0C0h, 0F0h, 060h, 000h, 000h, 000h, 000h, 010h, 000h, 000h
         DB 000h, 000h, 040h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 080h, 060h, 018h, 006h, 001h, 0DDh, 02Bh, 080h, 078h
         DB 006h, 001h, 000h, 000h, 000h, 040h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 004h
         DB 000h, 000h, 000h, 000h, 010h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 080h, 0E0h, 058h, 026h, 011h, 008h, 004h, 002h
         DB 001h, 0D8h, 030h, 080h, 060h, 018h, 006h, 001h, 000h, 000h
         DB 000h, 000h, 010h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 001h, 000h, 000h, 000h
         DB 000h, 004h, 000h, 000h, 000h, 000h, 000h, 000h, 080h, 060h
         DB 018h, 006h, 001h, 080h, 040h, 020h, 010h, 008h, 004h, 002h
         DB 001h, 0D4h, 034h, 080h, 060h, 018h, 006h, 001h, 000h, 000h
         DB 000h, 000h, 000h, 004h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 001h, 000h, 000h, 000h, 000h, 000h, 080h, 060h
         DB 018h, 006h, 001h, 000h, 000h, 000h, 000h, 080h, 040h, 020h
         DB 010h, 008h, 004h, 002h, 001h, 0D0h, 03Ch, 080h, 060h, 018h
         DB 006h, 001h, 000h, 000h, 000h, 000h, 000h, 000h, 001h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 040h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 080h, 060h, 018h, 006h, 001h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 080h, 040h, 020h, 010h, 008h
         DB 008h, 004h, 004h, 002h, 002h, 001h, 001h, 0C8h, 048h, 080h
         DB 060h, 018h, 006h, 001h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 010h, 000h, 000h, 000h, 000h, 040h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 080h, 060h, 018h, 006h, 001h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 080h, 080h, 040h, 040h, 020h
         DB 020h, 010h, 010h, 008h, 008h, 004h, 004h, 002h, 002h, 001h
         DB 001h, 0BCh, 052h, 080h, 060h, 018h, 006h, 001h, 000h, 000h
         DB 000h, 040h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 004h, 000h, 000h, 000h, 000h
         DB 010h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 080h, 060h
         DB 018h, 006h, 001h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 080h, 080h, 040h, 040h, 020h, 020h, 010h, 010h, 008h
         DB 008h, 004h, 004h, 002h, 001h, 0B2h, 052h, 080h, 067h, 018h
         DB 006h, 001h, 000h, 000h, 000h, 000h, 010h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 001h, 000h, 000h, 000h, 000h, 004h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 080h, 060h, 018h, 006h, 001h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 080h, 061h, 019h, 006h, 001h, 0AEh
         DB 056h, 01Fh, 0E0h, 000h, 000h, 080h, 060h, 018h, 006h, 001h
         DB 000h, 000h, 000h, 000h, 000h, 004h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 001h, 000h, 000h, 000h, 000h, 000h
         DB 080h, 060h, 018h, 006h, 001h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 001h, 001h, 002h
         DB 004h, 004h, 009h, 011h, 012h, 024h, 048h, 048h, 090h, 020h
         DB 040h, 040h, 080h, 060h, 018h, 006h, 001h, 0A8h, 057h, 001h
         DB 07Eh, 080h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 080h
         DB 060h, 018h, 006h, 001h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 001h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 040h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 080h, 060h, 018h, 006h, 001h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 001h, 001h, 002h, 004h, 004h
         DB 008h, 010h, 011h, 022h, 044h, 044h, 088h, 010h, 02Ch, 023h
         DB 040h, 080h, 000h, 000h, 000h, 000h, 000h, 000h, 001h, 002h
         DB 004h, 008h, 010h, 020h, 040h, 080h, 0A8h, 050h, 007h, 0F8h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 080h, 060h, 018h, 006h, 001h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 001h, 001h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 080h, 060h
         DB 018h, 026h, 041h, 042h, 084h, 008h, 010h, 010h, 020h, 040h
         DB 080h, 080h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 0C1h, 032h, 00Ch, 008h, 010h, 020h, 040h, 080h, 0AFh, 049h
         DB 01Fh, 0E0h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 080h, 060h, 018h, 006h, 001h, 000h, 000h, 000h, 03Fh, 040h
         DB 040h, 080h, 080h, 000h, 000h, 0C0h, 030h, 00Ch, 003h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 0FFh, 080h, 040h, 020h, 010h
         DB 008h, 004h, 002h, 001h, 000h, 001h, 002h, 004h, 008h, 010h
         DB 020h, 040h, 080h, 0B6h, 042h, 07Fh, 080h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 001h, 001h, 002h, 004h, 004h, 008h
         DB 090h, 060h, 019h, 007h, 0FFh, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 0C0h, 030h, 00Ch, 003h, 000h
         DB 001h, 001h, 002h, 002h, 004h, 004h, 008h, 008h, 010h, 010h
         DB 020h, 0E0h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 080h, 0BEh, 02Fh, 0E0h, 018h, 006h, 001h, 000h, 000h, 000h
         DB 001h, 001h, 002h, 004h, 004h, 008h, 011h, 012h, 022h, 044h
         DB 044h, 088h, 00Ch, 013h, 010h, 020h, 040h, 040h, 080h, 080h
         DB 000h, 000h, 0FFh, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 001h, 000h, 000h, 0E0h, 01Eh, 001h
         DB 0D4h, 02Dh, 080h, 060h, 058h, 096h, 021h, 020h, 041h, 041h
         DB 082h, 082h, 002h, 004h, 004h, 008h, 008h, 008h, 010h, 010h
         DB 0E0h, 020h, 020h, 040h, 040h, 080h, 080h, 080h, 0FFh, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 001h, 006h, 018h, 060h
         DB 080h, 060h, 018h, 006h, 001h, 0E0h, 01Fh, 0D7h, 028h, 080h
         DB 080h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 0FFh, 000h, 000h, 000h, 001h, 006h, 018h, 060h, 098h
         DB 006h, 001h, 000h, 001h, 006h, 018h, 060h, 080h, 080h, 0EEh
         DB 00Dh, 0F8h, 006h, 001h, 060h, 098h, 006h, 001h, 000h, 001h
         DB 006h, 098h, 060h, 080h, 0F5h, 007h, 080h, 060h, 018h, 006h
         DB 098h, 060h, 080h, 000h
lnfqy:   DB 041h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FAh
         DB 0F5h, 0FAh, 0F5h, 0EFh, 0FFh, 0EBh, 0F5h, 0EAh, 0F5h, 0EAh
         DB 0BFh, 0FFh, 0FFh, 0FFh, 0FFh, 0EBh, 0BEh, 0FFh, 07Fh, 0FFh
         DB 07Fh, 0FFh, 0FFh, 0FFh, 0EBh, 0FDh, 0FEh, 0FDh, 0FEh, 0FDh
         DB 0EAh, 0F5h, 0EFh, 0FDh, 0FFh, 055h, 0FFh, 055h, 0FFh, 055h
         DB 0FFh, 055h, 0BFh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h
         DB 0AAh, 055h, 02Ah, 015h, 002h, 001h, 0BFh, 043h, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 05Fh, 0BFh, 06Fh, 0BFh, 05Fh
         DB 0FFh, 0DFh, 0FFh, 0DFh, 0EFh, 0FFh, 0FFh, 07Fh, 0F7h, 0FFh
         DB 0F7h, 0FBh, 0FDh, 0FEh, 0F5h, 0FAh, 0F5h, 0FAh, 0F5h, 0FAh
         DB 0F5h, 0EAh, 0D5h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0FFh
         DB 055h, 0FFh, 055h, 0FFh, 055h, 0FFh, 055h, 0FFh, 055h, 0FFh
         DB 055h, 0AFh, 055h, 0ABh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh
         DB 055h, 0AAh, 055h, 02Ah, 005h, 0BDh, 044h, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0F3h, 0EFh, 0DFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0EFh, 0FFh, 0EEh, 0DDh, 0FEh, 0FDh, 0FAh, 0F5h
         DB 0FAh, 0F5h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h
         DB 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h
         DB 0AAh, 055h, 0AAh, 055h, 0EAh, 055h, 0EAh, 055h, 0FAh, 055h
         DB 0FAh, 055h, 0FAh, 055h, 0FEh, 055h, 0BFh, 055h, 0AAh, 055h
         DB 0AAh, 055h, 0AAh, 055h, 01Fh, 0BCh, 043h, 0FFh, 0FFh, 0FFh
         DB 0F5h, 0FFh, 0F5h, 0FFh, 0FDh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FDh, 0EAh, 0D5h, 0BFh, 07Fh, 0EAh, 0FFh, 0AAh, 0FFh
         DB 0AAh, 07Fh, 0AAh, 07Fh, 0AAh, 05Fh, 0AAh, 055h, 0AAh, 055h
         DB 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h
         DB 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h
         DB 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0FBh, 055h
         DB 0AAh, 055h, 0ABh, 058h, 0BDh, 042h, 0C0h, 0F0h, 0FCh, 07Eh
         DB 0FFh, 057h, 0FFh, 055h, 0FFh, 0FDh, 0FFh, 0FFh, 05Fh, 0B9h
         DB 075h, 0EAh, 07Fh, 0AAh, 0FFh, 0AAh, 0FFh, 0AAh, 0FFh, 0AAh
         DB 0FFh, 0AAh, 0F7h, 0AAh, 0D5h, 0AAh, 055h, 0AAh, 055h, 0AAh
         DB 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh
         DB 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh
         DB 055h, 0AAh, 057h, 0AFh, 05Fh, 0BFh, 0FFh, 0FFh, 0FEh, 0F8h
         DB 0E0h, 080h, 0C2h, 039h, 080h, 0C0h, 0F0h, 0F8h, 0FCh, 0FEh
         DB 0FEh, 0FFh, 0FFh, 0EBh, 0FDh, 0AFh, 0FDh, 0AAh, 0FDh, 0AAh
         DB 0FDh, 0AAh, 0FDh, 0AAh, 0FFh, 0AAh, 0FFh, 0AAh, 0FFh, 0AAh
         DB 07Fh, 0EAh, 07Fh, 0AAh, 07Fh, 0AAh, 05Fh, 0AAh, 057h, 0AAh
         DB 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h
lkacz:   DB 0AAh, 055h, 0AAh, 05Fh, 0BFh, 07Fh, 0FEh, 0FCh, 0F8h, 0F0h
         DB 0E0h, 0C0h, 0CFh, 02Ah, 080h, 0C0h, 0C0h, 0E0h, 060h, 0F0h
         DB 070h, 0B8h, 058h, 0ACh, 054h, 0ACh, 056h, 0AAh, 0D6h, 0AAh
         DB 0DEh, 0AEh, 0DDh, 0ABh, 0D5h, 0ABh, 0F5h, 0AAh, 0D6h, 0AAh
         DB 0D6h, 0AAh, 056h
lnhfh:   DB 0ACh, 054h, 0ACh, 050h, 0A8h, 058h, 0B0h, 050h, 0A0h, 060h
         DB 0C0h, 0C0h, 080h, 000h
ljojo:   DB 02Dh, 001h, 001h, 001h, 001h, 001h, 001h, 001h, 001h, 001h
         DB 003h, 003h, 003h, 003h, 003h, 003h, 003h, 003h, 003h, 003h
         DB 003h, 002h, 003h, 002h, 003h, 002h, 003h, 002h, 003h, 002h
         DB 003h
lkama:   DB 002h, 003h, 002h, 003h, 002h, 003h, 002h, 001h, 001h, 001h
         DB 001h, 001h, 001h, 001h, 001h, 0B5h, 051h, 001h, 001h, 002h
         DB 003h, 002h, 005h, 006h, 005h, 00Ah, 00Dh, 00Ah, 00Dh, 01Bh
         DB 015h, 01Bh, 015h, 02Bh, 035h, 02Bh, 035h, 06Fh, 057h, 07Fh
         DB 07Fh, 07Fh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FDh, 0FDh, 0FFh, 0FFh, 0FFh, 0DFh, 0DFh, 0DFh, 0FDh
         DB 0FAh, 0FAh, 0FAh, 0FAh, 0FDh, 0FFh, 0FFh, 0FFh, 07Fh, 05Bh
         DB 057h, 0ABh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh
         DB 055h, 0AAh, 055h, 0AAh, 055h, 0ABh, 057h, 0AFh, 05Fh, 0AFh
         DB 05Fh, 0AFh, 0DFh, 0BBh, 0FBh, 0FBh, 0FFh, 0FFh, 09Dh, 063h
         DB 001h, 001h, 003h, 003h, 007h, 005h, 00Eh, 00Dh, 01Ah, 015h
         DB 02Ah, 035h, 06Ah, 055h, 06Ah, 0D5h, 0AAh, 0D5h, 0AAh, 055h
         DB 0AAh, 055h, 0ABh, 055h, 0ABh, 055h, 0BFh, 055h, 0BFh, 055h
         DB 0FFh, 055h, 0FFh, 055h, 0FFh, 0F5h, 0FFh, 0F5h, 0FFh, 0FDh
         DB 0FFh, 0FDh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FEh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0DFh, 0DFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 07Fh
         DB 0FDh, 07Ah, 0FAh, 0FAh, 0FDh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0EFh, 0EFh, 0FFh, 0BFh, 0BFh, 0FFh, 0FFh, 0FFh, 0FFh, 090h
         DB 070h, 001h, 003h, 003h, 007h, 00Fh, 00Fh, 01Fh, 03Fh, 03Fh
         DB 07Fh, 07Bh, 0F7h, 0F7h, 0EFh, 0FFh, 0FFh, 0FFh, 0FFh, 055h
         DB 0FFh, 055h, 0FFh, 055h, 0FFh, 055h, 0BFh, 055h, 0BFh, 055h
         DB 0BFh, 055h, 0FFh, 055h, 0BFh, 055h, 0FFh, 055h, 0FFh, 055h
         DB 0FFh, 055h, 0FFh, 055h, 0FFh, 055h, 0FFh, 055h, 0FFh, 055h
         DB 0FFh, 055h, 0FFh, 055h, 0FFh, 055h, 0FFh, 055h, 0FFh, 0D5h
         DB 0FFh, 0D5h, 0FFh, 0F7h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FDh, 0FFh
         DB 0FFh, 0FDh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FEh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 085h, 07Bh, 001h, 003h, 007h, 007h, 00Fh
         DB 01Fh, 03Fh, 03Fh, 07Fh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FEh, 0FDh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 07Fh, 0FFh
         DB 07Fh, 0FFh, 07Fh, 0FFh, 05Fh, 0FFh, 057h, 0FFh, 057h, 0FFh
         DB 057h, 0FFh, 057h, 0FFh, 057h, 0FFh, 057h, 0FFh, 057h, 0FFh
         DB 057h, 0FFh, 057h, 0FFh, 05Fh, 0FFh, 05Fh, 0FFh, 05Fh, 0FFh
         DB 07Fh, 0FFh, 07Fh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 07Fh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FEh, 0FEh, 0FEh, 0FEh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FEh
         DB 0FDh, 0FAh, 0FDh, 0FAh, 0F5h, 0EAh, 0D5h, 0AAh, 07Ch, 084h
         DB 001h, 003h, 007h, 00Fh, 01Fh, 03Fh, 07Fh, 07Fh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FEh, 0FDh, 0FBh, 0FBh, 0F7h, 0F7h, 0F9h
         DB 0FFh, 0FEh, 0FDh, 0FAh, 0F9h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0F3h, 0CBh, 0DBh, 0BBh
         DB 0BBh, 077h, 077h, 06Fh, 04Fh, 03Fh, 0FFh, 0FFh, 0BFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0BFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0BFh, 05Fh, 05Fh, 0BFh
         DB 0FEh, 0FEh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 09Fh, 06Fh, 0F7h, 0F7h, 0F7h, 0F7h, 06Fh, 09Fh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FEh, 0FDh, 0FAh
         DB 0D5h, 0AEh, 057h, 0AFh, 05Fh, 0BFh, 05Fh, 0BFh, 05Fh, 0BFh
         DB 07Fh, 0FEh, 074h, 08Ch, 001h, 002h, 005h, 00Fh, 01Fh, 03Fh
         DB 07Fh, 0FFh, 0FFh, 0FEh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0EEh
         DB 0DFh, 0FEh, 0FFh, 0CEh, 037h, 0F7h, 0EFh, 0EFh, 0DFh, 0BFh
         DB 07Fh, 0FFh, 0FFh, 07Fh, 07Fh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FEh, 0FFh
         DB 0FEh, 0FFh, 0FFh, 0FDh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 07Fh, 0BFh, 0BFh, 07Fh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0DFh, 0DFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FEh, 0FDh, 0EAh, 0D5h, 0AAh
         DB 075h, 0AAh, 075h, 0EAh, 0F5h, 0EAh, 0D5h, 0AAh, 0D5h, 0AAh
         DB 055h, 0AAh, 055h, 0AAh, 06Dh, 093h, 001h, 003h, 006h, 01Dh
         DB 02Ah, 055h, 0AAh, 055h, 0AAh, 055h, 0EAh, 0D5h, 0EAh, 0D5h
         DB 0AAh, 055h, 0AAh, 055h, 0EAh, 0D5h, 0AAh, 055h, 0ABh, 057h
         DB 0AFh, 05Fh, 0FFh, 0E3h, 0DBh, 0BBh, 077h, 06Fh, 01Fh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0DFh, 0AFh, 0AFh, 0DFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FEh, 0FDh, 0FAh, 0FDh, 0FAh, 0F5h, 0FAh, 0F5h, 0FAh, 0FDh
         DB 0FEh, 0FDh, 0FEh, 0FFh, 0FEh, 0FDh, 0FEh, 0FDh, 0FEh, 0FDh
         DB 0FAh, 0F5h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h
         DB 0ABh, 057h, 0AFh, 05Fh, 0BFh, 055h, 0AAh, 055h, 0AAh, 057h
         DB 0ABh, 05Fh, 0AFh, 067h, 099h, 001h, 003h, 00Eh, 015h, 02Ah
         DB 0D5h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0ABh
         DB 057h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0ABh
         DB 057h, 0AFh, 05Fh, 0FEh, 0FEh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FAh
         DB 0F5h, 0EAh, 0D5h, 0EAh, 0D5h, 0EAh, 0F5h, 0EAh, 0D5h, 0EAh
         DB 0D5h, 0AAh, 0D5h, 0AAh, 055h, 0AAh, 055h, 0AAh, 0D5h, 0AAh
         DB 0D5h, 0AAh, 0D5h, 0FAh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FEh, 0FDh, 0FBh
         DB 0FBh, 0BBh, 0FDh, 0FEh, 0FFh, 0FFh, 0EFh, 0FFh, 0FFh, 0FFh
         DB 0FDh, 0FAh, 0F5h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh
         DB 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh
         DB 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0BAh
         DB 07Fh, 0BFh, 07Fh, 0FFh, 0FFh, 0FFh, 0F7h, 0FFh, 0FFh, 0FEh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 062h, 09Eh
         DB 001h, 006h, 00Dh, 03Ah, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh
         DB 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 05Dh, 0FFh, 0FFh, 0FAh
         DB 0F5h, 0EAh, 055h, 0BAh, 055h, 0AAh, 055h, 0AAh, 0FDh, 0FAh
         DB 0FDh, 09Fh, 05Fh, 0BFh, 07Fh, 0FFh, 0FFh, 0FFh, 0EFh, 0DFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0F7h, 0EBh, 0D5h, 0AAh, 055h, 0AAh
         DB 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh
         DB 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0ABh
         DB 055h, 0ABh, 05Fh, 0BFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0F7h, 0FFh, 0FFh, 0EFh, 0FFh, 0FFh, 0FFh, 0FFh, 03Fh, 03Fh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FEh, 0FDh, 0FDh, 03Eh, 0DFh, 0EFh
         DB 0EFh, 0EFh, 0DFh, 03Fh, 0FFh, 0FFh, 0FFh, 0EAh, 0D5h, 0AAh
         DB 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh
         DB 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh
         DB 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0ABh, 057h, 0AFh
         DB 0FFh, 0FCh, 0FBh, 0FBh, 0BCh, 05Fh, 0BFh, 0FFh, 07Fh, 0B3h
         DB 073h, 0FFh, 0FFh, 0FFh, 07Fh, 0FFh, 0DFh, 0FFh, 05Eh, 0A2h
         DB 003h, 00Eh, 035h, 06Ah, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh
         DB 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh
         DB 057h, 0AFh, 057h, 0AFh, 05Fh, 0BFh, 05Fh, 0BFh, 055h, 0AAh
         DB 055h, 0AAh, 055h, 0AFh, 05Fh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FEh, 0FDh, 0FAh, 0F5h, 0AAh
         DB 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh
         DB 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0ABh
         DB 07Fh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FBh
         DB 0F5h, 0FBh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0EFh, 0FFh, 0FFh, 0FFh, 07Fh, 0BFh
         DB 0BFh, 07Fh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FAh
         DB 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh
         DB 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh
         DB 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh
         DB 055h, 0AAh, 0FDh, 0FEh, 0FFh, 0FEh, 07Fh, 07Fh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 000h
lndwo:   DB 011h, 001h, 001h, 001h, 001h, 002h, 002h, 002h, 002h, 002h
         DB 00Ch, 030h, 0C0h, 080h, 080h, 09Fh, 0F0h, 01Fh, 0DFh, 028h
         DB 018h, 024h, 05Ah, 042h, 042h, 099h, 0A5h, 0A5h, 0BDh, 081h
         DB 099h, 081h, 081h, 0A5h, 081h, 081h, 081h, 081h, 081h, 081h
         DB 081h, 081h, 081h, 081h, 081h, 081h, 081h, 081h, 081h, 099h
         DB 099h, 099h, 099h, 099h, 099h, 0FFh, 099h, 0FFh, 018h, 018h
         DB 0E8h, 011h, 080h, 080h, 080h, 080h, 040h, 040h, 040h, 040h
         DB 040h, 030h, 00Ch, 003h, 001h, 001h, 0F9h, 00Fh, 0F8h, 000h
lndxx:   DB 000h, 000h, 000h, 000h, 000h, 080h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 001h, 0C0h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 002h, 0A0h, 000h, 000h, 000h, 000h, 000h, 000h, 006h, 0B0h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 01Dh, 0B8h, 000h, 000h
         DB 000h, 000h, 01Dh, 0B8h, 01Dh, 0B8h, 000h, 000h, 000h, 000h
         DB 03Dh, 0DEh, 025h, 0D2h, 03Dh, 0DEh, 0F9h, 09Fh, 08Fh, 0F1h
         DB 08Bh, 0D1h, 0F9h, 09Fh
lndyb:   DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 001h, 0C0h, 003h, 0E0h, 003h, 0E0h, 003h, 0E0h
         DB 001h, 0C0h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 001h, 000h
         DB 00Ah, 010h, 000h, 000h, 012h, 080h, 003h, 0E0h, 00Bh, 0F0h
         DB 003h, 0E0h, 001h, 0A8h, 010h, 040h, 000h, 088h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 010h, 008h, 002h, 080h, 001h, 0C0h, 005h, 000h, 00Dh, 0D8h
         DB 011h, 060h, 007h, 052h, 005h, 0A8h, 002h, 080h, 020h, 020h
         DB 000h, 004h, 000h, 000h, 002h, 020h, 000h, 000h, 000h, 000h
         DB 010h, 008h, 000h, 080h, 000h, 040h, 00Bh, 020h, 002h, 044h
         DB 004h, 0A0h, 021h, 048h, 005h, 041h, 012h, 090h, 008h, 040h
         DB 040h, 000h, 002h, 020h, 000h, 002h, 000h, 000h, 000h, 000h
         DB 020h, 004h, 000h, 080h, 000h, 000h, 090h, 000h, 004h, 040h
         DB 008h, 012h, 001h, 000h, 042h, 0A1h, 004h, 000h, 001h, 040h
         DB 040h, 024h, 008h, 000h, 000h, 000h, 000h, 020h, 004h, 000h
         DB 000h, 000h, 000h, 080h, 000h, 000h, 020h, 002h, 008h, 000h
         DB 000h, 000h, 001h, 009h, 000h, 000h, 080h, 000h, 000h, 000h
         DB 000h, 000h, 001h, 000h, 000h, 001h, 010h, 000h, 000h, 000h
         DB 000h, 010h
lndxz:   DB 025h, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h
         DB 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 055h
         DB 0AAh, 055h, 0AAh, 055h, 0AAh, 055h, 0AAh, 0FDh, 0FEh, 0FFh
         DB 0FEh, 07Fh, 07Fh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 000h, 011h, 001h
         DB 001h, 001h, 001h, 002h, 002h, 002h, 002h, 002h, 00Ch, 030h
         DB 0C0h, 080h, 080h, 09Fh, 0F0h, 01Fh, 0DFh, 028h, 018h, 024h
         DB 05Ah, 042h, 042h, 099h, 0A5h, 0A5h, 0BDh, 081h, 099h, 081h
         DB 081h, 0A5h, 081h, 081h, 081h, 081h, 081h, 081h, 081h, 081h
         DB 081h, 081h, 081h, 081h, 081h, 081h, 081h, 099h, 000h, 000h
         DB 000h, 000h, 001h, 000h, 000h, 001h, 010h, 000h
END