;*********************************************************************************************************
; 
; Autogenerated by DizAssembler:
;   https://github.com/codenjoyme/8080-emulator/blob/master/src/main/java/spec/assembler/DizAssembler.java
; From: src/main/resources/lik/apps/piton2/piton2.rks
; In test: DizAssemblerTest.testDizAssembly()
; 
;*********************************************************************************************************

            CPU  8080
            .ORG 00000h
lxbxllno    EQU 00A80h
lrsxgpcg    EQU 0100Fh
lvxmeuod    EQU 01080h
ltalrels    EQU 0110Eh
lyaatwlk    EQU 01323h
lzsuiukd    EQU 0180Fh
lprwrggc    EQU 01900h
looghdvy    EQU 02080h
lijrfyrf    EQU 02377h
ljkstxuy    EQU 03FFFh
lvoqjupx    EQU 05700h
llzjlkhp    EQU 0C037h
lupzithy    EQU 0C427h
lzjlqnow    EQU 0F700h
lxazvrue    EQU 0FF00h
lkukegic    EQU 0FF01h
lskutmav    EQU 0FF02h
lnsvwlwm    EQU 0FF03h
lobivtnf    EQU 0FFE0h
ljybtgvj    EQU 0FFFFh
ljbtkier:   LXI SP,ljkstxuy
            LXI H,lxbxllno
            LXI D,lcoawozk
            CALL lsynifuc
            MVI C,02Eh
ljwuhikq:   LXI D,lqseukct
            CALL lsynifuc
            DCR C
            JNZ ljwuhikq
            LXI D,lcoawozk
            CALL lsynifuc
            MVI C,01Fh
            CALL llzjlkhp
            LXI B,00000h
            LXI H,lppgvblo
            CALL lbjlpyky
lxdzuteq:   CALL lituwyhq
            ORA A
            JNZ lxdzuteq
lmgeivld:   CALL lyasxdhf
            CALL lituwyhq
            CPI 020h
            JNZ lmgeivld
            MVI C,01Fh
            CALL llzjlkhp
            LXI B,lrsxgpcg
            LXI H,lucffbmp
            CALL lbjlpyky
            DCR B
            LDA laoanbtj
            MOV D,A
            JMP lfhddubg
liktdmbw:   CALL lituwyhq
            ORA A
            JNZ liktdmbw
lnuxhqgw:   CALL lituwyhq
            ORA A
            JZ lnuxhqgw
            CPI 020h
            JZ lgbbogiy
            INR D
            MOV A,D
            CPI 01Ah
            CZ lvvsceik
lfhddubg:   MOV A,D
            CALL ltnevjsn
            JMP liktdmbw
lvvsceik:   MVI D,011h
            RET
lgbbogiy:   MOV A,D
            STA laoanbtj
            SUI 010h
            LXI H,lvoqjupx
            LXI B,lzjlqnow
lqsxpipc:   DAD B
            DCR A
            JNZ lqsxpipc
            SHLD lgpujtlr
            MVI C,01Fh
            CALL llzjlkhp
            LXI B,00000h
            LXI H,ldoyjmeq
            CALL lbjlpyky
            MVI D,01Dh
lwiwzmfc:   LXI H,lulxyobh
            CALL lbjlpyky
            DCR D
            JNZ lwiwzmfc
            LXI H,lmvahrch
            CALL lbjlpyky
            LXI H,lvxmeuod
            SHLD lmserllq
            SHLD ltdvemzw
            LXI H,00100h
            SHLD lbzuhbwh
            LXI H,0030Fh
            SHLD lvxmeuod
            LXI B,lxbxllno
            DAD B
            MVI M,002h
            LXI B,lzsuiukd
            MVI A,00Dh
            CALL ltnevjsn
            MVI A,004h
            STA ltsbpshz
            STA lukjcloj
            MVI A,001h
            STA lankvafj
            XRA A
            STA lrrtjqtg
            STA llxrvvrl
            STA lunomphh
            STA llstmnje
            LXI B,0031Fh
            MVI A,043h
            CALL ltnevjsn
            MVI D,005h
lwkmusje:   PUSH D
            CALL lcfqozbw
            POP D
            DCR D
            JNZ lwkmusje
lmaktkzm:   CALL lyasxdhf
            MOV A,H
            ANI 03Fh
            CZ lcfqozbw
            CALL lyasxdhf
            MOV A,L
            ANI 07Fh
            CZ lgnesuqs
            CALL lyasxdhf
            MOV A,H
            ANI 07Fh
            CZ ltqumykh
            CALL lyasxdhf
            MOV A,H
            CPI 034h
            PUSH PSW
            CZ lmizcaeb
            POP PSW
            ANI 03Fh
            CPI 020h
            CZ lqzyhhcb
            LDA lrrtjqtg
            ORA A
            JNZ ljqsdyat
            CALL luqzinon
            STA ltsbpshz
            LHLD lmserllq
            CALL lcljjwdq
            PUSH H
            CALL lyeqepbb
            MVI A,002h
            CALL ltnevjsn
            LDA ltsbpshz
            POP H
            CALL lgalcmhb
            DAD B
            PUSH H
            LXI B,lxbxllno
            DAD B
            MOV A,M
            STA lbauxvjc
            MVI M,002h
            POP H
            PUSH H
            CALL liapzlds
            MOV A,D
            CALL ltnevjsn
            POP D
            LHLD lmserllq
            INX H
            INX H
            PUSH D
            LXI D,looghdvy
            CALL lupzithy
            POP D
            CZ lbffjazj
            SHLD lmserllq
            CALL lfqpxpkr
            LDA ltcdsebr
            ORA A
            CNZ lllliqiw
lojwbwdc:   LDA lukjcloj
            ORA A
            JZ livpflrb
            DCR A
            STA lukjcloj
            CALL lvdqvbxb
            JMP lrukfxzu
lllliqiw:   LDA lunomphh
            ORA A
            RZ
            MVI D,01Bh
            LDA ltsbpshz
            CPI 004h
            JZ lzylginz
            CPI 010h
            JZ lzylginz
            INR D
lzylginz:   CALL lxkarroy
            MVI D,000h
            CALL lxkarroy
            XRA A
            STA ltcdsebr
            RET
lxkarroy:   LHLD lmserllq
            CALL lcljjwdq
            MVI E,003h
lydkowom:   LDA ltsbpshz
            CALL lgalcmhb
            DAD B
            PUSH H
            LXI B,lxbxllno
            DAD B
            MOV A,M
            ORA A
            JZ lkjvapdt
            CPI 040h
            JZ lkjvapdt
            CPI 00Bh
            JZ lkjvapdt
            JMP lnxerczk
lkjvapdt:   MVI M,000h
            POP H
            PUSH H
            CALL lyeqepbb
            MOV A,D
            CALL ltnevjsn
            LXI H,00100h
            CALL lptsgivv
            POP H
            DCR E
            JNZ lydkowom
            RET
lqzyhhcb:   LDA lankvafj
            CPI 00Fh
            RZ
            LDA llstmnje
            ORA A
            RNZ
            MVI A,001h
            STA llstmnje
            MVI A,043h
            JMP llgphqyw
ljqsdyat:   LDA lrrtjqtg
            DCR A
            STA lrrtjqtg
            CALL lgrxwlui
            CALL laeizxau
            JZ lnxerczk
            JMP lojwbwdc
lgnesuqs:   MVI A,003h
llgphqyw:   STA lqxyzygu
            JMP lqeazsea
lmizcaeb:   LDA llxrvvrl
            ORA A
            RNZ
            CALL lglguydd
            MVI A,042h
            STA llxrvvrl
            JMP llgphqyw
lcfqozbw:   MVI A,00Bh
            JMP llgphqyw
ltqumykh:   MVI A,040h
            JMP llgphqyw
lvdqvbxb:   LXI H,lhwxxacs
            MOV A,M
            ADI 001h
            DAA
            MOV M,A
            DCX H
            MOV A,M
            ACI 000h
            DAA
            MOV M,A
            JMP lqmfsusz
lgrxwlui:   LXI H,lhwxxacs
            MOV A,M
            ADI 099h
            DAA
            MOV M,A
            DCX H
            CPI 099h
            MOV A,M
            JNZ ltnuqffs
            ADI 099h
            DAA
ltnuqffs:   MOV M,A
            JMP lqmfsusz
laeizxau:   LXI H,lbzuhbwh
            XRA A
            ORA M
            INX H
            ORA M
            RET
lbffjazj:   LXI H,lvxmeuod
            RET
lqeazsea:   CALL lglguydd
            PUSH H
            LXI B,lxbxllno
            DAD B
            MOV A,M
            ORA A
            POP H
            JNZ lcfqozbw
            PUSH H
            LXI B,lxbxllno
            DAD B
            LDA lqxyzygu
            MOV M,A
            POP H
            CALL lyeqepbb
            LDA lqxyzygu
            CALL ltnevjsn
            RET
lglguydd:   CALL lyasxdhf
            MOV A,H
            ANI 007h
            CPI 006h
            JC lvxcagdk
            SUI 006h
lvxcagdk:   MOV H,A
            RET
livpflrb:   LHLD ltdvemzw
            PUSH H
            INX H
            INX H
            PUSH D
            LXI D,looghdvy
            CALL lupzithy
            POP D
            CZ lbffjazj
            SHLD ltdvemzw
            POP H
            CALL lcljjwdq
            PUSH H
            LXI B,lxbxllno
            DAD B
            MVI M,000h
            POP H
            CALL lyeqepbb
            XRA A
            CALL ltnevjsn
lrukfxzu:   CALL ldqqxamb
            LDA lbauxvjc
            CPI 00Bh
            JZ lhbhszwc
            CPI 040h
            JZ lhugysax
            CPI 042h
            JZ lxczkwck
            CPI 043h
            JZ lckasxrx
            ORA A
            JZ lmaktkzm
            JMP lnxerczk
lckasxrx:   XRA A
            STA llstmnje
            LDA lankvafj
            INR A
            STA lankvafj
            ADI 002h
            MOV B,A
            MVI C,01Fh
            MVI A,043h
            CALL ltnevjsn
            JMP lmaktkzm
lxczkwck:   MVI A,001h
            STA lunomphh
            LXI B,0011Fh
            MVI A,042h
            CALL ltnevjsn
            JMP lmaktkzm
lhugysax:   MVI A,014h
            STA lrrtjqtg
            XRA A
            STA lbauxvjc
            LXI B,0011Fh
            CALL ltnevjsn
            LDA lankvafj
            MVI D,002h
ljihpwio:   CPI 001h
            JZ lpwcunuz
            DCR A
            MOV E,A
            ADI 003h
            MOV B,A
            MVI C,01Fh
            XRA A
            CALL ltnevjsn
            MOV A,E
            DCR D
            STA lankvafj
            JNZ ljihpwio
lpwcunuz:   LDA lunomphh
            ORA A
            JZ lmaktkzm
            XRA A
            STA lunomphh
            STA llxrvvrl
            JMP lmaktkzm
lhbhszwc:   LDA lukjcloj
            MOV B,A
            LDA lankvafj
            ADD B
            STA lukjcloj
            JMP lmaktkzm
ldqqxamb:   LHLD lgpujtlr
lptsgivv:   DCX H
            MOV A,H
            ORA L
            JNZ lptsgivv
            RET
liapzlds:   CALL lyeqepbb
            MVI D,00Ch
            LDA ltsbpshz
            CPI 080h
            RZ
            INR D
            CPI 004h
            RZ
            INR D
            CPI 040h
            RZ
            INR D
            RET
luqzinon:   CALL lituwyhq
            ORA A
            CZ lbaunmmc
            CPI 004h
            RZ
            CPI 010h
            RZ
            CPI 040h
            RZ
            CPI 080h
            RZ
            CPI 020h
            CZ lhleuufi
            LDA ltsbpshz
            RET
lbaunmmc:   PUSH PSW
            XRA A
            STA llprpmqg
            POP PSW
            RET
lhleuufi:   LDA llprpmqg
            ORA A
            RNZ
            INR A
            STA llprpmqg
            STA ltcdsebr
            RET
lgalcmhb:   LXI B,00020h
            CPI 004h
            RZ
            LXI B,lobivtnf
            CPI 010h
            RZ
            LXI B,ljybtgvj
            CPI 080h
            RZ
            LXI B,00001h
            RET
lcljjwdq:   PUSH D
            MOV E,M
            INX H
            MOV D,M
            XCHG
            POP D
            RET
lfqpxpkr:   MOV M,E
            INX H
            MOV M,D
            RET
lqmfsusz:   PUSH B
            PUSH H
            LXI B,lprwrggc
            LXI H,lbzuhbwh
            MOV A,M
            CALL ldmixyfb
            INX H
            MOV A,M
            CALL ldmixyfb
            POP H
            POP B
            RET
ldmixyfb:   PUSH D
            MOV E,A
            RRC
            RRC
            RRC
            RRC
            CALL lnfqtgfg
            MOV D,A
            MOV A,E
            CALL lnfqtgfg
            MOV E,A
            MOV A,D
            SUI 020h
            CALL ltnevjsn
            INR B
            MOV A,E
            SUI 020h
            CALL ltnevjsn
            INR B
            POP D
            RET
lnfqtgfg:   ANI 00Fh
            CPI 00Ah
            JC lbiktlen
            ADI 007h
lbiktlen:   ADI 030h
            RET
lyeqepbb:   PUSH H
            DAD H
            DAD H
            DAD H
            MOV B,H
            POP H
            MOV A,L
            ANI 01Fh
            MOV C,A
            RET
lsynifuc:   MVI B,020h
lrrihecn:   LDAX D
            MOV M,A
            INX H
            INX D
            DCR B
            JNZ lrrihecn
            RET
lituwyhq:   PUSH B
            MVI A,091h
            STA lnsvwlwm
            MVI A,0FBh
            STA lkukegic
            LDA lxazvrue
            ANI 03Fh
            MOV B,A
            LDA lskutmav
            ANI 003h
            RRC
            RRC
            ORA B
            CMA
            POP B
            RET
lyasxdhf:   LHLD lazkqjdw
            MVI C,010h
lnvvxvjg:   MOV A,H
            DAD H
            ANI 060h
            JPE lvynrvtr
            INX H
lvynrvtr:   DCR C
            JNZ lnvvxvjg
            SHLD lazkqjdw
            RET
ltnevjsn:   PUSH H
            PUSH D
            PUSH B
            PUSH PSW
            MOV A,C
            RLC
            RLC
            RLC
            MOV L,A
            MOV A,B
            ADI 090h
            MOV H,A
            POP PSW
            PUSH PSW
            XCHG
            LXI B,lnxcsrae
            MVI H,000h
            MOV L,A
            DAD H
            DAD H
            DAD H
            DAD B
            MVI B,008h
ldmbirfx:   MOV A,M
            STAX D
            INX H
            INX D
            DCR B
            JNZ ldmbirfx
            POP PSW
            POP B
            POP D
            POP H
            RET
lnxerczk:   LXI B,ltalrels
            LXI H,lmnxbnrz
            CALL lbjlpyky
            MVI D,006h
ldqukvhi:   LXI H,ljybtgvj
lbaelmii:   CALL lituwyhq
            CPI 020h
            JZ ljbtkier
            DCX H
            MOV A,H
            ORA L
            JNZ lbaelmii
            DCR D
            JNZ ldqukvhi
            JMP ljbtkier
lbjlpyky:   MOV A,M
            ORA A
            RZ
            CPI 00Ah
            JZ lxbhpjic
            CPI 00Bh
            JZ ldzgiyrc
            SUI 020h
            JZ lwxlulrh
            CALL ltnevjsn
lwxlulrh:   INR B
ldmyisjr:   INX H
            JMP lbjlpyky
lxbhpjic:   MVI B,000h
            INR C
            JMP ldmyisjr
ldzgiyrc:   INR B
            INR B
            INR B
            INR B
            JMP ldmyisjr

lcoawozk:   DB 041h, 041h, 041h, 041h, 041h, 041h, 041h, 041h, 041h, 041h
            DB 041h, 041h, 041h, 041h, 041h, 041h, 041h, 041h, 041h, 041h
            DB 041h, 041h, 041h, 041h, 041h, 041h, 041h, 041h, 041h, 041h
            DB 041h, 041h
lqseukct:   DB 041h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
            DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
            DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
            DB 041h, 041h
lppgvblo:   DB 00Ah, 00Ah, 00Ah, 00Bh, 00Bh, 00Bh, 00Bh, 00Bh, 020h, 020h
            DB 024h, 025h, 026h, 00Ah, 00Bh, 00Bh, 00Bh, 00Bh, 00Bh, 020h
            DB 020h, 027h, 028h, 029h, 00Ah, 00Ah, 00Bh, 00Bh, 00Bh, 00Bh
            DB 05Eh, 045h, 052h, 04Eh, 04Fh, 057h, 043h, 059h, 020h, 02Ah
            DB 020h, 031h, 039h, 038h, 038h, 00Ah, 00Ah, 00Ah, 00Ah, 00Ah
            DB 00Ah, 00Bh, 023h, 023h, 023h, 023h, 023h, 023h, 023h, 020h
            DB 023h, 020h, 020h, 020h, 020h, 020h, 023h, 020h, 023h, 023h
            DB 023h, 023h, 023h, 023h, 023h, 020h, 023h, 023h, 023h, 023h
            DB 023h, 023h, 023h, 020h, 023h, 020h, 020h, 020h, 020h, 020h
            DB 023h, 00Ah, 00Bh, 023h, 020h, 020h, 020h, 020h, 020h, 023h
            DB 020h, 023h, 020h, 020h, 020h, 020h, 023h, 023h, 020h, 020h
            DB 020h, 020h, 023h, 020h, 020h, 020h, 020h, 023h, 020h, 020h
            DB 020h, 020h, 020h, 023h, 020h, 023h, 020h, 020h, 020h, 020h
            DB 020h, 023h, 00Ah, 00Bh, 023h, 020h, 020h, 020h, 020h, 020h
            DB 023h, 020h, 023h, 020h, 020h, 020h, 023h, 020h, 023h, 020h
            DB 020h, 020h, 020h, 023h, 020h, 020h, 020h, 020h, 023h, 020h
            DB 020h, 020h, 020h, 020h, 023h, 020h, 023h, 020h, 020h, 020h
            DB 020h, 020h, 023h, 00Ah, 00Bh, 023h, 020h, 020h, 020h, 020h
            DB 020h, 023h, 020h, 023h, 020h, 020h, 023h, 020h, 020h, 023h
            DB 020h, 020h, 020h, 020h, 023h, 020h, 020h, 020h, 020h, 023h
            DB 020h, 020h, 020h, 020h, 020h, 023h, 020h, 023h, 023h, 023h
            DB 023h, 023h, 023h, 023h, 00Ah, 00Bh, 023h, 023h, 020h, 020h
            DB 020h, 020h, 023h, 020h, 023h, 020h, 023h, 020h, 020h, 023h
            DB 023h, 020h, 020h, 020h, 020h, 023h, 023h, 020h, 020h, 020h
            DB 023h, 023h, 023h, 020h, 020h, 020h, 023h, 020h, 023h, 023h
            DB 020h, 020h, 020h, 020h, 023h, 00Ah, 00Bh, 023h, 023h, 020h
            DB 020h, 020h, 020h, 023h, 020h, 023h, 023h, 020h, 020h, 020h
            DB 023h, 023h, 020h, 020h, 020h, 020h, 023h, 023h, 020h, 020h
            DB 020h, 023h, 023h, 023h, 020h, 020h, 020h, 023h, 020h, 023h
            DB 023h, 020h, 020h, 020h, 020h, 023h, 00Ah, 00Bh, 023h, 023h
            DB 020h, 020h, 020h, 020h, 023h, 020h, 023h, 020h, 020h, 020h
            DB 020h, 023h, 023h, 020h, 020h, 020h, 020h, 023h, 023h, 020h
            DB 020h, 020h, 023h, 023h, 023h, 020h, 020h, 020h, 023h, 020h
            DB 023h, 023h, 020h, 020h, 020h, 020h, 023h, 00Ah, 00Bh, 023h
            DB 023h, 020h, 020h, 020h, 020h, 023h, 020h, 023h, 020h, 020h
            DB 020h, 020h, 023h, 023h, 020h, 020h, 020h, 020h, 023h, 023h
            DB 020h, 020h, 020h, 023h, 023h, 023h, 023h, 023h, 023h, 023h
            DB 020h, 023h, 023h, 020h, 020h, 020h, 020h, 023h, 00Ah, 00Ah
            DB 00Ah, 00Ah, 00Ah, 00Bh, 00Bh, 00Bh, 020h, 020h, 020h, 022h
            DB 022h, 022h, 022h, 022h, 022h, 02Dh, 020h, 02Bh, 020h, 022h
            DB 022h, 022h, 022h, 022h, 022h, 022h, 020h, 00Ah, 00Bh, 00Bh
            DB 00Bh, 020h, 020h, 022h, 020h, 020h, 020h, 020h, 020h, 020h
            DB 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h
            DB 020h, 022h, 00Ah, 00Bh, 00Bh, 00Bh, 020h, 020h, 022h, 020h
            DB 060h, 020h, 020h, 020h, 060h, 020h, 020h, 020h, 060h, 020h
            DB 020h, 020h, 060h, 020h, 020h, 020h, 022h, 00Ah, 00Bh, 00Bh
            DB 00Bh, 020h, 020h, 022h, 020h, 020h, 020h, 060h, 020h, 020h
            DB 020h, 060h, 020h, 020h, 020h, 060h, 020h, 020h, 020h, 060h
            DB 020h, 022h, 00Ah, 00Bh, 00Bh, 00Bh, 020h, 020h, 022h, 020h
            DB 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h
            DB 020h, 020h, 020h, 020h, 020h, 020h, 022h, 00Ah, 00Bh, 00Bh
            DB 00Bh, 020h, 020h, 020h, 022h, 022h, 022h, 022h, 022h, 022h
            DB 022h, 022h, 022h, 022h, 022h, 022h, 022h, 022h, 022h, 022h
            DB 022h, 020h, 000h
ldoyjmeq:   DB 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h
            DB 021h, 021h, 021h, 021h, 021h, 020h, 020h, 020h, 020h, 044h
            DB 04Ch, 049h, 04Eh, 041h, 020h, 030h, 030h, 030h, 030h, 020h
            DB 020h, 020h, 020h, 021h, 021h, 021h, 021h, 021h, 021h, 021h
            DB 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 00Ah, 000h
lulxyobh:   DB 021h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h
            DB 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h
            DB 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h
            DB 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h
            DB 020h, 020h, 020h, 020h, 020h, 020h, 020h, 021h, 00Ah, 000h
lmvahrch:   DB 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h
            DB 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h
            DB 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h
            DB 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h
            DB 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 00Ah, 000h
lucffbmp:   DB 053h, 04Bh, 04Fh, 052h, 04Fh, 053h, 054h, 058h, 020h, 02Dh
            DB 020h, 031h, 000h
lmnxbnrz:   DB 064h, 064h, 064h, 064h, 064h, 064h, 064h, 064h, 064h, 064h
            DB 064h, 064h, 064h, 064h, 064h, 064h, 064h, 00Ah, 00Bh, 00Bh
            DB 00Bh, 020h, 020h, 064h, 064h, 049h, 047h, 052h, 041h, 064h
            DB 04Fh, 04Bh, 04Fh, 04Eh, 05Eh, 045h, 04Eh, 041h, 064h, 064h
            DB 00Ah, 00Bh, 00Bh, 00Bh, 020h, 020h, 064h, 064h, 064h, 064h
            DB 064h, 064h, 064h, 064h, 064h, 064h, 064h, 064h, 064h, 064h
            DB 064h, 064h, 064h, 000h
lazkqjdw:   DB 001h, 000h
lbzuhbwh:   DB 000h
lhwxxacs:   DB 006h
lmserllq:   DB 096h, 079h
ltdvemzw:   DB 08Ch, 079h
lukjcloj:   DB 000h
ltsbpshz:   DB 080h
lbauxvjc:   DB 041h
lqxyzygu:   DB 00Bh
lrrtjqtg:   DB 000h
lgpujtlr:   DB 000h, 00Fh
laoanbtj:   DB 014h
llprpmqg:   DB 000h
ltcdsebr:   DB 000h
llxrvvrl:   DB 000h
lunomphh:   DB 000h
lankvafj:   DB 001h
llstmnje:   DB 000h, 0CDh, 0E1h, 00Dh, 0D6h, 031h, 0FAh, 000h, 081h, 0FEh
            DB 003h, 032h, 012h, 010h, 0FAh, 02Fh, 008h, 021h
lnxcsrae:   DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 0FFh, 0FFh
            DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 03Ch, 042h, 099h, 0BDh
            DB 0BDh, 099h, 042h, 03Ch, 049h, 092h, 024h, 0C9h, 092h, 024h
            DB 049h, 092h, 000h, 000h, 001h, 002h, 007h, 007h, 00Fh, 00Fh
            DB 07Fh, 083h, 005h, 009h, 0F1h, 0F3h, 0F3h, 0F7h, 01Eh, 026h
            DB 04Ch, 094h, 0E8h, 0C8h, 0CCh, 094h, 01Eh, 01Eh, 03Ch, 03Dh
            DB 07Ah, 07Ch, 0F8h, 0F0h, 0F7h, 0FFh, 0FFh, 0F7h, 0F7h, 0F7h
            DB 0FBh, 0F1h, 0A2h, 042h, 081h, 082h, 084h, 0C8h, 0D0h, 0E0h
            DB 03Ch, 042h, 099h, 0A1h, 0A1h, 099h, 042h, 03Ch, 008h, 004h
            DB 003h, 0C3h, 0FCh, 03Ch, 044h, 022h, 018h, 024h, 042h, 081h
            DB 0A5h, 081h, 042h, 03Ch, 038h, 044h, 092h, 081h, 081h, 092h
            DB 044h, 038h, 03Ch, 042h, 081h, 0A5h, 081h, 042h, 024h, 018h
            DB 01Ch, 022h, 049h, 081h, 081h, 049h, 022h, 01Ch, 0FEh, 082h
            DB 082h, 082h, 0C2h, 0C2h, 0C2h, 0FEh, 008h, 008h, 018h, 018h
            DB 018h, 018h, 018h, 018h, 07Eh, 002h, 002h, 0FEh, 080h, 0C0h
            DB 0C2h, 0FEh, 03Eh, 002h, 002h, 03Eh, 002h, 006h, 006h, 0FEh
            DB 082h, 082h, 0C2h, 0C2h, 0FEh, 006h, 006h, 006h, 0FCh, 080h
            DB 080h, 0FEh, 002h, 006h, 086h, 0FEh, 0F8h, 0C8h, 0C0h, 0FEh
            DB 082h, 086h, 086h, 0FEh, 0FEh, 082h, 002h, 002h, 006h, 006h
            DB 006h, 006h, 07Ch, 064h, 064h, 0FEh, 082h, 0C2h, 0C2h, 0FEh
            DB 0FEh, 082h, 0C2h, 0C2h, 0FEh, 006h, 026h, 03Eh, 000h, 018h
            DB 018h, 000h, 000h, 018h, 018h, 000h, 000h, 000h, 030h, 048h
            DB 085h, 002h, 000h, 000h, 008h, 004h, 008h, 010h, 020h, 020h
            DB 010h, 008h, 000h, 000h, 000h, 07Eh, 07Eh, 000h, 000h, 000h
            DB 000h, 000h, 000h, 000h, 000h, 038h, 038h, 038h, 0FEh, 006h
            DB 002h, 01Eh, 030h, 030h, 000h, 030h, 09Eh, 092h, 092h, 0F2h
            DB 096h, 0D6h, 0D6h, 0DEh, 03Eh, 022h, 022h, 0FEh, 082h, 0C2h
            DB 0C2h, 0C2h, 0F8h, 080h, 080h, 0FEh, 082h, 0C2h, 0C2h, 0FEh
            DB 084h, 084h, 084h, 084h, 0C4h, 0C4h, 0C4h, 0FEh, 01Ch, 014h
            DB 024h, 044h, 064h, 064h, 064h, 0FEh, 0FEh, 080h, 080h, 0F8h
            DB 0C0h, 0C0h, 0C0h, 0FEh, 0FEh, 092h, 092h, 0D2h, 0D2h, 0FEh
            DB 010h, 020h, 0FEh, 080h, 080h, 080h, 0C0h, 0C0h, 0C0h, 0C0h
            DB 044h, 044h, 044h, 038h, 044h, 0C6h, 0C6h, 0C6h, 082h, 086h
            DB 08Ah, 092h, 0A2h, 0C6h, 086h, 086h, 038h, 082h, 086h, 08Ah
            DB 092h, 0A6h, 0C6h, 086h, 088h, 088h, 088h, 0FEh, 0C2h, 0C2h
            DB 0C2h, 0C2h, 00Eh, 012h, 012h, 012h, 026h, 026h, 066h, 066h
            DB 082h, 0C6h, 0AAh, 092h, 0C2h, 0C2h, 0C2h, 0C2h, 082h, 082h
            DB 082h, 0FEh, 0C2h, 0C2h, 0C2h, 0C2h, 0FEh, 08Eh, 086h, 082h
            DB 082h, 082h, 082h, 0FEh, 0FEh, 082h, 082h, 082h, 0C2h, 0C2h
            DB 0C2h, 0C2h, 0FEh, 082h, 0C2h, 0C2h, 0FEh, 026h, 046h, 086h
            DB 0FEh, 082h, 0C2h, 0C2h, 0FEh, 080h, 080h, 080h, 0FEh, 080h
            DB 080h, 080h, 0C0h, 0C0h, 0C0h, 0FEh, 0FEh, 010h, 010h, 010h
            DB 018h, 018h, 018h, 018h, 082h, 082h, 0C2h, 0C2h, 0FEh, 002h
            DB 062h, 07Eh, 054h, 054h, 054h, 07Ch, 054h, 0D6h, 0D6h, 0D6h
            DB 0FCh, 084h, 084h, 0FEh, 0C2h, 0C2h, 0C2h, 0FEh, 080h, 080h
            DB 080h, 0FEh, 082h, 0C2h, 0C2h, 0FEh, 082h, 082h, 082h, 0FAh
            DB 08Ah, 0CAh, 0CAh, 0FAh, 0F8h, 018h, 018h, 07Eh, 002h, 006h
            DB 086h, 0FEh, 092h, 092h, 092h, 092h, 0D2h, 0D2h, 0D2h, 0FEh
            DB 0FEh, 082h, 002h, 01Eh, 006h, 006h, 086h, 0FEh, 094h, 094h
            DB 094h, 094h, 0D4h, 0D4h, 0D4h, 0FEh, 082h, 082h, 0C2h, 0C2h
            DB 0FEh, 006h, 006h, 006h, 0C0h, 040h, 040h, 07Eh, 042h, 062h
            DB 062h, 07Eh, 03Ch, 066h, 0E7h, 0FFh, 0AFh, 007h, 056h, 03Ch
            DB 018h, 018h, 018h, 018h, 018h, 018h, 018h, 018h, 042h, 024h
            DB 024h, 042h, 0A5h, 099h, 0A5h, 07Eh, 004h, 068h, 09Eh, 081h
            DB 081h, 082h, 044h, 038h, 000h, 000h, 000h, 000h, 000h, 000h
            DB 000h, 000h, 008h, 018h, 018h, 0FFh, 0FFh, 000h, 000h, 000h
            DB 000h, 000h, 0FFh, 0FFh, 000h, 000h, 0FFh, 0FFh, 000h, 000h
            DB 0FFh, 0FFh, 000h, 000h, 0FFh, 0FFh, 0FFh, 0FFh, 000h, 000h
            DB 0FFh, 0FFh, 000h, 000h, 0FFh, 0FFh, 000h, 000h, 0FFh, 0FFh
            DB 000h, 000h, 004h, 010h, 07Eh, 0B0h, 077h, 021h, 002h, 010h
            DB 07Eh, 03Ch, 027h, 077h, 0E1h, 0C9h, 006h, 004h
END