;*********************************************************************************************************
; 
; Autogenerated by DizAssembler:
;   https://github.com/codenjoyme/8080-emulator/blob/master/src/main/java/spec/assembler/DizAssembler.java
; From: src/main/resources/lik/apps/piton2/piton2.rks
; In test: DizAssemblerTest.testDizAssembly()
; 
;*********************************************************************************************************

         CPU  8080
         .ORG 00000h
ljyua    EQU 00A80h
lndxp    EQU 0100Fh
lkamq    EQU 01080h
lnqat    EQU 0110Eh
lnhhj    EQU 01323h
lndsr    EQU 0180Fh
lkahv    EQU 01900h
lkfau    EQU 02080h
lnisl    EQU 02377h
lnjsg    EQU 03FFFh
lkytv    EQU 05700h
lgozx    EQU 0C037h
lgpdp    EQU 0C427h
ldsyd    EQU 0F700h
ldstf    EQU 0FF00h
ldgqd    EQU 0FF01h
lhlrv    EQU 0FF02h
lgzot    EQU 0FF03h
ldsss    EQU 0FFE0h
lgwbe    EQU 0FFFFh
ljyzh:   LXI SP,lnjsg
         LXI H,ljyua
         LXI D,ljmxo
         CALL lnrwr
         MVI C,02Eh
lnonh:   LXI D,ljmwy
         CALL lnrwr
         DCR C
         JNZ lnonh
         LXI D,ljmxo
         CALL lnrwr
         MVI C,01Fh
         CALL lgozx
         LXI B,00000h
         LXI H,ljmxn
         CALL lnrmu
ljvob:   CALL ljjkj
         ORA A
         JNZ ljvob
lnfrt:   CALL ljmkn
         CALL ljjkj
         CPI 020h
         JNZ lnfrt
         MVI C,01Fh
         CALL lgozx
         LXI B,lndxp
         LXI H,ljvpa
         CALL lnrmu
         DCR B
         LDA ljykn
         MOV D,A
         JMP lnomv
ljvwf:   CALL ljjkj
         ORA A
         JNZ ljvwf
lnfir:   CALL ljjkj
         ORA A
         JZ lnfir
         CPI 020h
         JZ ljymn
         INR D
         MOV A,D
         CPI 01Ah
         CZ ljjsn
lnomv:   MOV A,D
         CALL lnoor
         JMP ljvwf
ljjsn:   MVI D,011h
         RET
ljymn:   MOV A,D
         STA ljykn
         SUI 010h
         LXI H,lkytv
         LXI B,ldsyd
ljvym:   DAD B
         DCR A
         JNZ ljvym
         SHLD lnosf
         MVI C,01Fh
         CALL lgozx
         LXI B,00000h
         LXI H,lnovr
         CALL lnrmu
         MVI D,01Dh
ljvme:   LXI H,ljyqp
         CALL lnrmu
         DCR D
         JNZ ljvme
         LXI H,lnrmd
         CALL lnrmu
         LXI H,lkamq
         SHLD ljjjq
         SHLD lncig
         LXI H,00100h
         SHLD lnfja
         LXI H,0030Fh
         SHLD lkamq
         LXI B,ljyua
         DAD B
         MVI M,002h
         LXI B,lndsr
         MVI A,00Dh
         CALL lnoor
         MVI A,004h
         STA lnrsz
         STA ljmrh
         MVI A,001h
         STA ljjgr
         XRA A
         STA ljjqn
         STA lnfgb
         STA ljvjt
         STA lnoij
         LXI B,0031Fh
         MVI A,043h
         CALL lnoor
         MVI D,005h
lnfrw:   PUSH D
         CALL lncjh
         POP D
         DCR D
         JNZ lnfrw
ljvls:   CALL ljmkn
         MOV A,H
         ANI 03Fh
         CZ lncjh
         CALL ljmkn
         MOV A,L
         ANI 07Fh
         CZ lncrh
         CALL ljmkn
         MOV A,H
         ANI 07Fh
         CZ ljvvd
         CALL ljmkn
         MOV A,H
         CPI 034h
         PUSH PSW
         CZ lnchl
         POP PSW
         ANI 03Fh
         CPI 020h
         CZ lncju
         LDA ljjqn
         ORA A
         JNZ ljvyf
         CALL lncqx
         STA lnrsz
         LHLD ljjjq
         CALL ljjig
         PUSH H
         CALL lncvh
         MVI A,002h
         CALL lnoor
         LDA lnrsz
         POP H
         CALL lncte
         DAD B
         PUSH H
         LXI B,ljyua
         DAD B
         MOV A,M
         STA lnfpx
         MVI M,002h
         POP H
         PUSH H
         CALL lnrxf
         MOV A,D
         CALL lnoor
         POP D
         LHLD ljjjq
         INX H
         INX H
         PUSH D
         LXI D,lkfau
         CALL lgpdp
         POP D
         CZ ljyor
         SHLD ljjjq
         CALL ljvyk
         LDA lnrjd
         ORA A
         CNZ ljyww
lnchj:   LDA ljmrh
         ORA A
         JZ ljjiu
         DCR A
         STA ljmrh
         CALL ljmiz
         JMP ljvyi
ljyww:   LDA ljvjt
         ORA A
         RZ
         MVI D,01Bh
         LDA lnrsz
         CPI 004h
         JZ ljjuw
         CPI 010h
         JZ ljjuw
         INR D
ljjuw:   CALL lnruw
         MVI D,000h
         CALL lnruw
         XRA A
         STA lnrjd
         RET
lnruw:   LHLD ljjjq
         CALL ljjig
         MVI E,003h
lnrla:   LDA lnrsz
         CALL lncte
         DAD B
         PUSH H
         LXI B,ljyua
         DAD B
         MOV A,M
         ORA A
         JZ ljyne
         CPI 040h
         JZ ljyne
         CPI 00Bh
         JZ ljyne
         JMP lncsj
ljyne:   MVI M,000h
         POP H
         PUSH H
         CALL lncvh
         MOV A,D
         CALL lnoor
         LXI H,00100h
         CALL lnfil
         POP H
         DCR E
         JNZ lnrla
         RET
lncju:   LDA ljjgr
         CPI 00Fh
         RZ
         LDA lnoij
         ORA A
         RNZ
         MVI A,001h
         STA lnoij
         MVI A,043h
         JMP ljmjp
ljvyf:   LDA ljjqn
         DCR A
         STA ljjqn
         CALL lnrnx
         CALL ljyyn
         JZ lncsj
         JMP lnchj
lncrh:   MVI A,003h
ljmjp:   STA ljvtp
         JMP ljvnx
lnchl:   LDA lnfgb
         ORA A
         RNZ
         CALL lnomy
         MVI A,042h
         STA lnfgb
         JMP ljmjp
lncjh:   MVI A,00Bh
         JMP ljmjp
ljvvd:   MVI A,040h
         JMP ljmjp
ljmiz:   LXI H,ljvms
         MOV A,M
         ADI 001h
         DAA
         MOV M,A
         DCX H
         MOV A,M
         ACI 000h
         DAA
         MOV M,A
         JMP ljypi
lnrnx:   LXI H,ljvms
         MOV A,M
         ADI 099h
         DAA
         MOV M,A
         DCX H
         CPI 099h
         MOV A,M
         JNZ ljvmb
         ADI 099h
         DAA
ljvmb:   MOV M,A
         JMP ljypi
ljyyn:   LXI H,lnfja
         XRA A
         ORA M
         INX H
         ORA M
         RET
ljyor:   LXI H,lkamq
         RET
ljvnx:   CALL lnomy
         PUSH H
         LXI B,ljyua
         DAD B
         MOV A,M
         ORA A
         POP H
         JNZ lncjh
         PUSH H
         LXI B,ljyua
         DAD B
         LDA ljvtp
         MOV M,A
         POP H
         CALL lncvh
         LDA ljvtp
         CALL lnoor
         RET
lnomy:   CALL ljmkn
         MOV A,H
         ANI 007h
         CPI 006h
         JC lnfie
         SUI 006h
lnfie:   MOV H,A
         RET
ljjiu:   LHLD lncig
         PUSH H
         INX H
         INX H
         PUSH D
         LXI D,lkfau
         CALL lgpdp
         POP D
         CZ ljyor
         SHLD lncig
         POP H
         CALL ljjig
         PUSH H
         LXI B,ljyua
         DAD B
         MVI M,000h
         POP H
         CALL lncvh
         XRA A
         CALL lnoor
ljvyi:   CALL ljymx
         LDA lnfpx
         CPI 00Bh
         JZ lnrnz
         CPI 040h
         JZ ljjlj
         CPI 042h
         JZ ljjii
         CPI 043h
         JZ ljjuq
         ORA A
         JZ ljvls
         JMP lncsj
ljjuq:   XRA A
         STA lnoij
         LDA ljjgr
         INR A
         STA ljjgr
         ADI 002h
         MOV B,A
         MVI C,01Fh
         MVI A,043h
         CALL lnoor
         JMP ljvls
ljjii:   MVI A,001h
         STA ljvjt
         LXI B,0011Fh
         MVI A,042h
         CALL lnoor
         JMP ljvls
ljjlj:   MVI A,014h
         STA ljjqn
         XRA A
         STA lnfpx
         LXI B,0011Fh
         CALL lnoor
         LDA ljjgr
         MVI D,002h
ljmvj:   CPI 001h
         JZ ljmjb
         DCR A
         MOV E,A
         ADI 003h
         MOV B,A
         MVI C,01Fh
         XRA A
         CALL lnoor
         MOV A,E
         DCR D
         STA ljjgr
         JNZ ljmvj
ljmjb:   LDA ljvjt
         ORA A
         JZ ljvls
         XRA A
         STA ljvjt
         STA lnfgb
         JMP ljvls
lnrnz:   LDA ljmrh
         MOV B,A
         LDA ljjgr
         ADD B
         STA ljmrh
         JMP ljvls
ljymx:   LHLD lnosf
lnfil:   DCX H
         MOV A,H
         ORA L
         JNZ lnfil
         RET
lnrxf:   CALL lncvh
         MVI D,00Ch
         LDA lnrsz
         CPI 080h
         RZ
         INR D
         CPI 004h
         RZ
         INR D
         CPI 040h
         RZ
         INR D
         RET
lncqx:   CALL ljjkj
         ORA A
         CZ lnfsc
         CPI 004h
         RZ
         CPI 010h
         RZ
         CPI 040h
         RZ
         CPI 080h
         RZ
         CPI 020h
         CZ lnrli
         LDA lnrsz
         RET
lnfsc:   PUSH PSW
         XRA A
         STA ljmhl
         POP PSW
         RET
lnrli:   LDA ljmhl
         ORA A
         RNZ
         INR A
         STA ljmhl
         STA lnrjd
         RET
lncte:   LXI B,00020h
         CPI 004h
         RZ
         LXI B,ldsss
         CPI 010h
         RZ
         LXI B,lgwbe
         CPI 080h
         RZ
         LXI B,00001h
         RET
ljjig:   PUSH D
         MOV E,M
         INX H
         MOV D,M
         XCHG
         POP D
         RET
ljvyk:   MOV M,E
         INX H
         MOV M,D
         RET
ljypi:   PUSH B
         PUSH H
         LXI B,lkahv
         LXI H,lnfja
         MOV A,M
         CALL ljvmc
         INX H
         MOV A,M
         CALL ljvmc
         POP H
         POP B
         RET
ljvmc:   PUSH D
         MOV E,A
         RRC
         RRC
         RRC
         RRC
         CALL lnfhu
         MOV D,A
         MOV A,E
         CALL lnfhu
         MOV E,A
         MOV A,D
         SUI 020h
         CALL lnoor
         INR B
         MOV A,E
         SUI 020h
         CALL lnoor
         INR B
         POP D
         RET
lnfhu:   ANI 00Fh
         CPI 00Ah
         JC ljvzt
         ADI 007h
ljvzt:   ADI 030h
         RET
lncvh:   PUSH H
         DAD H
         DAD H
         DAD H
         MOV B,H
         POP H
         MOV A,L
         ANI 01Fh
         MOV C,A
         RET
lnrwr:   MVI B,020h
ljvxh:   LDAX D
         MOV M,A
         INX H
         INX D
         DCR B
         JNZ ljvxh
         RET
ljjkj:   PUSH B
         MVI A,091h
         STA lgzot
         MVI A,0FBh
         STA ldgqd
         LDA ldstf
         ANI 03Fh
         MOV B,A
         LDA lhlrv
         ANI 003h
         RRC
         RRC
         ORA B
         CMA
         POP B
         RET
ljmkn:   LHLD ljmkk
         MVI C,010h
lnoll:   MOV A,H
         DAD H
         ANI 060h
         JPE lnoyn
         INX H
lnoyn:   DCR C
         JNZ lnoll
         SHLD ljmkk
         RET
lnoor:   PUSH H
         PUSH D
         PUSH B
         PUSH PSW
         MOV A,C
         RLC
         RLC
         RLC
         MOV L,A
         MOV A,B
         ADI 090h
         MOV H,A
         POP PSW
         PUSH PSW
         XCHG
         LXI B,ljytt
         MVI H,000h
         MOV L,A
         DAD H
         DAD H
         DAD H
         DAD B
         MVI B,008h
lnrov:   MOV A,M
         STAX D
         INX H
         INX D
         DCR B
         JNZ lnrov
         POP PSW
         POP B
         POP D
         POP H
         RET
lncsj:   LXI B,lnqat
         LXI H,ljmkg
         CALL lnrmu
         MVI D,006h
lnrzc:   LXI H,lgwbe
ljjwq:   CALL ljjkj
         CPI 020h
         JZ ljyzh
         DCX H
         MOV A,H
         ORA L
         JNZ ljjwq
         DCR D
         JNZ lnrzc
         JMP ljyzh
lnrmu:   MOV A,M
         ORA A
         RZ
         CPI 00Ah
         JZ ljvwq
         CPI 00Bh
         JZ lnrme
         SUI 020h
         JZ lncku
         CALL lnoor
lncku:   INR B
ljyxk:   INX H
         JMP lnrmu
ljvwq:   MVI B,000h
         INR C
         JMP ljyxk
lnrme:   INR B
         INR B
         INR B
         INR B
         JMP ljyxk

ljmxo:   DB 041h, 041h, 041h, 041h, 041h, 041h, 041h, 041h, 041h, 041h
         DB 041h, 041h, 041h, 041h, 041h, 041h, 041h, 041h, 041h, 041h
         DB 041h, 041h, 041h, 041h, 041h, 041h, 041h, 041h, 041h, 041h
         DB 041h, 041h
ljmwy:   DB 041h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 041h, 041h
ljmxn:   DB 00Ah, 00Ah, 00Ah, 00Bh, 00Bh, 00Bh, 00Bh, 00Bh, 020h, 020h
         DB 024h, 025h, 026h, 00Ah, 00Bh, 00Bh, 00Bh, 00Bh, 00Bh, 020h
         DB 020h, 027h, 028h, 029h, 00Ah, 00Ah, 00Bh, 00Bh, 00Bh, 00Bh
         DB 05Eh, 045h, 052h, 04Eh, 04Fh, 057h, 043h, 059h, 020h, 02Ah
         DB 020h, 031h, 039h, 038h, 038h, 00Ah, 00Ah, 00Ah, 00Ah, 00Ah
         DB 00Ah, 00Bh, 023h, 023h, 023h, 023h, 023h, 023h, 023h, 020h
         DB 023h, 020h, 020h, 020h, 020h, 020h, 023h, 020h, 023h, 023h
         DB 023h, 023h, 023h, 023h, 023h, 020h, 023h, 023h, 023h, 023h
         DB 023h, 023h, 023h, 020h, 023h, 020h, 020h, 020h, 020h, 020h
         DB 023h, 00Ah, 00Bh, 023h, 020h, 020h, 020h, 020h, 020h, 023h
         DB 020h, 023h, 020h, 020h, 020h, 020h, 023h, 023h, 020h, 020h
         DB 020h, 020h, 023h, 020h, 020h, 020h, 020h, 023h, 020h, 020h
         DB 020h, 020h, 020h, 023h, 020h, 023h, 020h, 020h, 020h, 020h
         DB 020h, 023h, 00Ah, 00Bh, 023h, 020h, 020h, 020h, 020h, 020h
         DB 023h, 020h, 023h, 020h, 020h, 020h, 023h, 020h, 023h, 020h
         DB 020h, 020h, 020h, 023h, 020h, 020h, 020h, 020h, 023h, 020h
         DB 020h, 020h, 020h, 020h, 023h, 020h, 023h, 020h, 020h, 020h
         DB 020h, 020h, 023h, 00Ah, 00Bh, 023h, 020h, 020h, 020h, 020h
         DB 020h, 023h, 020h, 023h, 020h, 020h, 023h, 020h, 020h, 023h
         DB 020h, 020h, 020h, 020h, 023h, 020h, 020h, 020h, 020h, 023h
         DB 020h, 020h, 020h, 020h, 020h, 023h, 020h, 023h, 023h, 023h
         DB 023h, 023h, 023h, 023h, 00Ah, 00Bh, 023h, 023h, 020h, 020h
         DB 020h, 020h, 023h, 020h, 023h, 020h, 023h, 020h, 020h, 023h
         DB 023h, 020h, 020h, 020h, 020h, 023h, 023h, 020h, 020h, 020h
         DB 023h, 023h, 023h, 020h, 020h, 020h, 023h, 020h, 023h, 023h
         DB 020h, 020h, 020h, 020h, 023h, 00Ah, 00Bh, 023h, 023h, 020h
         DB 020h, 020h, 020h, 023h, 020h, 023h, 023h, 020h, 020h, 020h
         DB 023h, 023h, 020h, 020h, 020h, 020h, 023h, 023h, 020h, 020h
         DB 020h, 023h, 023h, 023h, 020h, 020h, 020h, 023h, 020h, 023h
         DB 023h, 020h, 020h, 020h, 020h, 023h, 00Ah, 00Bh, 023h, 023h
         DB 020h, 020h, 020h, 020h, 023h, 020h, 023h, 020h, 020h, 020h
         DB 020h, 023h, 023h, 020h, 020h, 020h, 020h, 023h, 023h, 020h
         DB 020h, 020h, 023h, 023h, 023h, 020h, 020h, 020h, 023h, 020h
         DB 023h, 023h, 020h, 020h, 020h, 020h, 023h, 00Ah, 00Bh, 023h
         DB 023h, 020h, 020h, 020h, 020h, 023h, 020h, 023h, 020h, 020h
         DB 020h, 020h, 023h, 023h, 020h, 020h, 020h, 020h, 023h, 023h
         DB 020h, 020h, 020h, 023h, 023h, 023h, 023h, 023h, 023h, 023h
         DB 020h, 023h, 023h, 020h, 020h, 020h, 020h, 023h, 00Ah, 00Ah
         DB 00Ah, 00Ah, 00Ah, 00Bh, 00Bh, 00Bh, 020h, 020h, 020h, 022h
         DB 022h, 022h, 022h, 022h, 022h, 02Dh, 020h, 02Bh, 020h, 022h
         DB 022h, 022h, 022h, 022h, 022h, 022h, 020h, 00Ah, 00Bh, 00Bh
         DB 00Bh, 020h, 020h, 022h, 020h, 020h, 020h, 020h, 020h, 020h
         DB 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h
         DB 020h, 022h, 00Ah, 00Bh, 00Bh, 00Bh, 020h, 020h, 022h, 020h
         DB 060h, 020h, 020h, 020h, 060h, 020h, 020h, 020h, 060h, 020h
         DB 020h, 020h, 060h, 020h, 020h, 020h, 022h, 00Ah, 00Bh, 00Bh
         DB 00Bh, 020h, 020h, 022h, 020h, 020h, 020h, 060h, 020h, 020h
         DB 020h, 060h, 020h, 020h, 020h, 060h, 020h, 020h, 020h, 060h
         DB 020h, 022h, 00Ah, 00Bh, 00Bh, 00Bh, 020h, 020h, 022h, 020h
         DB 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h
         DB 020h, 020h, 020h, 020h, 020h, 020h, 022h, 00Ah, 00Bh, 00Bh
         DB 00Bh, 020h, 020h, 020h, 022h, 022h, 022h, 022h, 022h, 022h
         DB 022h, 022h, 022h, 022h, 022h, 022h, 022h, 022h, 022h, 022h
         DB 022h, 020h, 000h
lnovr:   DB 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h
         DB 021h, 021h, 021h, 021h, 021h, 020h, 020h, 020h, 020h, 044h
         DB 04Ch, 049h, 04Eh, 041h, 020h, 030h, 030h, 030h, 030h, 020h
         DB 020h, 020h, 020h, 021h, 021h, 021h, 021h, 021h, 021h, 021h
         DB 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 00Ah, 000h
ljyqp:   DB 021h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h
         DB 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h
         DB 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h
         DB 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h, 020h
         DB 020h, 020h, 020h, 020h, 020h, 020h, 020h, 021h, 00Ah, 000h
lnrmd:   DB 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h
         DB 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h
         DB 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h
         DB 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h
         DB 021h, 021h, 021h, 021h, 021h, 021h, 021h, 021h, 00Ah, 000h
ljvpa:   DB 053h, 04Bh, 04Fh, 052h, 04Fh, 053h, 054h, 058h, 020h, 02Dh
         DB 020h, 031h, 000h
ljmkg:   DB 064h, 064h, 064h, 064h, 064h, 064h, 064h, 064h, 064h, 064h
         DB 064h, 064h, 064h, 064h, 064h, 064h, 064h, 00Ah, 00Bh, 00Bh
         DB 00Bh, 020h, 020h, 064h, 064h, 049h, 047h, 052h, 041h, 064h
         DB 04Fh, 04Bh, 04Fh, 04Eh, 05Eh, 045h, 04Eh, 041h, 064h, 064h
         DB 00Ah, 00Bh, 00Bh, 00Bh, 020h, 020h, 064h, 064h, 064h, 064h
         DB 064h, 064h, 064h, 064h, 064h, 064h, 064h, 064h, 064h, 064h
         DB 064h, 064h, 064h, 000h
ljmkk:   DB 001h, 000h
lnfja:   DB 000h
ljvms:   DB 006h
ljjjq:   DB 096h, 079h
lncig:   DB 08Ch, 079h
ljmrh:   DB 000h
lnrsz:   DB 080h
lnfpx:   DB 041h
ljvtp:   DB 00Bh
ljjqn:   DB 000h
lnosf:   DB 000h, 00Fh
ljykn:   DB 014h
ljmhl:   DB 000h
lnrjd:   DB 000h
lnfgb:   DB 000h
ljvjt:   DB 000h
ljjgr:   DB 001h
lnoij:   DB 000h, 0CDh, 0E1h, 00Dh, 0D6h, 031h, 0FAh, 000h, 081h, 0FEh
         DB 003h, 032h, 012h, 010h, 0FAh, 02Fh, 008h, 021h
ljytt:   DB 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 0FFh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 03Ch, 042h, 099h, 0BDh
         DB 0BDh, 099h, 042h, 03Ch, 049h, 092h, 024h, 0C9h, 092h, 024h
         DB 049h, 092h, 000h, 000h, 001h, 002h, 007h, 007h, 00Fh, 00Fh
         DB 07Fh, 083h, 005h, 009h, 0F1h, 0F3h, 0F3h, 0F7h, 01Eh, 026h
         DB 04Ch, 094h, 0E8h, 0C8h, 0CCh, 094h, 01Eh, 01Eh, 03Ch, 03Dh
         DB 07Ah, 07Ch, 0F8h, 0F0h, 0F7h, 0FFh, 0FFh, 0F7h, 0F7h, 0F7h
         DB 0FBh, 0F1h, 0A2h, 042h, 081h, 082h, 084h, 0C8h, 0D0h, 0E0h
         DB 03Ch, 042h, 099h, 0A1h, 0A1h, 099h, 042h, 03Ch, 008h, 004h
         DB 003h, 0C3h, 0FCh, 03Ch, 044h, 022h, 018h, 024h, 042h, 081h
         DB 0A5h, 081h, 042h, 03Ch, 038h, 044h, 092h, 081h, 081h, 092h
         DB 044h, 038h, 03Ch, 042h, 081h, 0A5h, 081h, 042h, 024h, 018h
         DB 01Ch, 022h, 049h, 081h, 081h, 049h, 022h, 01Ch, 0FEh, 082h
         DB 082h, 082h, 0C2h, 0C2h, 0C2h, 0FEh, 008h, 008h, 018h, 018h
         DB 018h, 018h, 018h, 018h, 07Eh, 002h, 002h, 0FEh, 080h, 0C0h
         DB 0C2h, 0FEh, 03Eh, 002h, 002h, 03Eh, 002h, 006h, 006h, 0FEh
         DB 082h, 082h, 0C2h, 0C2h, 0FEh, 006h, 006h, 006h, 0FCh, 080h
         DB 080h, 0FEh, 002h, 006h, 086h, 0FEh, 0F8h, 0C8h, 0C0h, 0FEh
         DB 082h, 086h, 086h, 0FEh, 0FEh, 082h, 002h, 002h, 006h, 006h
         DB 006h, 006h, 07Ch, 064h, 064h, 0FEh, 082h, 0C2h, 0C2h, 0FEh
         DB 0FEh, 082h, 0C2h, 0C2h, 0FEh, 006h, 026h, 03Eh, 000h, 018h
         DB 018h, 000h, 000h, 018h, 018h, 000h, 000h, 000h, 030h, 048h
         DB 085h, 002h, 000h, 000h, 008h, 004h, 008h, 010h, 020h, 020h
         DB 010h, 008h, 000h, 000h, 000h, 07Eh, 07Eh, 000h, 000h, 000h
         DB 000h, 000h, 000h, 000h, 000h, 038h, 038h, 038h, 0FEh, 006h
         DB 002h, 01Eh, 030h, 030h, 000h, 030h, 09Eh, 092h, 092h, 0F2h
         DB 096h, 0D6h, 0D6h, 0DEh, 03Eh, 022h, 022h, 0FEh, 082h, 0C2h
         DB 0C2h, 0C2h, 0F8h, 080h, 080h, 0FEh, 082h, 0C2h, 0C2h, 0FEh
         DB 084h, 084h, 084h, 084h, 0C4h, 0C4h, 0C4h, 0FEh, 01Ch, 014h
         DB 024h, 044h, 064h, 064h, 064h, 0FEh, 0FEh, 080h, 080h, 0F8h
         DB 0C0h, 0C0h, 0C0h, 0FEh, 0FEh, 092h, 092h, 0D2h, 0D2h, 0FEh
         DB 010h, 020h, 0FEh, 080h, 080h, 080h, 0C0h, 0C0h, 0C0h, 0C0h
         DB 044h, 044h, 044h, 038h, 044h, 0C6h, 0C6h, 0C6h, 082h, 086h
         DB 08Ah, 092h, 0A2h, 0C6h, 086h, 086h, 038h, 082h, 086h, 08Ah
         DB 092h, 0A6h, 0C6h, 086h, 088h, 088h, 088h, 0FEh, 0C2h, 0C2h
         DB 0C2h, 0C2h, 00Eh, 012h, 012h, 012h, 026h, 026h, 066h, 066h
         DB 082h, 0C6h, 0AAh, 092h, 0C2h, 0C2h, 0C2h, 0C2h, 082h, 082h
         DB 082h, 0FEh, 0C2h, 0C2h, 0C2h, 0C2h, 0FEh, 08Eh, 086h, 082h
         DB 082h, 082h, 082h, 0FEh, 0FEh, 082h, 082h, 082h, 0C2h, 0C2h
         DB 0C2h, 0C2h, 0FEh, 082h, 0C2h, 0C2h, 0FEh, 026h, 046h, 086h
         DB 0FEh, 082h, 0C2h, 0C2h, 0FEh, 080h, 080h, 080h, 0FEh, 080h
         DB 080h, 080h, 0C0h, 0C0h, 0C0h, 0FEh, 0FEh, 010h, 010h, 010h
         DB 018h, 018h, 018h, 018h, 082h, 082h, 0C2h, 0C2h, 0FEh, 002h
         DB 062h, 07Eh, 054h, 054h, 054h, 07Ch, 054h, 0D6h, 0D6h, 0D6h
         DB 0FCh, 084h, 084h, 0FEh, 0C2h, 0C2h, 0C2h, 0FEh, 080h, 080h
         DB 080h, 0FEh, 082h, 0C2h, 0C2h, 0FEh, 082h, 082h, 082h, 0FAh
         DB 08Ah, 0CAh, 0CAh, 0FAh, 0F8h, 018h, 018h, 07Eh, 002h, 006h
         DB 086h, 0FEh, 092h, 092h, 092h, 092h, 0D2h, 0D2h, 0D2h, 0FEh
         DB 0FEh, 082h, 002h, 01Eh, 006h, 006h, 086h, 0FEh, 094h, 094h
         DB 094h, 094h, 0D4h, 0D4h, 0D4h, 0FEh, 082h, 082h, 0C2h, 0C2h
         DB 0FEh, 006h, 006h, 006h, 0C0h, 040h, 040h, 07Eh, 042h, 062h
         DB 062h, 07Eh, 03Ch, 066h, 0E7h, 0FFh, 0AFh, 007h, 056h, 03Ch
         DB 018h, 018h, 018h, 018h, 018h, 018h, 018h, 018h, 042h, 024h
         DB 024h, 042h, 0A5h, 099h, 0A5h, 07Eh, 004h, 068h, 09Eh, 081h
         DB 081h, 082h, 044h, 038h, 000h, 000h, 000h, 000h, 000h, 000h
         DB 000h, 000h, 008h, 018h, 018h, 0FFh, 0FFh, 000h, 000h, 000h
         DB 000h, 000h, 0FFh, 0FFh, 000h, 000h, 0FFh, 0FFh, 000h, 000h
         DB 0FFh, 0FFh, 000h, 000h, 0FFh, 0FFh, 0FFh, 0FFh, 000h, 000h
         DB 0FFh, 0FFh, 000h, 000h, 0FFh, 0FFh, 000h, 000h, 0FFh, 0FFh
         DB 000h, 000h, 004h, 010h, 07Eh, 0B0h, 077h, 021h, 002h, 010h
         DB 07Eh, 03Ch, 027h, 077h, 0E1h, 0C9h, 006h, 004h
END