;*********************************************************************************************************
; 
; Autogenerated by DizAssembler:
;   https://github.com/codenjoyme/8080-emulator/blob/master/src/main/java/spec/assembler/DizAssembler.java
; From: src/main/resources/lik/apps/reversi/reversi.rks
; In test: DizAssemblerTest.testDizAssembly()
; 
;*********************************************************************************************************

         CPU  8080
         .ORG 00000h
lnhdx    EQU 01C23h
lkxgk    EQU 04780h
lldcb    EQU 06800h
lknnt    EQU 0682Dh
lospl    EQU 0682Eh
logtt    EQU 06837h
llcpd    EQU 06838h
lknxt    EQU 06865h
loszl    EQU 06866h
logwj    EQU 06867h
llcrt    EQU 06868h
lkqor    EQU 06869h
lovqj    EQU 0686Ah
lojnh    EQU 0686Bh
lkzqz    EQU 0686Ch
lospp    EQU 0686Eh
logmn    EQU 0686Fh
llczd    EQU 06870h
lkqwb    EQU 06871h
lovxt    EQU 06872h
lojur    EQU 06873h
lkqmf    EQU 06879h
lovnx    EQU 0687Ah
lojkv    EQU 0687Bh
lldcd    EQU 06900h
lkzrn    EQU 0690Ch
lojvf    EQU 06913h
logul    EQU 06917h
lkzpb    EQU 0691Ch
lkqpj    EQU 06949h
losqh    EQU 0694Eh
lovyl    EQU 06952h
lkqmx    EQU 06959h
lknxv    EQU 06965h
lcasc    EQU 08FF1h
lgftu    EQU 08FF2h
lcjko    EQU 08FFCh
lbxhm    EQU 08FFDh
lcopl    EQU 09000h
lcllh    EQU 09234h
lcokn    EQU 09800h
lcoid    EQU 09910h
lgeey    EQU 09AB6h
lckxf    EQU 09B1Ch
lcstq    EQU 0A3C8h
lcszw    EQU 0AC80h
lcrif    EQU 0B834h
lgozx    EQU 0C037h
lgost    EQU 0C16Fh
lgozo    EQU 0C2B7h
lgozr    EQU 0C337h
ldkwn    EQU 0C438h
lgouq    EQU 0CAB7h
lgwbe    EQU 0FFFFh
ljyzh:   LXI H,lcopl
lnfuv:   MVI M,000h
         INX H
         MVI M,055h
         INX H
         MOV A,H
         CPI 0C0h
         JNZ lnfuv
         LXI H,lkakj
         LXI D,lcokn
ljjsz:   MOV B,M
         MOV A,B
         ORA A
         JZ lnctl
         INX H
         MOV A,M
         INX H
lnokv:   STAX D
         INX D
         DCR B
         JNZ lnokv
         JMP ljjsz
lnctl:   LXI H,lnouv
lnrnl:   MOV A,M
         ORA A
         JZ ljypp
         STA lcasc
         INX H
         STA lgftu
         INX H
         PUSH H
         CALL lgost
         POP H
         LXI D,lncci
lnchd:   DCX D
         MOV A,D
         ORA A
         JNZ lnchd
         JMP lnrnl
ljypp:   MVI A,050h
         STA lcasc
         STA lgftu
         CALL lgozr
         JMP ljyyv

lnouv:   DB 050h, 028h, 050h, 028h, 050h, 028h, 0A0h, 0FFh, 000h, 001h
ljyyv:   MVI A,000h
lnrxl:   INR A
         MOV L,A
         MVI H,068h
         MVI M,000h
         MVI H,069h
         MVI M,001h
         CPI 064h
         JNZ lnrxl
         MVI A,000h
         MVI H,068h
ljjsn:   INR A
         MOV L,A
         MVI M,009h
         MOV C,A
         ADI 05Ah
         MOV L,A
         MVI M,009h
         MOV A,C
         CPI 00Ah
         JNZ ljjsn
         MVI A,001h
lncua:   ADI 00Ah
         MOV L,A
         MVI M,009h
         MOV C,A
         ADI 009h
         MOV L,A
         MVI M,009h
         MOV A,C
         CPI 051h
         JNZ lncua
         MVI H,069h
         MVI A,00Ch
ljvme:   INR A
         MOV L,A
         MVI M,004h
         MOV C,A
         ADI 00Ah
         MOV L,A
         MVI M,0FEh
         MOV A,C
         ADI 046h
         MOV L,A
         MVI M,004h
         SUI 00Ah
         MOV L,A
         MVI M,0FEh
         MOV A,C
         CPI 012h
         JNZ ljvme
         MVI A,00Ch
ljmjg:   ADI 00Ah
         MOV L,A
         MVI M,004h
         MOV C,A
         INR A
         MOV L,A
         MVI M,0FEh
         MOV A,C
         ADI 007h
         MOV L,A
         MVI M,004h
         DCR A
         MOV L,A
         MVI M,0FEh
         MOV A,C
         CPI 048h
         JNZ ljmjg
         MVI A,010h
         STA lkzrn
         STA lojvf
         STA lovyl
         STA lkqmx
         MVI A,0F8h
         STA logul
         STA lkzpb
         STA lkqpj
         STA losqh
         LXI H,lnftb
         CALL ldkwn
         CALL ljynj
ljymm:   LXI H,ljvwx
         CALL ljjwm
lnoki:   CPI 031h
         JC ljymm
         CPI 036h
         JNC ljymm
         LXI H,lnrhm
         SHLD lcjko
         MVI C,02Eh
         CALL lgozx
         MOV C,A
         CALL lgozx
         MVI C,02Eh
         CALL lgozx
         SUI 030h
         STA lknxt
         CALL ljvii
         CALL ljjhr
         LXI H,lnftq
         CALL ljjwm
         CPI 064h
         JZ lnokl
         CPI 044h
         JZ lnokl
         MVI A,002h
         STA logmn
         MVI A,004h
         STA llczd
         MVI A,004h
         STA lkqwb
         CALL lnort
         MVI A,005h
         STA llczd
         CALL lnort
         MVI A,002h
         STA lknnt
         STA logtt
         MVI A,001h
         STA logmn
         MVI A,005h
         STA lkqwb
         MVI A,004h
         STA llczd
         CALL lnort
         MVI A,005h
         STA llczd
         CALL lnort
         MVI A,001h
         STA lospl
         STA llcpd
         JMP ljypq
lnokl:   MVI A,001h
         STA logmn
         MVI A,004h
         STA llczd
         MVI A,005h
         STA lkqwb
         CALL lnort
         MVI A,005h
         STA llczd
         MVI A,004h
         STA lkqwb
         CALL lnort
         MVI A,001h
         STA lospl
         STA logtt
         MVI A,002h
         STA logmn
         MVI A,004h
         STA llczd
         STA lkqwb
         CALL lnort
         MVI A,005h
         STA llczd
         STA lkqwb
         CALL lnort
         MVI A,002h
         STA lknnt
         STA llcpd
ljypq:   MVI A,004h
         STA llcrt
         STA lkqor
         MVI A,002h
         STA lovqj
         STA lojnh
         LXI H,ljyxm
         CALL ljjwm
         CPI 062h
         JZ ljvvq
         CPI 042h
         JZ ljvvq
         MVI A,001h
         STA lojur
         INR A
         STA lovxt
         JMP ljjis
ljvvq:   MVI A,001h
         STA lovxt
         INR A
         STA lojur
ljjis:   MVI A,005h
         STA lbxhm
         MVI A,028h
         STA lcjko
         LXI H,lnftu
         CALL ldkwn
         MVI A,09Ah
         STA lbxhm
         LXI H,ljjko
         CALL ldkwn
         LDA lovxt
         STA logmn
         LXI D,lcllh
         CALL ljmhk
         LDA lojur
         STA logmn
         LXI D,lcrif
         CALL ljmhk
         MVI A,005h
         STA lbxhm
         MVI A,070h
         STA lcjko
         LXI H,lncuw
         CALL ldkwn
         LDA lovxt
         STA ljjnf
         STA ljmsi
         STA ljjgp
         STA lncmo
         STA lnfok
         STA lnccs
         STA ljjhx
         LDA lojur
         STA lnoow
         STA lnoqu
         STA lnoig
         STA lnrkc
         STA lnopr
         STA lnofv
         STA ljvjm
         MVI A,09Ah
         STA lbxhm
         LXI H,lncuw
         CALL ldkwn
         LDA lovqj
         ADI 030h
         MOV C,A
         LXI H,lkany
         SHLD lcjko
         CALL lgozx
         LDA lojnh
         ADI 030h
         MOV C,A
         LXI H,lcszw
         SHLD lcjko
         CALL lgozx
         LXI H,lnovi
         SHLD lcjko
         LXI H,lnooc
         CALL ldkwn
         LXI H,lgeey
         SHLD lcjko
         LXI H,lnooc
         CALL ldkwn
         LXI H,lnfte
         CALL ljjwm
         CPI 064h
         JZ ljjil
         CPI 044h
         JZ ljjil
ljmwa:   LXI H,ljyxs
         CALL ljynz
         LDA llcrt
         MOV B,A
         LDA lknxt
         ADD B
         CPI 03Ch
         JC lnfke
         LXI H,lldcd
         MVI B,064h
ljmjs:   MVI M,001h
         INX H
         DCR B
         JNZ ljmjs
         MVI A,009h
         STA lknxt
         CALL ljvii
         CALL ljjhr
lnfke:   CALL ljyjh
         LDA lospp
         ORA A
         JNZ lnfih
         LXI H,ljvyu
         CALL ljynz
         MVI B,01Eh
ljjii:   MVI A,064h
         ADD B
         ADD B
         ADD B
         ADD B
         ADD B
         STA lcasc
         CALL lgost
         DCR B
         JNZ ljjii
         LDA loszl
         DCR A
         JZ lnror
         STA loszl
         JMP ljjil
lnfih:   LDA lospp
         STA logwj
         MVI A,002h
         STA loszl
         CALL ljyqu
         LDA lovxt
         STA lovnx
         LDA lojur
         STA logmn
         MVI A,060h
         STA lcasc
         CALL lnffx
         LXI H,lcstq
         SHLD lcjko
         MVI C,07Fh
         CALL lgozx
         CALL lgozx
         SHLD lcjko
         LDA llczd
         ADI 030h
         MOV C,A
         CALL lgozx
         LDA lkqwb
         ADI 040h
         MOV C,A
         CALL lgozx
         LDA llcrt
         INR A
         STA llcrt
         LDA lkzqz
         MOV B,A
         LDA lojnh
         ADD B
         STA lojnh
         LDA lovqj
         SUB B
         INR A
         STA lovqj
         CALL ljmnd
ljjil:   LDA llcrt
         CPI 040h
         JZ lnror
         LDA lovqj
         ORA A
         JZ lnror
ljvok:   XRA A
         STA llczd
         STA lkqwb
         STA logwj
         MVI A,040h
         STA lcasc
         LXI H,ljyxt
         CALL ljjwm
         CALL ljjdr
         LDA logwj
         CPI 000h
         JNZ lncgw
         CALL lnost
         JNZ ljvok
         LDA loszl
         DCR A
         JZ lnror
         STA loszl
         JMP ljmwa
lncgw:   MVI A,002h
         STA loszl
         CALL ljyqu
         LDA lovxt
         STA logmn
         LDA lojur
         STA lovnx
         MVI A,040h
         STA lcasc
         CALL lnffx
         LDA lkzqz
         CPI 002h
         JNC ljjik
         LXI H,lnonp
         CALL ljynz
         MVI B,014h
lnfkg:   LDA lcasc
         ADI 064h
         STA lcasc
         CALL lgost
         DCR B
         JNZ lnfkg
         JMP ljvok
ljjik:   LDA llcrt
         INR A
         STA llcrt
         LDA lkzqz
         MOV B,A
         LDA lovqj
         ADD B
         STA lovqj
         LDA lojnh
         SUB B
         INR A
         STA lojnh
         CALL ljmnd
         LDA lojnh
         CPI 000h
         JZ lnror
         LDA llcrt
         CPI 040h
         JNZ ljmwa
lnror:   LDA lovqj
         MOV B,A
         LDA lojnh
         CMP B
         JZ lnoll
         JNC ljvzx
         LXI H,lnold
         JMP lncvl
lnoll:   LXI H,lncsr
         JMP lncvl
ljvzx:   LXI H,ljjvx
lncvl:   CALL ljynz
         MVI B,032h
         MVI A,040h
         STA lcasc
ljmvd:   CALL lgost
         DCR B
         JNZ ljmvd
         LXI H,ljvwn
         CALL ljjwm
         CPI 064h
         JZ ljyyv
         CPI 044h
         JZ ljyyv
         RET
ljmnd:   LXI H,lkany
         SHLD lcjko
         MVI C,07Fh
         CALL lgozx
         CALL lgozx
         LXI H,lkany
         SHLD lcjko
         LDA lovqj
         MVI B,000h
lnrzc:   INR B
         SUI 00Ah
         JNC lnrzc
         DCR B
         MOV D,A
         MOV A,B
         ADI 030h
         MOV C,A
         CALL lgozx
         MOV A,D
         ADI 03Ah
         MOV C,A
         CALL lgozx
         LXI H,lcszw
         SHLD lcjko
         MVI C,07Fh
         CALL lgozx
         CALL lgozx
         LXI H,lcszw
         SHLD lcjko
         LDA lojnh
         MVI B,000h
ljmui:   INR B
         SUI 00Ah
         JNC ljmui
         DCR B
         MOV D,A
         MOV A,B
         ADI 030h
         MOV C,A
         CALL lgozx
         MOV A,D
         ADI 03Ah
         MOV C,A
         CALL lgozx
         RET
ljyqu:   LDA logwj
         MVI B,028h
         LXI H,lnfvo
ljyye:   CMP M
         JZ lnfjw
         INX H
         INX H
         DCR B
         RZ
         JMP ljyye
lnfjw:   INX H
         MOV E,M
         MVI D,069h
         MVI A,001h
         STAX D
         RET

lnfvo:   DB 00Ch, 017h, 00Eh, 018h, 00Fh, 019h, 010h, 01Ah, 011h, 01Bh
         DB 013h, 01Ch, 027h, 026h, 031h, 030h, 03Bh, 03Ah, 045h, 044h
         DB 059h, 04Eh, 057h, 04Dh, 056h, 04Ch, 055h, 04Bh, 054h, 04Ah
         DB 052h, 049h, 03Eh, 03Fh, 034h, 035h, 02Ah, 02Bh, 020h, 021h
         DB 017h, 017h, 018h, 018h, 019h, 019h, 01Ah, 01Ah
lnftr:   DB 01Bh, 01Bh, 01Ch, 01Ch, 026h, 026h, 030h, 030h, 03Ah, 03Ah
         DB 044h, 044h, 04Eh, 04Eh, 04Dh, 04Dh, 04Ch, 04Ch, 04Bh, 04Bh
         DB 04Ah, 04Ah, 049h, 049h, 03Fh, 03Fh, 035h, 035h, 02Bh, 02Bh
         DB 017h, 017h
lnftb:   DB 01Fh, 020h, 03Dh, 020h, 03Dh, 020h, 03Dh, 020h, 03Dh, 020h
         DB 03Dh, 020h, 03Dh, 020h, 03Dh, 020h, 03Dh, 020h, 03Dh, 020h
         DB 03Dh, 020h, 03Dh, 020h, 03Dh, 020h, 072h, 020h, 065h, 020h
         DB 077h, 020h, 065h, 020h, 072h, 020h, 073h, 020h, 069h, 020h
         DB 03Dh, 020h, 03Dh, 020h, 03Dh, 020h, 03Dh, 020h, 03Dh, 020h
         DB 03Dh, 020h, 03Dh, 020h, 03Dh, 020h, 03Dh, 020h, 03Dh, 020h
         DB 03Dh, 020h, 03Dh, 020h, 000h
ljvwx:   DB 075h, 06Bh, 061h, 076h, 069h, 074h, 065h, 020h, 075h, 072h
         DB 06Fh, 077h, 065h, 06Eh, 078h, 020h, 069h, 067h, 072h, 079h
         DB 020h, 028h, 031h, 02Eh, 02Eh, 02Eh, 035h, 029h, 020h, 03Eh
         DB 000h
lnftq:   DB 070h, 065h, 072h, 065h, 073h, 065h, 07Eh, 065h, 06Eh, 069h
         DB 065h, 020h, 077h, 020h, 063h, 065h, 06Eh, 074h, 072h, 065h
         DB 020h, 028h, 064h, 02Fh, 06Eh, 029h, 020h, 03Eh, 000h
ljyxm:   DB 06Bh, 061h, 06Bh, 069h, 06Dh, 020h
lnovi:   DB 063h, 077h, 065h, 074h, 06Fh, 06Dh, 020h, 062h, 075h, 064h
         DB 065h, 074h, 065h, 020h, 069h, 067h, 072h, 061h, 074h, 078h
         DB 020h, 028h, 062h, 02Fh, 07Eh, 029h, 020h, 03Eh, 000h
lnftu:   DB 077h, 061h, 07Bh, 020h, 063h, 077h, 065h, 074h, 03Ah, 000h
ljjko:   DB 063h, 077h, 065h, 074h, 020h, 07Ch, 077h, 06Dh, 03Ah, 000h
lncuw:   DB 066h, 069h, 067h, 075h, 072h, 03Ah, 000h
lnooc:   DB 068h, 06Fh, 064h, 03Ah, 000h
lnfte:   DB 062h, 075h, 064h, 065h, 074h, 065h, 020h, 068h, 06Fh, 064h
         DB 069h, 074h, 078h, 020h, 070h, 065h, 072h, 077h, 079h, 06Dh
         DB 020h, 028h, 064h, 02Fh, 06Eh, 029h, 020h, 03Eh, 000h
ljyxt:   DB 068h, 06Fh, 064h, 069h, 074h, 065h, 020h, 028h, 073h, 074h
         DB 072h, 02Fh, 073h, 074h, 062h, 03Bh, 020h, 022h, 04Bh, 022h
         DB 03Bh, 020h, 022h, 042h, 04Bh, 022h, 029h, 020h, 03Eh, 000h
lnonp:   DB 06Eh, 065h, 077h, 065h, 072h, 06Eh, 079h, 06Ah, 020h, 068h
         DB 06Fh, 064h, 020h, 021h, 020h, 000h
lnold:   DB 070h, 06Fh, 07Ah, 064h, 072h, 061h, 077h, 06Ch, 071h, 060h
         DB 021h, 020h, 077h, 079h, 020h, 070h, 06Fh, 062h, 065h, 064h
         DB 069h, 06Ch, 069h, 02Eh, 000h
lncsr:   DB 062h, 06Fh, 065h, 077h, 061h, 071h, 020h, 06Eh, 069h, 07Eh
         DB 078h, 071h, 02Eh, 000h
ljjvx:   DB 020h, 071h, 020h, 077h, 079h, 069h, 067h, 072h, 061h, 06Ch
         DB 061h, 021h, 021h, 021h, 000h
ljvwn:   DB 020h, 068h, 06Fh, 074h, 069h, 074h, 065h, 020h, 065h, 07Dh
         DB 065h, 020h, 073h, 079h, 067h, 072h, 061h, 074h, 078h, 020h
         DB 028h, 064h, 02Fh, 06Eh, 029h, 020h, 03Eh, 000h
ljyxs:   DB 020h, 06Fh, 076h, 069h, 064h, 061h, 06Ah, 074h, 065h, 021h
         DB 020h, 071h, 020h, 064h, 075h, 06Dh, 061h, 060h, 02Eh, 000h
ljvyu:   DB 020h, 06Dh, 06Eh, 065h, 020h, 06Eh, 065h, 06Bh, 075h, 064h
         DB 061h, 020h, 068h, 06Fh, 064h, 069h, 074h, 078h, 021h, 000h
         DB 020h, 071h, 020h, 070h, 06Fh, 07Bh, 06Ch, 061h, 020h, 06Eh
         DB 061h, 020h, 000h
ljjwm:   MVI A,026h
         STA lbxhm
         MVI A,0FAh
         STA lcjko
         PUSH H
         LXI H,ljypw
         CALL ldkwn
         MVI A,026h
         STA lbxhm
         MVI A,0FAh
         STA lcjko
         POP H
         CALL ldkwn
         CALL lgozr
         RET

ljypw:   DB 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh
         DB 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh
         DB 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh
         DB 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh
         DB 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 07Fh, 000h
ljynz:   MVI A,026h
         STA lbxhm
         MVI A,0FAh
         STA lcjko
         PUSH H
         LXI H,ljypw
         CALL ldkwn
         MVI A,026h
         STA lbxhm
         MVI A,0FAh
         STA lcjko
         POP H
         CALL ldkwn
         RET
ljynj:   LXI D,lckxf
lnfix:   MVI B,000h
ljjjn:   MVI C,000h
         MOV H,D
         MOV L,E
ljmxj:   MVI M,0FFh
         INR H
         INR C
         MOV A,C
         CPI 018h
         JNZ ljmxj
         INR E
         INR B
         MOV A,B
         CPI 002h
         JNZ ljjjn
         MOV A,E
         ADI 016h
         MOV E,A
         CPI 0DCh
         JNZ lnfix
         LXI D,lckxf
lncix:   MVI B,000h
ljmwt:   MVI C,000h
         MOV H,D
         MOV L,E
ljjvz:   MOV A,M
         ORI 0C0h
         MOV M,A
         INR L
         INR C
         MOV A,C
         CPI 0C0h
         JNZ ljjvz
         INR D
         INR B
         MOV A,B
         CPI 001h
         JNZ ljmwt
         MOV A,D
         ADI 002h
         MOV D,A
         CPI 0B3h
         JNZ lncix
         LXI D,lcoid
         MVI B,000h
lncva:   MVI C,000h
         MOV L,E
         MOV H,D
lnfly:   MVI M,0FFh
         MOV A,L
         ADI 0CCh
         MOV L,A
         MVI M,0FFh
         SUI 0CCh
         MOV L,A
         INR H
         INR C
         MOV A,C
         CPI 01Ch
         JNZ lnfly
         INR E
         INR B
         MOV A,B
         CPI 00Eh
         JNZ lncva
         LXI D,lcoid
         MVI B,000h
lnfli:   MVI C,000h
         MOV L,E
         MOV H,D
lncko:   MVI M,03Fh
         MOV A,B
         CPI 000h
         JZ ljmkg
         MVI M,0FFh
ljmkg:   MOV A,H
         ADI 01Ah
         MOV H,A
         MVI M,0FFh
         PUSH PSW
         MOV A,B
         CPI 000h
         JZ ljyqo
         MVI M,0FFh
ljyqo:   POP PSW
         SUI 01Ah
         MOV H,A
         INR L
         INR C
         MOV A,C
         CPI 0DAh
         JNZ lncko
         INR D
         INR B
         MOV A,B
         CPI 002h
         JNZ lnfli
         MVI B,041h
         MVI D,030h
ljyzu:   MVI E,01Ah
         MOV L,E
lnfvi:   MOV H,D
         DCR L
         MVI C,07Fh
         CALL ljvhl
         MOV H,D
         INR L
         INR L
         CALL ljvhl
         MOV A,L
         CPI 0E7h
         JZ ljjjq
         MOV A,E
         ADI 0CCh
         MOV L,A
         JMP lnfvi
ljjjq:   MOV H,D
         INR H
         MOV L,E
         MOV C,B
         SHLD lcjko
         CALL lgozx
         MOV A,E
         ADI 0CCh
         MOV L,A
         SHLD lcjko
         CALL lgozx
         MOV A,D
         ADI 00Ch
         MOV D,A
         INR B
         MOV A,B
         CPI 049h
         JNZ ljyzu
         MVI B,031h
         MVI E,02Bh
ljytt:   MVI D,026h
         MOV H,D
lnfph:   MOV L,E
         DCR L
         MVI C,07Fh
         CALL ljvhl
         INR L
         INR L
         CALL ljvhl
         MOV A,H
         CPI 08Dh
         JZ ljvgr
         MOV A,D
         ADI 067h
         MOV H,A
         JMP lnfph
ljvgr:   MOV H,D
         INR H
         MOV L,E
         MOV C,B
         SHLD lcjko
         CALL lgozx
         MOV A,D
         ADI 068h
         MOV H,A
         SHLD lcjko
         CALL lgozx
         MOV A,E
         ADI 018h
         MOV E,A
         INR B
         MOV A,B
         CPI 039h
         JNZ ljytt
         RET
ljvhl:   SHLD lcjko
         CALL lgozx
         CALL lgozx
         RET
lnort:   LXI D,lckxf
         LDA llczd
ljvjh:   DCR A
         JZ ljmen
         MOV B,A
         MOV A,E
         ADI 018h
         MOV E,A
         MOV A,B
         JMP ljvjh
ljmen:   LDA lkqwb
ljvgv:   DCR A
         JZ ljmhk
         MOV B,A
         MOV A,D
         ADI 003h
         MOV D,A
         MOV A,B
         JMP ljvgv
ljmhk:   LXI H,lnrim
         LDA logmn
         DCR A
         JZ lnops
         LXI H,lnrqa
lnops:   MVI C,003h
ljyia:   MVI B,018h
         PUSH D
lnfdo:   MOV A,M
         STAX D
         INX H
         INR E
         DCR B
         JNZ lnfdo
         POP D
         INR D
         DCR C
         JNZ ljyia
         RET

lnrim:   DB 0FFh, 0FFh, 0C0h, 0C0h, 0C0h, 0C0h, 0C1h, 0C3h, 0C7h, 0C7h
         DB 0CFh, 0CFh, 0CFh, 0CFh, 0CFh, 0CFh, 0C7h, 0C7h, 0C3h, 0C1h
         DB 0C0h, 0C0h, 0C0h, 0C0h, 0FFh, 0FFh, 000h, 000h, 03Fh, 0FFh
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0E1h, 0C0h, 0C0h, 0C0h, 0C0h, 0E1h
         DB 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 03Fh, 000h, 000h, 0FFh, 0FFh
         DB 000h, 000h, 000h, 0C0h, 0E0h, 0F0h, 0F8h, 0F8h, 0FCh, 0FCh
         DB 0FCh, 0FCh, 0FCh, 0FCh, 0F8h, 0F8h, 0F0h, 0E0h, 0C0h, 000h
         DB 000h, 000h
lnrqa:   DB 0FFh, 0FFh, 0C0h, 0C0h, 0C0h, 0C0h, 0C1h, 0C2h, 0C4h, 0C4h
         DB 0C8h, 0C8h, 0C8h
lncci:   DB 0C8h, 0C8h, 0C8h, 0C4h, 0C4h, 0C2h, 0C1h, 0C0h, 0C0h, 0C0h
         DB 0C0h, 0FFh, 0FFh, 000h, 000h, 03Fh, 0C0h, 000h, 000h, 000h
         DB 000h, 01Eh, 03Fh, 03Fh, 03Fh, 03Fh, 01Eh, 000h, 000h, 000h
         DB 000h, 0C0h, 03Fh, 000h, 000h, 0FFh, 0FFh, 000h, 000h, 000h
         DB 0C0h, 020h, 010h, 008h, 008h, 004h, 004h, 004h, 004h, 004h
         DB 004h, 008h, 008h, 010h, 020h, 0C0h, 000h, 000h, 000h
lnrgd:   CALL lgozr
ljjdr:   CPI 00Dh
         JNZ lnrjj
         LDA logwj
         ORA A
         RZ
         JMP ljmek
lnrjj:   CPI 04Bh
         JZ ljvrj
         CPI 06Bh
         JNZ ljyih
ljvrj:   POP H
         JMP ljyyv
ljyih:   CPI 008h
         JNZ lncex
         MVI C,008h
         CALL lgozx
         MVI C,07Fh
         CALL lgozx
         MVI C,008h
         CALL lgozx
         JMP lnrgd
lncex:   CPI 039h
         JC ljmri
         CPI 049h
         JC ljyic
         CPI 069h
         JC lnces
         JMP lnrgd
ljmri:   CPI 031h
         JC lnrgd
         MOV C,A
         STA llczd
         CALL lgozx
         LDA logwj
         ORI 001h
         STA logwj
         JMP lnrgd
ljyic:   CPI 041h
         JC lnrgd
         MOV C,A
         STA lkqwb
         CALL lgozx
         LDA logwj
         ORI 002h
         STA logwj
         JMP lnrgd
lnces:   CPI 061h
         JC lnrgd
         SUI 020h
         JMP ljyic
ljmek:   LDA logwj
         CPI 003h
         JNZ lnrgd
         LXI H,00FC8h
         SHLD lcjko
         MVI C,07Fh
         CALL lgozx
         CALL lgozx
         LXI H,00FC8h
         SHLD lcjko
         LDA llczd
         MOV C,A
         CALL lgozx
         SUI 030h
         STA llczd
         ADD A
         MOV C,A
         ADD A
         ADD A
         ADD C
         MOV B,A
         LDA lkqwb
         MOV C,A
         CALL lgozx
         SUI 040h
         STA lkqwb
         ADD B
         INR A
         STA logwj
         RET
ljmeo:   LDA lkqmf
         MVI B,000h
lnofm:   INR B
         SUI 00Ah
         JNC lnofm
         ADI 00Ah
         DCR A
         STA lkqwb
         DCR B
         MOV A,B
         STA llczd
         MVI A,001h
         STA lojkv
ljvqv:   CALL lnort
         LXI H,lgwbe
lnrgj:   DCX H
         LXI D,00030h
lnofp:   DCX D
         MOV A,E
         ORA D
         JNZ lnofp
         MOV A,L
         ORA A
         JNZ lnrgj
         LDA lojkv
         CPI 005h
         RZ
         LDA logmn
         CPI 001h
         JZ ljvgj
         MVI A,001h
         JMP lnoez
ljvgj:   MVI A,002h
lnoez:   STA logmn
         LDA lojkv
         INR A
         STA lojkv
         JMP ljvqv
lnffx:   LDA logwj
         LXI H,lldcb
         ADD L
         MOV L,A
         MOV A,M
         ORA A
         JZ ljjeb
         XRA A
         STA lkzqz
         RET
ljjeb:   MVI B,000h
         LDA lovnx
         STA ljvgn
         LDA logmn
         STA ljjqe
         STA ljyro
         JMP lnrpt
ljmob:   POP H
lnrpt:   PUSH H
         MVI C,000h
ljjnh:   INR C
         MOV A,L
         SUI 001h
         MOV L,A
         MOV A,M
         CPI 000h
         JZ ljjnh
         DCR C
         JZ lnfoy
         CPI 000h
         JNZ lnfoy
         INR C
lnriu:   MOV A,L
         ADI 001h
         MOV L,A
         INR B
         MVI M,000h
         STA lkqmf
         PUSH H
         PUSH B
         CALL lgost
         CALL ljmeo
         POP B
         POP H
         DCR C
         JNZ lnriu
         DCR B
lnfoy:   JMP lnorg
lnorg:   LXI H,lncls
         SHLD ljvsq
         MVI A,009h
         STA ljyhh
         STA ljvjk
         JMP ljmob

lncls:   DB 021h, 0C8h, 00Ah, 022h, 0A4h, 00Ah, 03Eh, 00Ah, 032h, 078h
         DB 00Ah, 032h, 08Ch, 00Ah, 0C3h, 071h, 00Ah, 021h, 0D9h, 00Ah
         DB 022h, 0A4h, 00Ah, 03Eh, 00Bh, 032h, 078h, 00Ah, 032h, 08Ch
         DB 00Ah, 0C3h, 071h, 00Ah, 03Eh, 001h, 032h, 078h, 00Ah, 032h
         DB 08Ch, 00Ah, 03Eh, 0C6h, 032h, 077h, 00Ah, 03Eh, 0D6h, 032h
         DB 08Bh, 00Ah, 021h, 0A6h, 00Ah, 022h, 0A4h, 00Ah, 021h, 0FAh
         DB 00Ah, 022h, 0C9h, 00Ah, 0C3h, 071h, 00Ah, 0E1h, 03Eh, 001h
         DB 032h, 078h, 00Ah, 032h, 08Ch, 00Ah, 03Eh, 0D6h, 032h, 077h
         DB 00Ah, 03Eh, 0C6h, 032h, 08Bh, 00Ah, 021h, 0A6h, 00Ah, 022h
         DB 0A4h, 00Ah, 021h, 0D9h, 00Ah, 022h, 0C9h, 00Ah, 004h, 078h
         DB 032h, 06Ch, 068h, 0C9h
lnccp:   LDAX D
         ORA A
         JZ ljyjr
         XRA A
ljjpr:   JMP ljyzh
ljyjr:   POP H
         CMP H
         JZ ljmed
         MVI M,000h
lncel:   POP H
         CMP H
         JZ ljmed
         MVI M,000h
         JMP lncel
ljmed:   PUSH H
         MOV L,E
         MOV B,H
ljvgl:   LDA lncmk
         MOV E,L
         ORA A
         JZ lnoff
         MOV H,A
         MVI C,000h
lncpb:   INR C
         MOV A,E
         ADD H
         MOV E,A
         LDAX D
         CPI 000h
         JZ lncpb
         DCR C
         JZ lnril
         CPI 000h
         JNZ lnril
lnrgp:   MOV A,E
         SUB H
         MOV E,A
         MVI A,000h
         STAX D
         PUSH D
         INR D
         LDAX D
         ADD B
         MOV B,A
         DCR D
         DCR C
         JNZ lnrgp
lnril:   LDA ljjdj
         INR A
         STA ljjdj
         JNZ ljvgl
         LDA lnofb
         INR A
         STA lnofb
         JMP ljvgl
lnoff:   LXI H,lncmk
         SHLD ljjdj
         POP H
         MOV A,H
         PUSH H
         ORA A
         JZ ljjpr
         MVI A,000h
         STAX D
         PUSH D
         INR D
         LDAX D
         ADD B
         MOV B,A
         DCR D
         JMP ljjpr

lncmk:   DB 0F5h, 0F6h, 0F7h, 001h, 00Bh, 00Ah, 009h, 0FFh, 000h, 01Ah
         DB 0B7h, 0CAh, 0A9h, 00Bh, 0AFh, 0C3h, 000h, 000h, 0E1h, 0BCh
         DB 0CAh, 0BAh, 00Bh, 036h, 000h, 0E1h, 0BCh, 0CAh, 0BAh, 00Bh
         DB 036h
lnoow:   DB 000h, 0C3h, 0B0h, 00Bh, 0E5h, 06Bh, 044h, 03Ah, 097h, 00Bh
         DB 05Dh, 0B7h, 0CAh, 0FFh, 00Bh, 067h, 00Eh, 000h, 00Ch, 07Bh
         DB 084h, 05Fh, 01Ah, 0FEh
lnoig:   DB 000h, 0CAh, 0C8h, 00Bh, 00Dh, 0CAh, 0EBh, 00Bh, 0FEh
lncmo:   DB 000h, 0C2h, 0EBh, 00Bh, 07Bh, 094h, 05Fh, 03Eh
lnccs:   DB 000h, 012h, 0D5h, 014h, 01Ah, 080h, 047h, 015h, 00Dh, 0C2h
         DB 0DBh, 00Bh, 03Ah, 0BEh, 00Bh, 03Ch, 032h, 0BEh, 00Bh, 0C2h
         DB 0BDh, 00Bh, 03Ah, 0BFh, 00Bh, 03Ch, 032h, 0BFh, 00Bh, 0C3h
         DB 0BDh, 00Bh, 021h, 097h, 00Bh, 022h, 0BEh, 00Bh, 0E1h, 07Ch
         DB 0E5h, 0B7h, 0CAh, 0A6h, 00Bh, 03Eh
ljjhx:   DB 000h, 012h, 0D5h, 014h, 01Ah, 080h, 047h, 015h, 0C3h, 0A6h
         DB 00Bh
ljyjh:   XRA A
         STA lknxv
         STA lospp
         PUSH PSW
         MVI D,068h
         MVI E,00Ch
         LXI H,ljjhh
         SHLD lnorj
         JMP lnccp

ljjhh:   DB 0CAh, 09Dh, 00Eh, 0C6h, 07Dh, 032h, 065h, 06Bh, 0C3h
lnoqj:   DB 038h, 00Ch
ljyir:   DB 03Eh, 0FFh, 032h, 066h, 069h, 0AFh, 0F5h, 01Eh, 00Ch, 021h
         DB 04Ah, 00Ch, 022h, 0A7h, 00Bh, 0C3h, 0A0h, 00Bh, 0CAh, 06Ah
         DB 00Eh, 03Ah, 065h, 06Bh, 090h, 032h, 066h, 06Bh, 0C3h
ljjpl:   DB 057h, 00Ch
lncob:   DB 0AFh, 032h, 067h, 069h, 0F5h, 01Eh, 00Ch, 021h, 067h, 00Ch
         DB 022h, 026h, 00Bh, 0C3h, 01Fh, 00Bh, 0CAh, 03Eh, 00Eh, 03Ah
         DB 066h, 06Bh, 080h, 032h, 067h, 06Bh, 0C3h
lnrrh:   DB 074h, 00Ch
ljvrx:   DB 03Eh, 0FFh, 032h, 068h, 069h, 0AFh, 0F5h, 01Eh, 00Ch, 021h
         DB 086h, 00Ch, 022h, 0A7h, 00Bh, 0C3h, 0A0h, 00Bh, 0CAh, 011h
         DB 00Eh, 03Ah, 067h, 06Bh, 090h, 032h, 068h, 06Bh, 0C3h
ljmqa:   DB 093h, 00Ch
lnfoq:   DB 0AFh, 032h, 069h, 069h, 0F5h, 01Eh, 00Ch, 021h, 0A3h, 00Ch
         DB 022h, 026h, 00Bh, 0C3h, 01Fh, 00Bh, 0CAh, 0E5h, 00Dh, 03Ah
         DB 068h, 06Bh, 080h, 032h, 069h, 06Bh, 0C3h
lnoiy:   DB 0B0h, 00Ch
ljysm:   DB 03Eh, 0FFh, 032h, 06Ah, 069h, 0AFh, 0F5h, 01Eh, 00Ch, 021h
         DB 0C2h, 00Ch, 022h, 0A7h, 00Bh, 0C3h, 0A0h, 00Bh, 0CAh, 0B8h
         DB 00Dh, 03Ah, 069h, 06Bh, 090h
ljmiu:   DB 032h, 06Ah, 06Bh, 0C3h
ljjia:   DB 0CFh, 00Ch
lncgq:   DB 0AFh, 032h, 06Bh, 069h, 0F5h, 01Eh, 00Ch, 021h, 0DFh, 00Ch
         DB 022h, 026h, 00Bh, 0C3h, 01Fh, 00Bh, 0CAh, 08Ch, 00Dh, 03Ah
         DB 06Ah, 06Bh, 080h, 032h, 06Bh, 06Bh, 0C3h
lnrjw:   DB 0ECh, 00Ch
ljvkm:   DB 03Eh, 0FFh, 032h, 06Ch, 069h, 0AFh, 0F5h, 01Eh, 00Ch, 021h
         DB 0FEh, 00Ch, 022h, 0A7h, 00Bh, 0C3h, 0A0h, 00Bh, 0CAh, 05Fh
         DB 00Dh, 03Ah, 06Bh, 06Bh, 090h, 032h, 06Ch, 06Bh, 0C3h
ljmit:   DB 00Bh, 00Dh
lnfhj:   DB 0AFh, 032h, 06Dh, 069h, 0F5h, 01Eh, 00Ch, 021h, 01Bh, 00Dh
         DB 022h, 026h, 00Bh, 0C3h, 01Fh, 00Bh, 0CAh, 033h, 00Dh, 03Ah
         DB 06Ch, 06Bh, 080h, 032h, 06Dh, 06Bh, 03Ah, 06Dh, 069h, 047h
         DB 03Ah, 06Dh, 06Bh, 0B8h, 0DAh, 033h, 00Dh, 032h, 06Dh, 069h
         DB 03Ah, 011h, 00Dh, 03Ch, 032h, 011h, 00Dh, 0FEh, 05Ah, 0DAh
         DB 010h, 00Dh, 03Eh, 00Ch, 032h, 011h, 00Dh, 03Ah, 06Dh, 069h
         DB 0B7h, 0CAh, 01Eh, 00Dh, 032h, 06Ch, 06Bh, 0CDh, 0B2h, 00Eh
ljmqh:   DB 03Ah, 06Ch, 069h, 047h, 03Ah, 06Ch, 06Bh, 0B8h, 0D2h, 05Fh
         DB 00Dh, 032h, 06Ch, 069h, 03Ah, 0F4h, 00Ch, 03Ch, 032h, 0F4h
         DB 00Ch, 0FEh, 05Ah, 0DAh, 0F3h, 00Ch, 03Eh, 00Ch, 032h, 0F4h
         DB 00Ch, 03Ah, 06Ch, 069h, 0FEh, 0FFh, 0CAh, 001h, 00Dh, 032h
         DB 06Bh, 06Bh, 0CDh, 0C7h, 00Eh
lnogt:   DB 03Ah, 06Bh, 069h, 047h, 03Ah, 06Bh, 06Bh, 0B8h, 0DAh, 08Ch
         DB 00Dh, 032h, 06Bh, 069h, 03Ah, 0D5h, 00Ch, 03Ch, 032h, 0D5h
         DB 00Ch, 0FEh, 05Ah, 0DAh, 0D4h, 00Ch, 03Eh, 00Ch, 032h, 0D5h
         DB 00Ch, 03Ah, 06Bh, 069h, 0B7h, 0CAh, 0E2h, 00Ch, 032h, 06Ah
         DB 06Bh, 0CDh, 0B2h, 00Eh
lnrju:   DB 03Ah, 06Ah, 069h, 047h, 03Ah, 06Ah, 06Bh, 0B8h, 0D2h, 0B8h
         DB 00Dh, 032h, 06Ah, 069h, 03Ah, 0B8h, 00Ch, 03Ch, 032h, 0B8h
         DB 00Ch, 0FEh, 05Ah, 0DAh, 0B7h, 00Ch, 03Eh, 00Ch, 032h, 0B8h
         DB 00Ch, 03Ah, 06Ah, 069h, 0FEh, 0FFh, 0CAh, 0C5h, 00Ch, 032h
         DB 069h, 06Bh, 0CDh, 0C7h, 00Eh
lncoc:   DB 03Ah, 069h, 069h, 047h, 03Ah, 069h, 06Bh, 0B8h, 0DAh, 0E5h
         DB 00Dh, 032h, 069h, 069h, 03Ah, 099h, 00Ch, 03Ch, 032h, 099h
         DB 00Ch, 0FEh, 05Ah, 0DAh, 098h, 00Ch, 03Eh, 00Ch, 032h, 099h
         DB 00Ch, 03Ah, 069h, 069h, 0B7h
lnrhm:   DB 0CAh, 0A6h, 00Ch, 032h, 068h, 06Bh, 0CDh, 0B2h, 00Eh
lnfqv:   DB 03Ah, 068h, 069h, 047h, 03Ah, 068h, 06Bh, 0B8h, 0D2h, 011h
         DB 00Eh, 032h, 068h, 069h, 03Ah, 07Ch, 00Ch, 03Ch, 032h, 07Ch
         DB 00Ch, 0FEh, 05Ah, 0DAh, 07Bh, 00Ch, 03Eh, 00Ch, 032h, 07Ch
         DB 00Ch, 03Ah, 068h, 069h, 0FEh, 0FFh, 0CAh, 089h, 00Ch, 032h
         DB 067h, 06Bh, 0CDh, 0C7h, 00Eh
ljysf:   DB 03Ah, 067h, 069h, 047h, 03Ah, 067h, 06Bh, 0B8h, 0DAh, 03Eh
         DB 00Eh, 032h, 067h, 069h, 03Ah, 05Dh, 00Ch, 03Ch, 032h, 05Dh
         DB 00Ch, 0FEh, 05Ah, 0DAh, 05Ch, 00Ch, 03Eh, 00Ch, 032h, 05Dh
         DB 00Ch, 03Ah, 067h, 069h, 0B7h, 0CAh, 06Ah, 00Ch, 032h, 066h
         DB 06Bh, 0CDh, 0B2h, 00Eh
ljvij:   DB 03Ah, 066h, 069h, 047h, 03Ah, 066h, 06Bh, 0B8h, 0D2h, 06Ah
         DB 00Eh, 032h, 066h, 069h, 03Ah, 040h, 00Ch, 03Ch, 032h, 040h
         DB 00Ch, 0FEh, 05Ah, 0DAh, 03Fh, 00Ch, 03Eh, 00Ch, 032h, 040h
         DB 00Ch, 03Ah, 066h, 069h, 0FEh, 0FFh, 0CAh, 04Dh, 00Ch, 032h
         DB 065h, 06Bh, 0CDh, 0C7h, 00Eh
ljmii:   DB 03Ah, 065h, 069h, 047h, 03Ah, 065h, 06Bh, 0B8h, 0DAh, 09Dh
         DB 00Eh, 032h, 065h, 069h, 03Ah, 023h, 00Ch, 032h, 06Eh, 068h
         DB 03Ah, 023h, 00Ch, 03Ch, 032h, 023h, 00Ch, 0FEh, 05Ah, 0DAh
         DB 022h, 00Ch, 03Eh, 00Ch, 032h, 023h, 00Ch, 0CDh, 0B2h, 00Eh
         DB 0C9h, 0AFh, 0C1h, 0E1h, 0BCh, 0CAh, 0C5h, 00Eh, 036h, 000h
         DB 0E1h, 0BCh, 0CAh, 0C5h, 00Eh, 036h
ljmsi:   DB 000h, 0C3h, 0BBh, 00Eh, 0C5h, 0C9h, 0AFh, 0C1h, 0E1h, 0BCh
         DB 0CAh, 0DAh, 00Eh, 036h, 000h, 0E1h, 0BCh, 0CAh, 0DAh, 00Eh
         DB 036h
lnoqu:   DB 000h, 0C3h, 0D0h, 00Eh, 0C5h, 0C9h
ljvii:   LXI H,ljyir
         SHLD lnoqj
         LXI H,lncob
         SHLD ljjpl
         LXI H,ljvrx
         SHLD lnrrh
         LXI H,lnfoq
         SHLD ljmqa
         LXI H,ljysm
         SHLD lnoiy
         LXI H,lncgq
         SHLD ljjia
         LXI H,ljvkm
         SHLD lnrjw
         LXI H,lnfhj
         SHLD ljmit
         RET
ljjhr:   LDA lknxt
         DCR A
         JNZ lnfep
         LXI H,ljmii
         SHLD lnoqj
         RET
lnfep:   DCR A
         JNZ lnosp
         LXI H,ljvij
         SHLD ljjpl
         RET
lnosp:   DCR A
         JNZ ljmpf
         LXI H,ljysf
         SHLD lnrrh
         RET
ljmpf:   DCR A
         JNZ ljvhr
         LXI H,lnfqv
         SHLD ljmqa
         RET
ljvhr:   DCR A
         JNZ lncqh
         LXI H,lncoc
         SHLD lnoiy
         RET
lncqh:   DCR A
         JNZ lnrrr
         LXI H,lnrju
         SHLD ljjia
         RET
lnrrr:   DCR A
         JNZ ljjfj
         LXI H,lnogt
         SHLD lnrjw
         RET
ljjfj:   DCR A
         RNZ
         LXI H,ljmqh
         SHLD ljmit
         RET
lnost:   XRA A
         STA lknxv
         STA lospp
         MVI D,068h
lncfv:   MVI E,00Ch
         MVI B,000h
         LDAX D
         ORA A
         JNZ ljjrq
         MOV L,E
ljmfn:   LDA lncmk
         MOV E,L
         ORA A
         JZ lnois
         MOV H,A
         MVI C,000h
ljvuo:   INR C
         MOV A,E
         ADD H
         MOV E,A
         LDAX D
         CPI 000h
         JZ ljvuo
         DCR C
         JZ lnrhq
         CPI 000h
         JNZ lnrhq
         MOV A,B
         ADD C
         MOV B,A
lnrhq:   LDA lnrhf
         INR A
         STA lnrhf
         JNZ ljmfn
         LDA lnfed
         INR A
         STA lnfed
         JMP ljmfn
lnois:   LXI H,lncmk
         SHLD lnrhf
         LDA lknxv
         CMP B
         JNC ljjrq
         MOV A,B
         STA lknxv
         LDA ljysl
         STA lospp
ljjrq:   LDA ljysl
         INR A
         STA ljysl
         CPI 05Ah
         JC lncfv
         MVI A,00Ch
         STA ljysl
         LDA lospp
         ORA A
         RZ
         MVI B,000h
ljjfi:   INR B
         SUI 00Ah
         JNC ljjfi
         ADI 00Ah
         DCR A
         STA lkqwb
         DCR B
         MOV A,B
         STA llczd
         MVI A,001h
         STA lojkv
lnfny:   LXI D,lckxf
         LDA llczd
ljmfm:   DCR A
         JZ lnqkn
         MOV B,A
         MOV A,E
         ADI 018h
         MOV E,A
         MOV A,B
         JMP ljmfm
lnqkn:   LDA lkqwb
ljnzt:   DCR A
         JZ lnqib
         MOV B,A
         MOV A,D
         ADI 003h
         MOV D,A
         MOV A,B
         JMP ljnzt
lnqib:   MVI C,003h
lkaaj:   MVI B,018h
         PUSH D
lngvx:   LDAX D
         CMA
         STAX D
         INX H
         INR E
         DCR B
         JNZ lngvx
         POP D
         INR D
         DCR C
         JNZ lkaaj
         LXI H,lgwbe
ljkyj:   DCX H
         LXI D,00030h
ljogn:   DCX D
         MOV A,E
         ORA D
         JNZ ljogn
         MOV A,L
         ORA A
         JNZ ljkyj
         LDA lojkv
         INR A
         STA lojkv
         CPI 00Bh
         JNZ lnfny
         MVI A,001h
         ORA A
         RET
         DB 00Dh, 020h, 04Ch, 044h
lkakj:   DB 0FFh, 000h, 0FFh, 000h, 055h, 000h, 001h, 01Fh, 001h, 020h
         DB 001h, 040h, 001h, 080h, 005h, 0FFh, 006h, 0FCh, 001h, 0FDh
         DB 001h, 0FEh, 005h, 0FFh, 009h, 0FCh, 001h, 0FDh, 001h, 0FEh
         DB 04Bh, 000h, 002h, 001h, 001h, 002h, 001h, 004h, 001h, 00Fh
         DB 001h, 009h, 001h, 008h, 001h, 009h, 001h, 008h, 001h, 009h
         DB 001h, 008h, 001h, 009h, 001h, 008h, 001h, 00Fh, 086h, 000h
         DB 001h, 0FFh, 003h, 000h, 005h, 0FFh, 004h, 040h, 001h, 07Fh
         DB 001h, 080h, 002h, 000h, 005h, 0FFh, 008h, 040h, 001h, 080h
         DB 043h, 000h, 001h, 001h, 002h, 002h, 001h, 004h, 001h, 008h
         DB 002h, 010h, 001h, 020h, 001h, 040h, 001h, 080h, 004h, 000h
         DB 001h, 0FFh, 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h
         DB 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h, 0FFh
         DB 086h, 000h, 001h, 0FCh, 001h, 006h, 001h, 009h, 001h, 010h
         DB 001h, 0E0h, 001h, 0F0h, 001h, 0F8h, 001h, 0FCh, 001h, 0FEh
         DB 004h, 01Fh, 001h, 0FFh, 003h, 01Fh, 001h, 0FEh, 001h, 0FCh
         DB 001h, 0F8h, 001h, 0F0h, 001h, 0E0h, 042h, 000h, 001h, 001h
         DB 001h, 003h, 002h, 007h, 001h, 00Fh, 001h, 017h, 001h, 03Fh
         DB 002h, 040h, 001h, 080h, 005h, 000h, 002h, 001h, 001h, 003h
         DB 001h, 007h, 002h, 00Fh, 001h, 01Fh, 001h, 03Fh, 001h, 07Fh
         DB 001h, 0FFh, 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h
         DB 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h, 0FFh
         DB 089h, 000h, 001h, 080h, 001h, 040h, 001h, 020h, 001h, 030h
         DB 001h, 050h, 001h, 090h, 005h, 010h, 001h, 020h, 001h, 040h
         DB 001h, 080h, 03Ch, 000h, 001h, 001h, 001h, 002h, 002h, 004h
         DB 001h, 008h, 001h, 01Fh, 002h, 03Fh, 001h, 07Fh, 009h, 0FFh
         DB 001h, 007h, 002h, 00Fh, 001h, 01Fh, 001h, 03Fh, 002h, 07Fh
         DB 00Bh, 0FFh, 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h
         DB 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h, 0FFh
         DB 086h, 000h, 001h, 01Fh, 001h, 020h, 001h, 040h, 001h, 080h
         DB 005h, 0FFh, 005h, 0FCh, 001h, 0FDh, 001h, 0FEh, 005h, 0FFh
         DB 005h, 0FCh, 001h, 0FDh, 001h, 0FEh, 005h, 0FFh, 022h, 000h
         DB 001h, 001h, 002h, 003h, 001h, 007h, 001h, 00Fh, 001h, 01Fh
         DB 002h, 03Fh, 001h, 040h, 002h, 080h, 003h, 000h, 001h, 001h
         DB 001h, 0FFh, 001h, 0FEh, 001h, 0FCh, 002h, 0F8h, 001h, 0F0h
         DB 002h, 0E0h, 001h, 0C0h, 001h, 080h, 002h, 000h, 010h, 0FFh
         DB 001h, 0FEh, 001h, 0FCh, 001h, 0FFh, 001h, 011h, 001h, 044h
         DB 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h, 011h
         DB 001h, 044h, 001h, 0FFh, 086h, 000h, 001h, 0FFh, 003h, 000h
         DB 005h, 0FFh, 003h, 040h, 001h, 07Fh, 001h, 080h, 002h, 000h
         DB 005h, 0FFh, 003h, 040h, 001h, 07Fh, 001h, 0C0h, 002h, 000h
         DB 005h, 0FFh, 018h, 000h, 001h, 001h, 001h, 002h, 001h, 007h
         DB 002h, 00Fh, 001h, 01Fh, 001h, 03Fh, 002h, 040h, 001h, 080h
         DB 001h, 000h, 004h, 0FFh, 001h, 0FEh, 001h, 0FCh, 001h, 0FFh
         DB 001h, 00Fh, 001h, 01Fh, 002h, 03Fh, 001h, 07Fh, 003h, 0FFh
         DB 00Bh, 000h, 003h, 0FFh, 002h, 0FEh, 001h, 0FCh, 002h, 0F8h
         DB 001h, 0F0h, 002h, 0E0h, 001h, 0C0h, 002h, 080h, 004h, 000h
         DB 001h, 0FFh, 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h
         DB 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h
lndwr:   DB 0FFh, 086h, 000h, 001h, 0FEh, 001h, 006h, 001h, 00Ah, 001h
         DB 012h, 002h, 0E2h, 001h, 0E4h, 001h, 0E8h, 001h, 0F0h, 003h
         DB 000h, 001h, 0FEh, 001h, 006h, 001h, 00Ah, 001h, 012h, 002h
         DB 0E2h, 001h, 0E4h, 001h, 0E8h, 001h, 0F0h, 003h, 000h, 001h
         DB 0FEh, 001h, 006h, 001h, 00Ah, 001h, 012h, 002h, 0E2h, 001h
         DB 0E4h, 001h, 0E8h, 001h, 0F0h, 012h, 000h, 002h, 01Fh, 001h
         DB 03Fh, 001h, 07Fh, 001h, 0FFh, 001h, 080h, 002h, 000h, 002h
         DB 0FFh, 001h, 0FEh, 001h, 0FCh, 001h, 0FFh, 001h, 00Fh, 001h
         DB 01Fh, 002h, 03Fh, 001h, 0FFh, 001h, 080h, 004h, 000h, 009h
         DB 0FFh, 001h, 001h, 002h, 003h, 002h, 007h, 001h, 00Fh, 002h
         DB 01Fh, 001h, 03Fh, 002h, 07Fh, 001h, 0FFh, 011h, 000h, 001h
         DB 0FFh, 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h
         DB 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h, 0FFh, 0B9h
         DB 000h, 001h, 0FFh, 001h, 0FCh, 001h, 0F8h, 001h, 0F0h, 001h
         DB 0FFh, 001h, 03Fh, 001h, 07Fh, 002h, 0FFh, 003h, 000h, 006h
         DB 0FFh, 001h, 000h, 002h, 001h, 001h, 003h, 001h, 007h, 001h
         DB 0FFh, 001h, 0F8h, 002h, 0F0h, 002h, 0E0h, 002h, 0C0h, 00Dh
         DB 0FFh, 007h, 000h, 002h, 001h, 002h, 003h, 002h, 007h, 002h
         DB 00Fh, 002h, 01Fh, 001h, 0FFh, 001h, 011h, 001h, 044h, 001h
         DB 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h, 011h, 001h
         DB 044h, 001h, 0FFh, 086h, 000h, 001h, 01Fh, 001h, 020h, 001h
         DB 040h, 001h, 080h, 004h, 0FFh, 006h, 0FCh, 001h, 0FDh, 001h
         DB 0FEh, 005h, 0FFh, 005h, 0FCh, 001h, 0FDh, 001h, 0FEh, 005h
         DB 0FFh, 012h, 000h, 001h, 0FFh, 003h, 000h, 005h, 0FFh, 001h
         DB 003h, 001h, 007h, 001h, 00Fh, 001h, 0FFh, 001h, 0F0h, 002h
         DB 0E0h, 001h, 0C0h, 007h, 0FFh, 007h, 000h, 006h, 0FFh, 002h
         DB 0FEh, 002h, 0FCh, 002h, 0F8h, 001h, 0FFh, 001h, 01Fh, 002h
         DB 03Fh, 002h, 07Fh, 00Dh, 0FFh, 001h, 011h, 001h, 044h, 001h
         DB 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h, 011h, 001h
         DB 044h, 001h, 0FFh, 086h, 000h, 001h, 0FFh, 003h, 000h, 004h
         DB 0FFh, 004h, 040h, 001h, 07Fh, 001h, 080h, 002h, 000h, 005h
         DB 0FFh, 003h, 040h, 001h, 07Fh, 001h, 080h, 002h, 000h, 005h
         DB 0FFh, 012h, 000h, 001h, 0FFh, 001h, 01Fh, 001h, 03Fh, 001h
         DB 07Fh, 001h, 0FFh, 002h, 080h, 001h, 000h, 005h, 0FFh, 004h
         DB 000h, 005h, 0FFh, 001h, 0FEh, 001h, 0FFh, 002h, 007h, 002h
         DB 00Fh, 002h, 01Fh, 001h, 03Fh, 001h, 0FFh, 001h, 0C0h, 002h
         DB 080h, 008h, 000h, 013h, 0FFh, 001h, 011h, 001h, 044h, 001h
         DB 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h, 011h, 001h
         DB 044h, 001h, 0FFh, 054h, 000h, 003h, 0FFh, 001h, 000h, 001h
         DB 03Fh, 02Dh, 000h, 001h, 0F0h, 001h, 028h, 001h, 044h, 001h
         DB 082h, 001h, 001h, 001h, 080h, 001h, 0C1h, 001h, 0E2h, 001h
         DB 0F4h, 001h, 0F8h, 001h, 0F9h, 001h, 0FAh, 001h, 0FEh, 001h
         DB 0F9h, 001h, 0F0h, 002h, 0E0h, 001h, 0F0h, 001h, 0F8h, 001h
         DB 0FCh, 001h, 0FEh, 003h, 01Fh, 001h, 0FFh, 003h, 01Fh, 001h
         DB 0FEh, 001h, 0FCh, 001h, 0F8h, 001h, 0F0h, 001h, 0E0h, 012h
         DB 000h, 005h, 0FFh, 001h, 001h, 002h, 003h, 001h, 0FFh, 001h
         DB 0FCh, 002h, 0F8h, 001h, 0FFh, 001h, 01Fh, 002h, 03Fh, 001h
         DB 07Fh, 001h, 0FFh, 002h, 080h, 003h, 000h, 009h, 0FFh, 00Bh
         DB 000h, 013h, 0FFh, 001h, 011h, 001h, 044h, 001h, 011h, 001h
         DB 044h, 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h
         DB 0FFh, 045h, 000h, 002h, 03Fh, 001h, 000h, 002h, 03Fh, 002h
         DB 000h, 001h, 03Ch, 003h, 040h, 001h, 03Ch, 003h, 000h, 003h
         DB 0FFh, 001h, 000h, 001h, 0FFh, 032h, 000h, 005h, 080h, 004h
         DB 000h, 001h, 080h, 001h, 040h, 001h, 020h, 001h, 010h, 001h
         DB 030h, 001h, 050h, 001h, 090h, 004h, 010h, 001h, 020h, 001h
         DB 040h, 001h, 080h, 017h, 000h, 001h, 0FFh, 001h, 0C0h, 002h
         DB 080h, 005h, 0FFh, 003h, 000h, 006h, 0FFh, 005h, 000h, 009h
         DB 0FFh, 003h, 000h, 005h, 001h, 003h, 003h, 001h, 0FFh, 001h
         DB 0FEh, 004h, 0FCh, 005h, 0F8h, 005h, 0F0h, 002h, 0E0h, 001h
         DB 0FFh, 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h
         DB 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h, 0FFh, 045h
         DB 000h, 002h, 0E0h, 001h, 030h, 001h, 098h, 001h, 0CCh, 001h
         DB 067h, 001h, 033h, 001h, 019h, 001h, 00Ch, 001h, 006h, 001h
         DB 003h, 001h, 001h, 003h, 000h, 003h, 0FFh, 001h, 000h, 001h
         DB 0FFh, 02Dh, 000h, 001h, 01Fh, 001h, 020h, 001h, 040h, 001h
         DB 080h, 005h, 0FFh, 005h, 0FCh, 001h, 0FDh, 001h, 0FEh, 005h
         DB 0FFh, 005h, 0FCh, 001h, 0FDh, 001h, 0FEh, 005h, 0FFh, 012h
         DB 000h, 001h, 0FFh, 001h, 001h, 002h, 003h, 001h
ljlhs:   DB 0FFh, 002h, 0FEh, 001h, 0FCh, 001h, 0FFh, 003h, 007h, 001h
         DB 0FFh, 003h, 0F8h, 001h, 0F0h, 001h, 0FFh, 003h, 01Fh, 002h
         DB 03Fh, 001h, 0FFh, 002h, 0E0h, 004h, 0C0h, 001h, 080h, 00Dh
         DB 0FFh, 011h, 000h, 001h, 0FFh, 001h, 011h, 001h, 044h, 001h
         DB 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h, 011h, 001h
         DB 044h, 001h, 0FFh, 046h, 000h, 001h, 008h, 001h, 01Ch, 001h
         DB 036h, 001h, 063h, 001h, 0C9h, 001h, 09Ch, 001h, 036h, 001h
         DB 063h, 001h, 0C1h, 001h, 080h, 004h, 000h, 003h, 0FFh, 001h
         DB 000h, 001h, 0FFh, 02Dh, 000h, 001h, 0FFh, 003h, 000h, 005h
         DB 0FFh, 003h, 040h, 001h, 07Fh, 001h, 080h, 002h, 000h, 005h
         DB 0FFh, 003h, 040h, 001h, 07Fh, 001h, 0C0h, 002h, 000h, 005h
         DB 0FFh, 012h, 000h, 005h, 0FFh, 003h, 000h, 005h, 0FFh, 004h
         DB 000h, 007h, 0FFh, 007h, 000h, 00Dh, 0FFh, 011h, 000h, 001h
         DB 0FFh, 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h
         DB 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h, 0FFh, 045h
         DB 000h, 001h, 001h, 001h, 003h, 001h, 006h, 001h, 00Ch, 001h
         DB 019h, 001h, 0B3h, 001h, 0E6h, 001h, 04Ch, 001h, 018h, 001h
         DB 0B0h
lkany:   DB 001h, 0E0h, 001h, 040h, 003h, 000h, 003h, 0FFh, 001h, 000h
         DB 001h, 0FFh, 02Dh, 000h, 001h, 0FEh, 001h, 006h, 001h, 00Ah
         DB 001h, 012h, 002h, 0E2h, 001h, 0E4h, 001h, 0E8h, 001h, 0F0h
         DB 003h, 000h, 001h, 0FEh, 001h, 006h, 001h, 00Ah, 001h, 012h
         DB 002h, 0E2h, 001h, 0E4h, 001h, 0E8h, 001h, 0F0h, 003h, 000h
         DB 001h, 0FEh, 001h, 006h, 001h, 00Ah, 001h, 012h, 002h, 0E2h
         DB 001h, 0E4h, 001h, 0E8h, 001h, 0F0h, 012h, 000h, 001h, 0FFh
         DB 003h, 0FCh, 001h, 0FFh, 003h, 003h, 005h, 0FFh, 001h, 001h
         DB 003h, 000h, 007h, 0FFh, 007h, 000h, 00Dh, 0FFh, 011h, 000h
         DB 001h, 0FFh, 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h
         DB 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h, 0FFh
         DB 045h, 000h, 002h, 0FEh, 001h, 000h, 002h, 0FEh, 002h, 000h
         DB 001h, 00Fh, 003h, 010h, 001h, 00Fh, 003h, 000h, 003h, 0FFh
         DB 001h, 000h, 001h, 0FFh, 060h, 000h, 001h, 0FFh, 003h, 000h
         DB 005h, 0FFh, 003h, 000h, 006h, 0FFh, 001h, 080h, 004h, 0C0h
         DB 001h, 0FFh, 005h, 03Fh, 002h, 01Fh, 001h, 0FFh, 002h, 0F0h
         DB 005h, 0F8h, 004h, 0FCh, 001h, 0FFh, 005h, 003h, 005h, 001h
         DB 007h, 000h, 001h, 0FFh, 001h, 011h, 001h, 044h, 001h, 011h
         DB 001h, 044h, 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h
         DB 001h, 0FFh, 054h, 000h, 003h, 0FFh, 001h, 000h, 001h, 0FEh
         DB 02Dh, 000h, 001h, 01Fh, 001h, 020h, 001h, 040h, 001h, 080h
         DB 005h, 0FFh, 006h, 0FCh, 001h, 0FDh, 001h, 0FEh, 005h, 0FFh
         DB 009h, 0FCh, 001h, 0FDh, 001h, 0FEh, 012h, 000h, 001h, 0FFh
         DB 001h, 01Fh, 002h, 00Fh, 001h, 0FFh, 001h, 0FCh, 002h, 0FEh
         DB 001h, 0FFh, 002h, 001h, 001h, 000h, 006h, 0FFh, 005h, 000h
         DB 009h, 0FFh, 00Bh, 000h, 010h, 0FFh, 002h, 07Fh, 001h, 0FFh
         DB 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h, 011h
         DB 001h, 044h, 001h, 011h, 001h, 044h, 001h, 0FFh, 054h, 000h
         DB 003h, 080h, 02Fh, 000h, 001h, 0FFh, 003h, 000h, 005h, 0FFh
         DB 004h, 040h, 001h, 07Fh, 001h, 080h, 002h, 000h, 005h, 0FFh
         DB 008h, 040h, 001h, 080h, 014h, 000h, 005h, 0FFh, 003h, 000h
         DB 005h, 0FFh, 002h, 0C0h, 002h, 0E0h, 001h, 0FFh, 001h, 01Fh
         DB 002h, 00Fh, 002h, 007h, 001h, 0FFh, 002h, 0FEh, 006h, 0FFh
         DB 00Bh, 000h, 013h, 0FFh, 001h, 011h, 001h, 044h, 001h, 011h
         DB 001h, 044h, 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h
         DB 001h, 0FFh, 086h, 000h, 001h, 0FCh, 001h, 006h, 001h, 009h
         DB 001h, 010h, 001h, 0E0h, 001h, 0F0h, 001h, 0F8h, 001h, 0FCh
         DB 001h, 0FEh, 004h, 01Fh, 001h, 0FFh, 003h, 01Fh, 001h, 0FEh
         DB 001h, 0FCh, 001h, 0F8h, 001h, 0F0h, 001h, 0E0h, 01Dh, 000h
         DB 001h, 0FFh, 002h, 0E0h, 001h, 0F0h, 001h, 0FFh, 001h, 00Fh
         DB 002h, 007h, 001h, 0FFh, 001h, 0FEh, 003h, 0FFh, 004h, 000h
         DB 007h, 0FFh, 004h, 000h, 002h, 080h, 001h, 0C0h, 001h, 0FFh
         DB 002h, 03Fh, 002h, 01Fh, 003h, 00Fh, 002h, 007h, 002h, 003h
         DB 013h, 0FFh, 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h
         DB 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h, 0FFh
         DB 089h, 000h, 001h, 080h, 001h, 040h, 001h, 020h, 001h, 030h
         DB 001h, 050h, 001h, 090h, 005h, 010h, 001h, 020h, 001h, 040h
         DB 001h, 080h, 022h, 000h, 001h, 0FFh, 001h, 001h, 002h, 000h
         DB 005h, 0FFh, 003h, 000h, 001h, 0FFh, 002h, 07Fh, 002h, 03Fh
         DB 001h, 0FFh, 001h, 0F0h, 002h, 0F8h, 001h, 0FCh, 001h, 0FEh
         DB 001h, 0FFh, 002h, 001h, 005h, 000h, 00Dh, 0FFh, 001h, 000h
         DB 002h, 080h, 002h, 0C0h, 002h, 0E0h, 003h, 0F0h, 002h, 0F8h
         DB 002h, 0FCh, 002h, 0FEh, 002h, 0FFh, 001h, 011h, 001h, 044h
         DB 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h, 011h
         DB 001h, 044h, 001h, 0FFh, 086h, 000h, 001h, 01Fh, 001h, 020h
         DB 001h, 040h, 001h, 080h, 005h, 0FFh, 011h, 0FCh, 001h, 0FDh
         DB 001h, 0FEh, 005h, 0FFh, 012h, 000h, 001h, 0FCh, 001h, 0FEh
         DB 001h, 0FFh, 001h, 07Fh, 001h, 0FFh, 001h, 0E0h, 002h, 0F0h
         DB 001h, 0FFh, 002h, 007h, 001h, 003h, 006h, 0FFh, 005h, 000h
         DB 005h, 0FFh, 002h, 07Fh, 001h, 03Fh, 001h, 0FFh, 001h, 0F0h
         DB 002h, 0F8h, 002h, 0FCh, 002h, 0FEh, 005h, 0FFh, 011h, 000h
         DB 001h, 0FFh, 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h
         DB 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h, 0FFh
         DB 086h, 000h, 001h, 0FFh, 003h, 000h, 005h, 0FFh, 00Fh, 040h
         DB 001h, 07Fh, 001h, 0C0h, 002h, 000h, 005h, 0FFh, 015h, 000h
         DB 002h, 080h, 001h, 040h, 001h, 020h, 001h, 010h, 001h, 0F0h
         DB 001h, 0F8h, 001h, 0FCh, 002h, 0FEh, 001h, 001h, 001h, 080h
         DB 002h, 0C0h, 001h, 0FFh, 001h, 03Fh, 001h, 01Fh, 002h, 00Fh
         DB 001h, 007h, 001h, 0FFh, 001h, 0FEh, 007h, 0FFh, 008h, 000h
         DB 002h, 080h, 001h, 0C0h, 001h, 0FFh, 002h, 03Fh, 002h, 01Fh
         DB 001h, 00Fh, 002h, 007h, 002h, 003h, 002h, 001h, 006h, 000h
         DB 001h, 0FFh, 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h
         DB 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h, 0FFh
         DB 086h, 000h, 001h, 0FEh, 001h, 006h, 001h, 00Ah, 001h, 012h
         DB 002h, 0E2h, 001h, 0E4h, 001h, 0E8h, 001h, 0F0h, 00Fh, 000h
         DB 001h, 0FEh, 001h, 006h, 001h, 00Ah, 001h, 012h, 002h, 0E2h
         DB 001h, 0E4h, 001h, 0E8h, 001h, 0F0h, 020h, 000h, 001h, 080h
         DB 002h, 040h, 001h, 0E0h, 001h, 0F0h, 002h, 0F8h, 001h, 0FCh
         DB 001h, 0FEh, 001h, 0FFh, 001h, 001h, 001h, 000h, 002h, 080h
         DB 001h, 0C0h, 002h, 0E0h, 001h, 0FFh, 002h, 00Fh, 001h, 007h
         DB 002h, 003h, 001h, 001h, 005h, 000h, 00Eh, 0FFh, 001h, 07Fh
         DB 002h, 03Fh, 001h, 01Fh, 001h, 0FFh, 001h, 011h, 001h, 044h
         DB 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h, 011h
         DB 001h, 044h, 001h, 0FFh, 0D2h, 000h, 001h, 080h, 001h, 040h
         DB 002h, 020h, 001h, 010h, 001h, 008h, 001h, 0FCh, 002h, 0FEh
         DB 006h, 0FFh, 001h, 07Fh, 002h, 03Fh, 001h, 0FFh, 002h, 0F8h
         DB 002h, 0FCh, 001h, 0FEh, 00Dh, 0FFh, 001h, 011h, 001h, 044h
         DB 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h, 011h
         DB 001h, 044h, 001h, 0FFh, 086h, 000h, 001h, 00Fh, 001h, 010h
         DB 001h, 021h, 001h, 042h, 00Dh, 0FCh, 001h, 0FDh, 005h, 0FFh
         DB 001h, 0FEh, 007h, 0FCh, 001h, 0FDh, 001h, 0FEh, 035h, 000h
         DB 001h, 080h, 002h, 0C0h, 001h, 0E0h, 001h, 0F0h, 002h, 0F8h
         DB 001h, 0FCh, 001h, 0FEh, 001h, 003h, 001h, 001h, 005h, 000h
         DB 001h, 080h, 002h, 0C0h, 001h, 0E0h, 002h, 0F0h, 001h, 0F8h
         DB 002h, 0FCh, 001h, 0FEh, 001h, 0FFh, 001h, 011h, 001h, 044h
         DB 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h, 011h
         DB 001h, 044h, 001h, 0FFh, 086h, 000h, 002h, 0C0h, 001h, 041h
         DB 001h, 042h, 008h, 047h, 001h, 04Fh, 001h, 05Fh, 002h, 07Fh
         DB 002h, 0FFh, 001h, 0F7h, 001h, 0E7h, 002h, 0C7h, 008h, 047h
         DB 001h, 087h, 002h, 007h, 040h, 000h, 001h, 080h, 001h, 040h
         DB 002h, 020h, 001h, 010h, 001h, 008h, 002h, 004h, 001h, 002h
         DB 001h, 001h, 005h, 000h, 001h, 0FFh, 001h, 011h, 001h, 044h
         DB 001h, 011h, 001h, 044h, 001h, 011h, 001h, 044h, 001h, 011h
         DB 001h, 044h, 001h, 0FFh, 086h, 000h, 001h, 07Eh, 001h, 086h
         DB 001h, 00Ah, 001h, 012h, 01Ah, 0E2h, 001h, 0E4h, 001h, 0E8h
         DB 001h, 0F0h, 04Ah, 000h, 002h, 080h, 001h, 040h, 001h, 020h
         DB 001h, 010h, 001h, 0F0h, 001h, 010h, 001h, 050h, 001h, 010h
         DB 001h, 050h, 001h
END